import {
  WasteFleetVehicle,
  WasteCollectionBin,
  FestronikManifestB3,
  WeighbridgeRecord,
  WasteCrewMember
} from '../types';

export const MOCK_WASTE_FLEETS: WasteFleetVehicle[] = [
  {
    id: 'w-fl-01',
    hullNumber: 'COMP-JAK-101',
    plateNumber: 'B 9412 TPA',
    vehicleType: 'COMPACTOR_TRUCK',
    cargoCategory: 'DOMESTIC_MUNICIPAL',
    capacityM3: 12,
    maxPayloadTons: 8.5,
    currentPayloadTons: 6.8,
    compactorFillRatePct: 80,
    odometerKm: 64210,
    hydraulicStatus: 'OPTIMAL',
    leachateDrainValve: 'CLOSED_SEALED',
    gpsLocation: {
      lat: -6.2297,
      lng: 106.8271,
      speedKmh: 24,
      address: 'Jl. Rasuna Said, Kuningan, Jakarta Selatan',
      zone: 'Sektor Selatan 3 - Kuningan'
    },
    currentStatus: 'ON_COLLECTION_ROUTE',
    currentDriver: 'Suparman Hadi',
    driverPhone: '+62 812-7788-9901',
    assignedCrewCount: 3,
    activeRouteName: 'Rute Pagi: Sudirman - Kuningan TPS Commercial',
    currentTpaDestination: 'TPST Bantargebang - Zona IV',
    kirExpiry: '2027-02-15',
    klhkLicenseExpiry: '2027-08-30'
  },
  {
    id: 'w-fl-02',
    hullNumber: 'ARM-ROLL-205',
    plateNumber: 'B 9801 DKP',
    vehicleType: 'ARM_ROLL_TRUCK',
    cargoCategory: 'COMMERCIAL_ORGANIC',
    capacityM3: 8,
    maxPayloadTons: 6.0,
    currentPayloadTons: 5.4,
    compactorFillRatePct: 90,
    odometerKm: 89400,
    hydraulicStatus: 'OPTIMAL',
    leachateDrainValve: 'CLOSED_SEALED',
    gpsLocation: {
      lat: -6.3482,
      lng: 106.9934,
      speedKmh: 42,
      address: 'Jl. Raya Narogong KM 12, Pangkalan 5',
      zone: 'Koridor Menuju TPST Bantargebang'
    },
    currentStatus: 'EN_ROUTE_TO_TPA',
    currentDriver: 'Dedi Kurniawan',
    driverPhone: '+62 813-4455-6677',
    assignedCrewCount: 2,
    activeRouteName: 'Swap Kontainer Pasar Induk Kramat Jati',
    currentTpaDestination: 'TPST Bantargebang - Zona II Tipping Floor',
    kirExpiry: '2026-11-20',
    klhkLicenseExpiry: '2027-05-18'
  },
  {
    id: 'w-fl-03',
    hullNumber: 'MED-B3-COLD-01',
    plateNumber: 'B 9233 BZZ',
    vehicleType: 'MEDICAL_B3_COLD_BOX',
    cargoCategory: 'MEDICAL_BIOHAZARD',
    capacityM3: 10,
    maxPayloadTons: 4.5,
    currentPayloadTons: 2.1,
    compactorFillRatePct: 46,
    odometerKm: 38200,
    hydraulicStatus: 'OPTIMAL',
    leachateDrainValve: 'CLOSED_SEALED',
    coldBoxTempC: 3.2,
    gpsLocation: {
      lat: -6.1823,
      lng: 106.8432,
      speedKmh: 0,
      address: 'Area Loading Bay B3 RSUPN Dr. Cipto Mangunkusumo (RSCM)',
      zone: 'Fasilitas Kesehatan Jakarta Pusat'
    },
    currentStatus: 'ON_COLLECTION_ROUTE',
    currentDriver: 'Ahmad Faisal B3',
    driverPhone: '+62 811-9988-1234',
    assignedCrewCount: 2,
    activeRouteName: 'Rute Khusus Limbah Medis RS Jakarta Pusat',
    currentTpaDestination: 'Insinerator Terpadu PT PPLI Cileungsi',
    festronikManifestNo: 'FES-KLHK-2026-MED-8910',
    kirExpiry: '2027-01-10',
    klhkLicenseExpiry: '2027-10-15'
  },
  {
    id: 'w-fl-04',
    hullNumber: 'VAC-SLUDGE-401',
    plateNumber: 'B 9552 TJA',
    vehicleType: 'VACUUM_SLUDGE_TRUCK',
    cargoCategory: 'SEPTIC_SLUDGE_IPAL',
    capacityM3: 5,
    maxPayloadTons: 5.5,
    currentPayloadTons: 4.8,
    compactorFillRatePct: 96,
    odometerKm: 72150,
    hydraulicStatus: 'OPTIMAL',
    leachateDrainValve: 'CLOSED_SEALED',
    gpsLocation: {
      lat: -6.1421,
      lng: 106.8872,
      speedKmh: 18,
      address: 'Jl. Danau Sunter Utara, Tanjung Priok',
      zone: 'Koridor Menuju IPLT Duri Kosambi'
    },
    currentStatus: 'EN_ROUTE_TO_TPA',
    currentDriver: 'Bambang Irawan',
    driverPhone: '+62 856-1122-3344',
    assignedCrewCount: 2,
    activeRouteName: 'Order Sedot Tinja Mall Sunter & Hotel Danau',
    currentTpaDestination: 'IPLT Duri Kosambi / Pulo Gebang',
    kirExpiry: '2026-12-05',
    klhkLicenseExpiry: '2027-04-12'
  },
  {
    id: 'w-fl-05',
    hullNumber: 'HOOK-IND-502',
    plateNumber: 'B 9044 BGA',
    vehicleType: 'HOOK_LIFT_TRUCK',
    cargoCategory: 'HAZARDOUS_B3_INDUSTRIAL',
    capacityM3: 15,
    maxPayloadTons: 10.0,
    currentPayloadTons: 8.9,
    compactorFillRatePct: 89,
    odometerKm: 105200,
    hydraulicStatus: 'OPTIMAL',
    leachateDrainValve: 'CLOSED_SEALED',
    gpsLocation: {
      lat: -6.3688,
      lng: 107.0122,
      speedKmh: 0,
      address: 'Gerbang Timbang Masuk Jembatan Timbang TPST Bantargebang',
      zone: 'Weighbridge Gate 1'
    },
    currentStatus: 'WEIGHBRIDGE_QUEUE',
    currentDriver: 'Mulyadi Pratama',
    driverPhone: '+62 818-0909-1212',
    assignedCrewCount: 2,
    activeRouteName: 'Sludge IPAL Kawasan Industri MM2100',
    currentTpaDestination: 'PT Wastec / PPLI Cileungsi',
    festronikManifestNo: 'FES-KLHK-2026-IND-4421',
    kirExpiry: '2027-03-22',
    klhkLicenseExpiry: '2027-09-01'
  }
];

export const MOCK_COLLECTION_BINS: WasteCollectionBin[] = [
  {
    id: 'bin-01',
    binCode: 'BIN-KNG-001',
    name: 'TPS 3R Rasuna Said Mega Kuningan',
    category: 'MALL_HOTEL',
    address: 'Kawasan Mega Kuningan Kav. E4, Setiabudi',
    coordinates: { lat: -6.2289, lng: 106.8265 },
    capacityM3: 10,
    fillLevelPct: 88,
    sensorStatus: 'OVERFLOW_ALERT',
    lastEmptiedAt: '2026-08-20 22:30',
    scheduledPickupTime: '2026-08-21 06:00',
    assignedVehicleHull: 'COMP-JAK-101',
    rfidTag: 'RFID-BIN-KNG-9912'
  },
  {
    id: 'bin-02',
    binCode: 'BIN-KRMT-002',
    name: 'Kontainer Arm Roll Pasar Kramat Jati Bay A',
    category: 'PUBLIC_MARKET',
    address: 'Jl. Raya Bogor KM 19, Kramat Jati',
    coordinates: { lat: -6.2842, lng: 106.8671 },
    capacityM3: 8,
    fillLevelPct: 95,
    sensorStatus: 'OVERFLOW_ALERT',
    lastEmptiedAt: '2026-08-21 01:15',
    scheduledPickupTime: '2026-08-21 07:30',
    assignedVehicleHull: 'ARM-ROLL-205',
    rfidTag: 'RFID-BIN-KRMT-8841'
  },
  {
    id: 'bin-03',
    binCode: 'BIN-MED-RSCM',
    name: 'Depo Limbah B3 Medis RSCM Paviliun Kiara',
    category: 'HOSPITAL',
    address: 'Jl. Diponegoro No. 71, Senen, Jakpus',
    coordinates: { lat: -6.1965, lng: 106.8488 },
    capacityM3: 4,
    fillLevelPct: 45,
    sensorStatus: 'NORMAL',
    lastEmptiedAt: '2026-08-21 05:00',
    scheduledPickupTime: '2026-08-21 10:00',
    assignedVehicleHull: 'MED-B3-COLD-01',
    rfidTag: 'RFID-BIN-MED-7719'
  },
  {
    id: 'bin-04',
    binCode: 'BIN-IND-MM2100',
    name: 'Bak Penampung Sludge IPAL PT Toyota MM2100',
    category: 'FACTORY_INDUSTRIAL',
    address: 'Kawasan Industri MM2100 Blok H-2, Cikarang',
    coordinates: { lat: -6.2991, lng: 107.0988 },
    capacityM3: 15,
    fillLevelPct: 90,
    sensorStatus: 'NORMAL',
    lastEmptiedAt: '2026-08-20 18:00',
    scheduledPickupTime: '2026-08-21 08:00',
    assignedVehicleHull: 'HOOK-IND-502',
    rfidTag: 'RFID-BIN-IND-3341'
  }
];

export const MOCK_FESTRONIK_MANIFESTS: FestronikManifestB3[] = [
  {
    id: 'fest-01',
    manifestNumber: 'FES-KLHK-2026-MED-8910',
    klhkRegistrationNo: 'KLHK-B3-TRANSP-0914/2026',
    wasteCode: 'A337-1',
    wasteName: 'Limbah Medis Klinis Infeksius & Benda Tajam (Spuit/Jarum)',
    generatorName: 'RSUPN Dr. Cipto Mangunkusumo (RSCM)',
    transporterName: 'PT Nusantara Waste Trans Logistics B3',
    receiverProcessorName: 'PT Prasadha Pamunah Limbah Industri (PPLI) Cileungsi',
    volumeTons: 2.1,
    packagingType: 'SAFETY_BOX_BIOHAZARD',
    packagingCount: 42,
    status: 'IN_TRANSIT',
    assignedHull: 'MED-B3-COLD-01',
    driverName: 'Ahmad Faisal B3',
    qrCodeUrl: 'https://festronik.menlhk.go.id/verify/FES-KLHK-2026-MED-8910',
    departureDate: '2026-08-21 06:30 WIB',
    emergencyPhone: '021-8674060'
  },
  {
    id: 'fest-02',
    manifestNumber: 'FES-KLHK-2026-IND-4421',
    klhkRegistrationNo: 'KLHK-B3-TRANSP-0914/2026',
    wasteCode: 'B351-1',
    wasteName: 'Sludge IPAL Instalasi Pengolahan Air Limbah Industri Otomotif',
    generatorName: 'PT Toyota Motor Manufacturing Indonesia',
    transporterName: 'PT Nusantara Waste Trans Logistics B3',
    receiverProcessorName: 'PT Wastec International - Cilegon Plant',
    volumeTons: 8.9,
    packagingType: 'JUMBO_BAG',
    packagingCount: 9,
    status: 'IN_TRANSIT',
    assignedHull: 'HOOK-IND-502',
    driverName: 'Mulyadi Pratama',
    qrCodeUrl: 'https://festronik.menlhk.go.id/verify/FES-KLHK-2026-IND-4421',
    departureDate: '2026-08-21 05:45 WIB',
    emergencyPhone: '0254-311220'
  },
  {
    id: 'fest-03',
    manifestNumber: 'FES-KLHK-2026-OIL-3012',
    klhkRegistrationNo: 'KLHK-B3-TRANSP-0914/2026',
    wasteCode: 'B105d',
    wasteName: 'Minyak Pelumas Bekas (Used Engine Oil) / Filter Oli',
    generatorName: 'PT United Tractors Tbk - Cakung Plant',
    transporterName: 'PT Nusantara Waste Trans Logistics B3',
    receiverProcessorName: 'PT Wiraswasta Gemilang Indonesia (WGI Oil Re-refining)',
    volumeTons: 6.5,
    packagingType: 'DRUM_200L',
    packagingCount: 30,
    status: 'ACCEPTED_RECEIVER',
    assignedHull: 'ARM-ROLL-205',
    driverName: 'Dedi Kurniawan',
    qrCodeUrl: 'https://festronik.menlhk.go.id/verify/FES-KLHK-2026-OIL-3012',
    departureDate: '2026-08-20 14:00 WIB',
    emergencyPhone: '021-8980111'
  }
];

export const MOCK_WEIGHBRIDGE_RECORDS: WeighbridgeRecord[] = [
  {
    id: 'wb-01',
    ticketNumber: 'WB-BTG-20260821-0814',
    tpaName: 'TPST Bantargebang Bekasi',
    hullNumber: 'COMP-JAK-101',
    plateNumber: 'B 9412 TPA',
    driverName: 'Suparman Hadi',
    wasteCategory: 'DOMESTIC_MUNICIPAL',
    grossWeightKg: 14850,
    tareWeightKg: 8050,
    netWeightKg: 6800,
    netWeightTons: 6.8,
    tippingFloorZone: 'Zona IV - Power Plant Waste-to-Energy (PLTSa)',
    inTimestamp: '07:15 WIB',
    outTimestamp: '07:38 WIB',
    operatorName: 'Rian Hidayat (Dishub DLH)',
    tippingFeeRp: 476000,
    paymentStatus: 'CONTRACT_ACCOUNT'
  },
  {
    id: 'wb-02',
    ticketNumber: 'WB-BTG-20260821-0815',
    tpaName: 'TPST Bantargebang Bekasi',
    hullNumber: 'ARM-ROLL-205',
    plateNumber: 'B 9801 DKP',
    driverName: 'Dedi Kurniawan',
    wasteCategory: 'COMMERCIAL_ORGANIC',
    grossWeightKg: 11400,
    tareWeightKg: 6000,
    netWeightKg: 5400,
    netWeightTons: 5.4,
    tippingFloorZone: 'Zona II - Komposting Organik Pasar',
    inTimestamp: '07:45 WIB',
    outTimestamp: '08:05 WIB',
    operatorName: 'Rian Hidayat (Dishub DLH)',
    tippingFeeRp: 378000,
    paymentStatus: 'CONTRACT_ACCOUNT'
  },
  {
    id: 'wb-03',
    ticketNumber: 'WB-PPLI-20260821-0209',
    tpaName: 'Fasilitas Terpadu PPLI Cileungsi',
    hullNumber: 'MED-B3-COLD-01',
    plateNumber: 'B 9233 BZZ',
    driverName: 'Ahmad Faisal B3',
    wasteCategory: 'MEDICAL_BIOHAZARD',
    grossWeightKg: 6600,
    tareWeightKg: 4500,
    netWeightKg: 2100,
    netWeightTons: 2.1,
    tippingFloorZone: 'Insinerator Suhu Tinggi 1200°C - Unit 3',
    inTimestamp: '08:12 WIB',
    outTimestamp: '08:40 WIB',
    operatorName: 'Dr. Hendra (PPLI Gate QC)',
    tippingFeeRp: 18900000,
    paymentStatus: 'BILLED_RETRIBUTION'
  }
];

export const MOCK_WASTE_CREWS: WasteCrewMember[] = [
  {
    id: 'crew-01',
    name: 'Suparman Hadi',
    nik: 'DLH-JKT-1092',
    role: 'CHIEF_DRIVER',
    assignedHull: 'COMP-JAK-101',
    depotBase: 'Depo Kebersihan Setiabudi Jaksel',
    shift: 'PAGI_SUBUH',
    attendanceStatus: 'HADIR_ON_DUTY',
    dailyPayloadTonsCollected: 13.6,
    dailyTripsCompleted: 2,
    safetyPpeCompliancePct: 100,
    healthFitnessStatus: 'FIT'
  },
  {
    id: 'crew-02',
    name: 'Rahmat Santoso',
    nik: 'DLH-JKT-2841',
    role: 'HYDRAULIC_OPERATOR',
    assignedHull: 'COMP-JAK-101',
    depotBase: 'Depo Kebersihan Setiabudi Jaksel',
    shift: 'PAGI_SUBUH',
    attendanceStatus: 'HADIR_ON_DUTY',
    dailyPayloadTonsCollected: 13.6,
    dailyTripsCompleted: 2,
    safetyPpeCompliancePct: 98,
    healthFitnessStatus: 'FIT'
  },
  {
    id: 'crew-03',
    name: 'Ahmad Faisal B3',
    nik: 'MED-B3-4491',
    role: 'CHIEF_DRIVER',
    assignedHull: 'MED-B3-COLD-01',
    depotBase: 'Depo Khusus Limbah B3 Cakung',
    shift: 'PAGI_SUBUH',
    attendanceStatus: 'HADIR_ON_DUTY',
    dailyPayloadTonsCollected: 2.1,
    dailyTripsCompleted: 1,
    safetyPpeCompliancePct: 100,
    healthFitnessStatus: 'FIT'
  },
  {
    id: 'crew-04',
    name: 'Bambang Irawan',
    nik: 'VAC-IPLT-5512',
    role: 'CHIEF_DRIVER',
    assignedHull: 'VAC-SLUDGE-401',
    depotBase: 'Pool Truk IPLT Duri Kosambi',
    shift: 'PAGI_SUBUH',
    attendanceStatus: 'HADIR_ON_DUTY',
    dailyPayloadTonsCollected: 4.8,
    dailyTripsCompleted: 1,
    safetyPpeCompliancePct: 100,
    healthFitnessStatus: 'FIT'
  }
];
