/**
 * Fleet Intelligence Smart AI - Fuel Anomaly & Theft Risk Detection Engine
 * Multi-layer telemetry intelligence evaluating sensor level drops, ignition status,
 * vehicle movement, geofencing, refueling reconciliation, and maintenance correlation.
 *
 * NOTE (PROMPT 30 Safety Rule):
 * AI MUST NOT assert theft as a proven fact without human verification.
 * Always classify as "Potential Fuel Theft Indicator" or "Fuel Drain Event".
 */

import {
  FuelAnomalyItem,
  FuelTheftIndicator,
  FuelDrainItem,
  RefuelingAuditItem,
  FuelTheftRiskLevel,
  FuelAnomalySeverity,
  FuelFilterState,
} from '../types';

export class FuelAnomalyEngine {
  /**
   * Generates Comprehensive Fuel Anomalies list
   */
  public getFuelAnomalies(): FuelAnomalyItem[] {
    return [
      {
        id: 'fanom-01',
        vehicleId: 'veh-001',
        plateNumber: 'B 9876 XYZ',
        driverId: 'drv-01',
        driverName: 'Ahmad Sudrajat',
        tripId: 'trp-101',
        timestamp: '2026-08-15T02:14:00Z',
        anomalyType: 'UNEXPECTED_FUEL_DROP',
        anomalyScore: 88,
        severity: 'CRITICAL',
        fuelLevelBefore: 74, // %
        fuelLevelAfter: 46, // %
        fuelDifferenceLiters: 84.0, // 28% drop in 300L tank
        fuelDifferencePercentage: -28.0,
        durationMinutes: 12,
        distanceTravelledKm: 0.2,
        ignitionStatus: false,
        speedKmH: 0,
        latitude: -6.2942,
        longitude: 107.1645,
        locationName: 'Area Parkir Liar Cikarang Barat (Luar Geofence)',
        insideGeofence: false,
        evidenceQuality: 'HIGH',
        evidenceDescription: 'Penurunan 84 Liter dalam 12 menit saat mesin MATI (Ignition OFF) dan kendaraan parkir diam tanpa transaksi SPBU.',
        status: 'NEW',
      },
      {
        id: 'fanom-02',
        vehicleId: 'veh-003',
        plateNumber: 'B 9555 TTT',
        driverId: 'drv-03',
        driverName: 'Eko Prasetyo',
        tripId: 'trp-108',
        timestamp: '2026-08-14T21:40:00Z',
        anomalyType: 'REFUELING_MISMATCH',
        anomalyScore: 78,
        severity: 'HIGH',
        fuelLevelBefore: 30,
        fuelLevelAfter: 65,
        fuelDifferenceLiters: 70.0, // Sensor detected +70L, but receipt was 120L
        fuelDifferencePercentage: 35.0,
        durationMinutes: 15,
        distanceTravelledKm: 0,
        ignitionStatus: false,
        speedKmH: 0,
        latitude: -6.5312,
        longitude: 107.8211,
        locationName: 'Rest Area KM 102 Tol Cipali',
        insideGeofence: true,
        geofenceName: 'SPBU Rest Area KM 102',
        evidenceQuality: 'HIGH',
        evidenceDescription: 'Kuitansi transaksi mencatat 120 Liter, namun sensor tangki hanya mencatat kenaikan 70 Liter (Selisih 50 Liter).',
        status: 'UNDER_REVIEW',
        reviewedBy: 'Supervisor BBM Cikarang',
        reviewedAt: '2026-08-15T08:30:00Z',
        investigationNotes: 'Sedang dilakukan klarifikasi struk pembayaran ke pihak SPBU Rest Area KM 102.',
      },
      {
        id: 'fanom-03',
        vehicleId: 'veh-006',
        plateNumber: 'B 9202 EF',
        driverId: 'drv-04',
        driverName: 'Doni Firmansyah',
        tripId: 'trp-115',
        timestamp: '2026-08-13T14:22:00Z',
        anomalyType: 'ABNORMAL_CONSUMPTION',
        anomalyScore: 65,
        severity: 'WARNING',
        fuelLevelBefore: 85,
        fuelLevelAfter: 52,
        fuelDifferenceLiters: 132.0,
        fuelDifferencePercentage: -33.0,
        durationMinutes: 140,
        distanceTravelledKm: 120.0,
        ignitionStatus: true,
        speedKmH: 52,
        latitude: -6.7451,
        longitude: 107.4892,
        locationName: 'Tol Cipularang KM 90 - 105',
        insideGeofence: false,
        evidenceQuality: 'MEDIUM',
        evidenceDescription: 'Konsumsi melonjak ke 42.1 L/100km saat melintasi rute tanjakan dengan muatan berat.',
        status: 'VERIFIED',
        maintenanceCorrelation: 'Terkait keterlambatan jadwal servis filter solar dan injektor (Work Order WO-2026-089).',
      },
      {
        id: 'fanom-04',
        vehicleId: 'veh-001',
        plateNumber: 'B 9876 XYZ',
        driverId: 'drv-01',
        driverName: 'Ahmad Sudrajat',
        timestamp: '2026-08-11T16:05:00Z',
        anomalyType: 'FUEL_SENSOR_SPIKE',
        anomalyScore: 42,
        severity: 'INFO',
        fuelLevelBefore: 55,
        fuelLevelAfter: 72,
        fuelDifferenceLiters: 51.0,
        fuelDifferencePercentage: 17.0,
        durationMinutes: 2,
        distanceTravelledKm: 1.5,
        ignitionStatus: true,
        speedKmH: 68,
        latitude: -6.3102,
        longitude: 107.2891,
        locationName: 'Tol Jakarta-Cikampek KM 42',
        insideGeofence: false,
        evidenceQuality: 'HIGH',
        evidenceDescription: 'Fluktuasi sensor sesaat akibat guncangan jalan tidak rata; level kembali normal setelah 90 detik.',
        status: 'RESOLVED',
        investigationNotes: 'Sensor noise terverifikasi otomatis oleh filter Kalman telemetri.',
      },
    ];
  }

  /**
   * Evaluates Potential Fuel Theft Indicators with multi-source evidence
   */
  public getTheftIndicators(): FuelTheftIndicator[] {
    return [
      {
        id: 'thft-01',
        vehicleId: 'veh-001',
        plateNumber: 'B 9876 XYZ',
        driverId: 'drv-01',
        driverName: 'Ahmad Sudrajat',
        timestamp: '2026-08-15T02:14:00Z',
        riskLevel: 'HIGH',
        detectionStrengthScore: 87, // Calibrated multi-source rule strength
        fuelDropLiters: 84.0,
        fuelDropPercentage: 28.0,
        ignitionOffConfirmed: true,
        vehicleStationaryConfirmed: true,
        distanceDuringDropKm: 0.2,
        outsideAuthorizedGeofence: true,
        noMatchingTransaction: true,
        latitude: -6.2942,
        longitude: 107.1645,
        locationName: 'Kawasan Pergudangan Liar Cibitung',
        evidenceList: [
          'Penurunan volume BBM signifikan sebesar 84.0 Liter (28% kapasitas tangki)',
          'Status kendaraan: Mesin MATI (Ignition OFF) dan diam (Speed 0 km/h) selama 12 menit',
          'Jarak tempuh selama periode penurunan hanya 200 meter (stasioner)',
          'Lokasi kejadian berada di luar seluruh zona geofence resmi/SPBU terdaftar',
          'Tidak terdapat catatan transaksi pengeluaran BBM atau struk klaim pada sistem',
          'Status sensor: Probe Ultrasonic Tangki Primer terkalibrasi normal tanpa noise',
        ],
        status: 'NEW',
        disclaimer: 'Indikator analitik berbasis telemetri GPS dan sensor tangki. Memerlukan investigasi fisik dan klarifikasi pengemudi sebelum tindakan administratif.',
      },
      {
        id: 'thft-02',
        vehicleId: 'veh-003',
        plateNumber: 'B 9555 TTT',
        driverId: 'drv-03',
        driverName: 'Eko Prasetyo',
        timestamp: '2026-08-10T23:45:00Z',
        riskLevel: 'MEDIUM',
        detectionStrengthScore: 68,
        fuelDropLiters: 38.0,
        fuelDropPercentage: 19.0,
        ignitionOffConfirmed: true,
        vehicleStationaryConfirmed: true,
        distanceDuringDropKm: 0.0,
        outsideAuthorizedGeofence: true,
        noMatchingTransaction: true,
        latitude: -6.3421,
        longitude: 107.2104,
        locationName: 'Pangkalan Truk Karawang Timur',
        evidenceList: [
          'Penurunan 38.0 Liter BBM Solar saat istirahat malam hari',
          'Ignition OFF & Speed 0 km/h selama durasi 35 menit',
          'Lokasi berada di luar depo/SPBU resmi',
        ],
        status: 'UNDER_REVIEW',
        reviewedBy: 'Staff Audit Operasional',
        reviewedAt: '2026-08-11T09:00:00Z',
        operatorNotes: 'Meminta rekaman dashcam dan klarifikasi dari pengemudi.',
        disclaimer: 'Indikator analitik berbasis telemetri sistem.',
      },
    ];
  }

  /**
   * Evaluates Fuel Drain and Leak Events (correlated with maintenance/sensor health)
   */
  public getDrainEvents(): FuelDrainItem[] {
    return [
      {
        id: 'drn-01',
        vehicleId: 'veh-001',
        plateNumber: 'B 9876 XYZ',
        driverName: 'Ahmad Sudrajat',
        timestamp: '2026-08-15T02:14:00Z',
        fuelLostLiters: 84.0,
        dropRateLitersPerHour: 420.0, // Fast drop rate
        ignitionState: false,
        speedKmH: 0,
        latitude: -6.2942,
        longitude: 107.1645,
        locationName: 'Cibitung Indah, Jawa Barat',
        possibleCauses: [
          'Penyedotan solar manual melalui keran tangki bawah (Indikasi Suspicious)',
          'Kebocoran parah pada selang bypass tangki cadangan',
        ],
        sensorHealthStatus: 'HEALTHY',
        status: 'NEW',
      },
      {
        id: 'drn-02',
        vehicleId: 'veh-006',
        plateNumber: 'B 9202 EF',
        driverName: 'Doni Firmansyah',
        timestamp: '2026-08-08T11:15:00Z',
        fuelLostLiters: 22.5,
        dropRateLitersPerHour: 15.0, // Slow continuous drop rate
        ignitionState: true,
        speedKmH: 45,
        latitude: -6.8912,
        longitude: 107.6102,
        locationName: 'Jalan Raya Padalarang',
        possibleCauses: [
          'Kebocoran seal injektor solar (Fuel Line Leak)',
          'Klem selang solar tangki sekunder longgar',
        ],
        maintenanceAlertLinked: 'WO-2026-074 (Perbaikan Selang Return Bahan Bakar)',
        sensorHealthStatus: 'HEALTHY',
        status: 'RESOLVED',
      },
    ];
  }

  /**
   * Refueling Audit & Station Reconciliation Logs
   */
  public getRefuelingAudits(): RefuelingAuditItem[] {
    return [
      {
        id: 'rf-01',
        vehicleId: 'veh-001',
        plateNumber: 'B 9876 XYZ',
        driverId: 'drv-01',
        driverName: 'Ahmad Sudrajat',
        timestamp: '2026-08-14T09:30:00Z',
        fuelType: 'BIODIESEL',
        sensorIncreaseLiters: 198.0,
        transactionVolumeLiters: 200.0,
        differenceLiters: -2.0,
        differencePercentage: -1.0,
        reconciliationResult: 'CONSISTENT',
        pricePerLiterIdr: 6800,
        totalCostIdr: 1360000,
        stationName: 'SPBU Pertamina 31.10201 Cikarang Utama',
        stationAuthorized: true,
        geofenceMatch: true,
        latitude: -6.2842,
        longitude: 107.1702,
        receiptNumber: 'RCP-2026-0814-01',
        status: 'VERIFIED',
        aiObservation: 'Pengisian bahan bakar konsisten dengan perubahan level sensor tangki (toleransi selisih 1.0% normal).',
      },
      {
        id: 'rf-02',
        vehicleId: 'veh-003',
        plateNumber: 'B 9555 TTT',
        driverId: 'drv-03',
        driverName: 'Eko Prasetyo',
        timestamp: '2026-08-14T21:40:00Z',
        fuelType: 'SOLAR',
        sensorIncreaseLiters: 70.0,
        transactionVolumeLiters: 120.0,
        differenceLiters: -50.0,
        differencePercentage: -41.7,
        reconciliationResult: 'MISMATCH_DETECTED',
        pricePerLiterIdr: 6800,
        totalCostIdr: 816000,
        stationName: 'SPBU Pertamina Rest Area KM 102 Tol Cipali',
        stationAuthorized: true,
        geofenceMatch: true,
        latitude: -6.5312,
        longitude: 107.8211,
        receiptNumber: 'RCP-2026-0814-99',
        status: 'FLAGGED',
        aiObservation: 'Terdeteksi diskrepansi volume transaksi 120 Liter vs kenaikan level sensor 70 Liter (-50 Liter mismatch). Memerlukan verifikasi struk fisik.',
      },
      {
        id: 'rf-03',
        vehicleId: 'veh-002',
        plateNumber: 'B 9123 KLR',
        driverId: 'drv-02',
        driverName: 'Budi Santoso',
        timestamp: '2026-08-13T16:10:00Z',
        fuelType: 'BIODIESEL',
        sensorIncreaseLiters: 148.5,
        transactionVolumeLiters: 150.0,
        differenceLiters: -1.5,
        differencePercentage: -1.0,
        reconciliationResult: 'CONSISTENT',
        pricePerLiterIdr: 6800,
        totalCostIdr: 1020000,
        stationName: 'SPBU Pertamina 31.10201 Cikarang Utama',
        stationAuthorized: true,
        geofenceMatch: true,
        latitude: -6.2842,
        longitude: 107.1702,
        receiptNumber: 'RCP-2026-0813-44',
        status: 'VERIFIED',
        aiObservation: 'Pengisian bahan bakar tervalidasi di SPBU terdaftar dengan kecocokan volume 99%.',
      },
      {
        id: 'rf-04',
        vehicleId: 'veh-004',
        plateNumber: 'B 9345 AB',
        driverId: 'drv-04',
        driverName: 'Faisal Akbar',
        timestamp: '2026-08-12T10:20:00Z',
        fuelType: 'SOLAR',
        sensorIncreaseLiters: 80.0,
        transactionVolumeLiters: 80.0,
        differenceLiters: 0.0,
        differencePercentage: 0.0,
        reconciliationResult: 'UNREGISTERED_STATION',
        pricePerLiterIdr: 14200, // Non-subsidized Shell price
        totalCostIdr: 1136000,
        stationName: 'SPBU Shell Express Batang KM 375 (Luar SPBU Rekanan)',
        stationAuthorized: false,
        geofenceMatch: false,
        latitude: -6.9082,
        longitude: 109.7302,
        receiptNumber: 'SHL-99812',
        status: 'FLAGGED',
        aiObservation: 'Pengisian dilakukan di SPBU non-rekanan dengan harga per liter lebih tinggi (Rp 14.200/L vs standar Rp 6.800/L).',
      },
    ];
  }
}

export const fuelAnomalyEngine = new FuelAnomalyEngine();
