/**
 * Fleet Intelligence Smart AI - Driver Management Mock Dataset
 * Realistic Indonesian Drivers, SIM Licenses, Vehicle Assignments, Shifts, Training, & AI Intelligence
 */

import {
  DriverExtended,
  DriverLicense,
  DriverAssignment,
  ShiftMaster,
  DriverShift,
  DriverDocument,
  DriverTraining,
  DriverSafetyEvent,
  DriverAIIntelligence,
  DriverActivityLog,
} from '../types/driver';

export const mockDriverLicenses: DriverLicense[] = [
  {
    licenseId: 'lic-001',
    driverId: 'drv-01',
    licenseNumber: '9203182390123',
    licenseType: 'SIM B2 Umum',
    issuingAuthority: 'Polda Metro Jaya',
    issuedDate: '2023-11-20',
    expiryDate: '2028-11-20',
    status: 'valid',
    verifiedAt: '2025-01-10T09:00:00Z',
    verifiedBy: 'HR Verification Bot',
    createdAt: '2025-01-10T09:00:00Z',
  },
  {
    licenseId: 'lic-002',
    driverId: 'drv-02',
    licenseNumber: '9203182390456',
    licenseType: 'SIM B2 Umum',
    issuingAuthority: 'Polda Jawa Barat',
    issuedDate: '2022-05-14',
    expiryDate: '2027-05-14',
    status: 'valid',
    verifiedAt: '2025-01-12T10:30:00Z',
    verifiedBy: 'HR Officer',
    createdAt: '2025-01-12T10:30:00Z',
  },
  {
    licenseId: 'lic-003',
    driverId: 'drv-03',
    licenseNumber: '9203182390789',
    licenseType: 'SIM B1 Umum',
    issuingAuthority: 'Polda Jawa Timur',
    issuedDate: '2021-09-10',
    expiryDate: '2026-09-10',
    status: 'expiring_soon',
    verifiedAt: '2025-01-15T08:15:00Z',
    verifiedBy: 'Fleet Safety Manager',
    createdAt: '2025-01-15T08:15:00Z',
  },
  {
    licenseId: 'lic-004',
    driverId: 'drv-04',
    licenseNumber: '9203182390111',
    licenseType: 'SIM B1',
    issuingAuthority: 'Polda Metro Jaya',
    issuedDate: '2020-02-15',
    expiryDate: '2025-02-15',
    status: 'expired',
    verifiedAt: '2025-02-16T00:00:00Z',
    verifiedBy: 'System Compliance Checker',
    createdAt: '2025-01-20T11:00:00Z',
  },
  {
    licenseId: 'lic-005',
    driverId: 'drv-05',
    licenseNumber: '9203182390222',
    licenseType: 'SIM B2 Umum',
    issuingAuthority: 'Polda Sulawesi Selatan',
    issuedDate: '2024-03-01',
    expiryDate: '2029-03-01',
    status: 'valid',
    verifiedAt: '2025-02-01T14:20:00Z',
    verifiedBy: 'HR Verification Bot',
    createdAt: '2025-02-01T14:20:00Z',
  },
  {
    licenseId: 'lic-006',
    driverId: 'drv-06',
    licenseNumber: '9203182390333',
    licenseType: 'SIM A Umum',
    issuingAuthority: 'Polda Metro Jaya',
    issuedDate: '2023-06-18',
    expiryDate: '2028-06-18',
    status: 'valid',
    verifiedAt: '2025-02-05T09:45:00Z',
    verifiedBy: 'HR Officer',
    createdAt: '2025-02-05T09:45:00Z',
  },
];

export const mockDriversExtended: DriverExtended[] = [
  {
    id: 'drv-01',
    driverId: 'drv-01',
    tenantId: 'tenant-tln-01',
    employeeId: 'EMP-2022-0104',
    driverCode: 'DRV-000001',
    fullName: 'Sutrisno Hartono',
    displayName: 'Pak Sutrisno',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    gender: 'male',
    dateOfBirth: '1985-03-12',
    phone: '+62 813 1122 3344',
    email: 'sutrisno.hartono@translogistik.co.id',
    address: 'Jl. Merdeka No. 45, Duren Sawit, Jakarta Timur, DKI Jakarta',
    branchId: 'br-jkt',
    branchName: 'HQ & Depo Jakarta (Tanjung Priok)',
    departmentId: 'dept-logistics',
    departmentName: 'Divisi Trans-Jawa Long Haul',
    position: 'Senior Heavy Truck Driver',
    status: 'active',
    availabilityStatus: 'on_trip',
    employmentType: 'permanent',
    joinDate: '2022-04-15',
    emergencyContact: {
      name: 'Dewi Ratnasari',
      relationship: 'Istri',
      phone: '+62 813 9988 7766',
      address: 'Jl. Merdeka No. 45, Jakarta Timur',
    },
    currentVehicleId: 'veh-01',
    currentVehiclePlate: 'B 9821 UTX',
    currentVehicleName: 'Isuzu Giga FVR 34 P (Box Trailer)',
    currentGpsDeviceId: 'dev-01',
    currentGpsStatus: 'online',
    currentShiftId: 'shift-01',
    currentShiftName: 'Shift Pagi (06:00 - 14:00)',
    currentTripId: 'trp-101',
    currentTripNumber: 'TRP-20260813-001',
    licenses: [mockDriverLicenses[0]],
    primaryLicenseNumber: '9203182390123',
    primaryLicenseType: 'SIM B2 Umum',
    primaryLicenseExpiry: '2028-11-20',
    licenseStatus: 'valid',
    safetyScore: 94,
    totalTripsCompleted: 142,
    totalDistanceKm: 14850,
    totalDriveTimeMinutes: 24000,
    speedingEventsCount: 1,
    harshBrakingCount: 0,
    harshAccelCount: 1,
    idleExcessMinutes: 12,
    notes: 'Driver teladan cabang Jakarta. Sertifikasi Defensif Heavy Vehicle 2025.',
    createdAt: '2022-04-15T08:00:00Z',
    updatedAt: '2026-08-13T08:30:00Z',
  },
  {
    id: 'drv-02',
    driverId: 'drv-02',
    tenantId: 'tenant-tln-01',
    employeeId: 'EMP-2023-0215',
    driverCode: 'DRV-000002',
    fullName: 'Ahmad Dahlan',
    displayName: 'Ahmad Dahlan',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    gender: 'male',
    dateOfBirth: '1982-08-15',
    phone: '+62 813 2233 4455',
    email: 'ahmad.dahlan@translogistik.co.id',
    address: 'Jl. Industri Utama No. 12, Cikarang Selatan, Kabupaten Bekasi',
    branchId: 'br-ckr',
    branchName: 'Hub Logistik Cikarang Dry Port',
    departmentId: 'dept-logistics',
    departmentName: 'Divisi Jabodetabek Distribution',
    position: 'Container Truck Driver',
    status: 'active',
    availabilityStatus: 'on_trip',
    employmentType: 'permanent',
    joinDate: '2023-01-10',
    emergencyContact: {
      name: 'Siti Aminah',
      relationship: 'Istri',
      phone: '+62 812 7766 5544',
    },
    currentVehicleId: 'veh-02',
    currentVehiclePlate: 'B 9410 UYY',
    currentVehicleName: 'Hino Ranger FL 235 JW',
    currentGpsDeviceId: 'dev-02',
    currentGpsStatus: 'online',
    currentShiftId: 'shift-01',
    currentShiftName: 'Shift Pagi (06:00 - 14:00)',
    currentTripId: 'trp-102',
    currentTripNumber: 'TRP-20260813-002',
    licenses: [mockDriverLicenses[1]],
    primaryLicenseNumber: '9203182390456',
    primaryLicenseType: 'SIM B2 Umum',
    primaryLicenseExpiry: '2027-05-14',
    licenseStatus: 'valid',
    safetyScore: 82,
    totalTripsCompleted: 118,
    totalDistanceKm: 12300,
    totalDriveTimeMinutes: 21500,
    speedingEventsCount: 4,
    harshBrakingCount: 3,
    harshAccelCount: 2,
    idleExcessMinutes: 45,
    notes: 'Perlu bimbingan terkait efisiensi BBM dan pengurangan waktu idle berlebih.',
    createdAt: '2023-01-10T08:00:00Z',
    updatedAt: '2026-08-13T08:29:55Z',
  },
  {
    id: 'drv-03',
    driverId: 'drv-03',
    tenantId: 'tenant-tln-01',
    employeeId: 'EMP-2023-0309',
    driverCode: 'DRV-000003',
    fullName: 'Cahyo Widodo',
    displayName: 'Pak Cahyo',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    gender: 'male',
    dateOfBirth: '1988-11-03',
    phone: '+62 813 3344 5566',
    email: 'cahyo.widodo@translogistik.co.id',
    address: 'Jl. Rungkut Industri No. 8, Surabaya, Jawa Timur',
    branchId: 'br-sby',
    branchName: 'Depo Surabaya (Tanjung Perak)',
    departmentId: 'dept-cargo',
    departmentName: 'Divisi Jawa Timur Feeder',
    position: 'Medium Cargo Driver',
    status: 'active',
    availabilityStatus: 'assigned',
    employmentType: 'contract',
    joinDate: '2023-06-01',
    emergencyContact: {
      name: 'Rina Widodo',
      relationship: 'Istri',
      phone: '+62 811 3322 1100',
    },
    currentVehicleId: 'veh-03',
    currentVehiclePlate: 'L 8122 UZ',
    currentVehicleName: 'Mitsubishi Fuso Canter FE 74 HD',
    currentGpsDeviceId: 'dev-03',
    currentGpsStatus: 'online',
    currentShiftId: 'shift-02',
    currentShiftName: 'Shift Sore (14:00 - 22:00)',
    licenses: [mockDriverLicenses[2]],
    primaryLicenseNumber: '9203182390789',
    primaryLicenseType: 'SIM B1 Umum',
    primaryLicenseExpiry: '2026-09-10',
    licenseStatus: 'expiring_soon',
    safetyScore: 96,
    totalTripsCompleted: 98,
    totalDistanceKm: 10500,
    totalDriveTimeMinutes: 18200,
    speedingEventsCount: 0,
    harshBrakingCount: 0,
    harshAccelCount: 0,
    idleExcessMinutes: 8,
    notes: 'SIM B1 Umum akan habis berlaku dalam kurun waktu kurang dari 30 hari. Telah diberikan notifikasi pembaruan.',
    createdAt: '2023-06-01T08:00:00Z',
    updatedAt: '2026-08-13T08:28:40Z',
  },
  {
    id: 'drv-04',
    driverId: 'drv-04',
    tenantId: 'tenant-tln-01',
    employeeId: 'EMP-2024-0412',
    driverCode: 'DRV-000004',
    fullName: 'Dedi Prasetyo',
    displayName: 'Dedi Prasetyo',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    gender: 'male',
    dateOfBirth: '1990-05-22',
    phone: '+62 813 4455 6677',
    email: 'dedi.prasetyo@translogistik.co.id',
    address: 'Jl. Raya Cilincing No. 89, Jakarta Utara',
    branchId: 'br-jkt',
    branchName: 'HQ & Depo Jakarta (Tanjung Priok)',
    departmentId: 'dept-logistics',
    departmentName: 'Divisi Jabodetabek Distribution',
    position: 'Light Truck & Van Driver',
    status: 'suspended',
    availabilityStatus: 'unavailable',
    employmentType: 'contract',
    joinDate: '2024-02-10',
    emergencyContact: {
      name: 'Bambang Prasetyo',
      relationship: 'Kakak',
      phone: '+62 815 6677 8899',
    },
    licenses: [mockDriverLicenses[3]],
    primaryLicenseNumber: '9203182390111',
    primaryLicenseType: 'SIM B1',
    primaryLicenseExpiry: '2025-02-15',
    licenseStatus: 'expired',
    safetyScore: 68,
    totalTripsCompleted: 45,
    totalDistanceKm: 5200,
    totalDriveTimeMinutes: 9100,
    speedingEventsCount: 8,
    harshBrakingCount: 6,
    harshAccelCount: 4,
    idleExcessMinutes: 120,
    notes: 'Status dinonaktifkan sementara karena SIM B1 telah kedaluwarsa dan terjadi pelanggaran prosedur pengemudian.',
    createdAt: '2024-02-10T08:00:00Z',
    updatedAt: '2026-08-13T08:00:00Z',
  },
  {
    id: 'drv-05',
    driverId: 'drv-05',
    tenantId: 'tenant-tln-01',
    employeeId: 'EMP-2024-0501',
    driverCode: 'DRV-000005',
    fullName: 'Eko Kurniawan',
    displayName: 'Pak Eko',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    gender: 'male',
    dateOfBirth: '1984-12-19',
    phone: '+62 813 5566 7788',
    email: 'eko.kurniawan@translogistik.co.id',
    address: 'Jl. Pelabuhan Hatta No. 102, Makassar, Sulawesi Selatan',
    branchId: 'br-mkn',
    branchName: 'Cabang Makassar (Soekarno-Hatta Port)',
    departmentId: 'dept-cargo',
    departmentName: 'Divisi Sulawesi Intercity',
    position: 'Heavy Haulage Driver',
    status: 'active',
    availabilityStatus: 'available',
    employmentType: 'permanent',
    joinDate: '2024-03-01',
    emergencyContact: {
      name: 'Maria Kurniawan',
      relationship: 'Istri',
      phone: '+62 812 8899 0011',
    },
    licenses: [mockDriverLicenses[4]],
    primaryLicenseNumber: '9203182390222',
    primaryLicenseType: 'SIM B2 Umum',
    primaryLicenseExpiry: '2029-03-01',
    licenseStatus: 'valid',
    safetyScore: 91,
    totalTripsCompleted: 62,
    totalDistanceKm: 8900,
    totalDriveTimeMinutes: 14500,
    speedingEventsCount: 2,
    harshBrakingCount: 1,
    harshAccelCount: 0,
    idleExcessMinutes: 15,
    notes: 'Pengemudi siap ditugaskan (available) di Makassar Depo.',
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2026-08-13T08:15:00Z',
  },
  {
    id: 'drv-06',
    driverId: 'drv-06',
    tenantId: 'tenant-tln-01',
    employeeId: 'EMP-2025-0610',
    driverCode: 'DRV-000006',
    fullName: 'Faisal Basri',
    displayName: 'Faisal Basri',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    gender: 'male',
    dateOfBirth: '1992-07-04',
    phone: '+62 813 6677 8899',
    email: 'faisal.basri@translogistik.co.id',
    address: 'Jl. Kalimalang No. 23, Bekasi, Jawa Barat',
    branchId: 'br-ckr',
    branchName: 'Hub Logistik Cikarang Dry Port',
    departmentId: 'dept-distribution',
    departmentName: 'Express Fleet Operations',
    position: 'Delivery Fleet Driver',
    status: 'active',
    availabilityStatus: 'off_duty',
    employmentType: 'contract',
    joinDate: '2025-01-15',
    emergencyContact: {
      name: 'Nurbaya Basri',
      relationship: 'Ibu',
      phone: '+62 813 0011 2233',
    },
    licenses: [mockDriverLicenses[5]],
    primaryLicenseNumber: '9203182390333',
    primaryLicenseType: 'SIM A Umum',
    primaryLicenseExpiry: '2028-06-18',
    licenseStatus: 'valid',
    safetyScore: 89,
    totalTripsCompleted: 34,
    totalDistanceKm: 3400,
    totalDriveTimeMinutes: 5800,
    speedingEventsCount: 1,
    harshBrakingCount: 1,
    harshAccelCount: 1,
    idleExcessMinutes: 20,
    notes: 'Pengemudi armada Van & Pickup Cikarang Hub. Off duty sesuai rotasi.',
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2026-08-13T07:45:00Z',
  },
];

export const mockDriverAssignments: DriverAssignment[] = [
  {
    assignmentId: 'asgn-001',
    tenantId: 'tenant-tln-01',
    driverId: 'drv-01',
    driverName: 'Sutrisno Hartono',
    vehicleId: 'veh-01',
    vehiclePlate: 'B 9821 UTX',
    vehicleName: 'Isuzu Giga FVR 34 P (Box Trailer)',
    gpsDeviceId: 'dev-01',
    gpsStatus: 'online',
    startAt: '2026-08-01T06:00:00Z',
    assignmentType: 'primary',
    status: 'active',
    assignedBy: 'Hendrikus Setiawan (Fleet Manager)',
    reason: 'Penugasan rutin armada Long Haul Trans-Jawa',
    createdAt: '2026-08-01T06:00:00Z',
  },
  {
    assignmentId: 'asgn-002',
    tenantId: 'tenant-tln-01',
    driverId: 'drv-02',
    driverName: 'Ahmad Dahlan',
    vehicleId: 'veh-02',
    vehiclePlate: 'B 9410 UYY',
    vehicleName: 'Hino Ranger FL 235 JW',
    gpsDeviceId: 'dev-02',
    gpsStatus: 'online',
    startAt: '2026-08-05T06:00:00Z',
    assignmentType: 'primary',
    status: 'active',
    assignedBy: 'Rudi Hermawan (Hub Manager Cikarang)',
    reason: 'Rute rutin Jabodetabek Container Distribution',
    createdAt: '2026-08-05T06:00:00Z',
  },
  {
    assignmentId: 'asgn-003',
    tenantId: 'tenant-tln-01',
    driverId: 'drv-03',
    driverName: 'Cahyo Widodo',
    vehicleId: 'veh-03',
    vehiclePlate: 'L 8122 UZ',
    vehicleName: 'Mitsubishi Fuso Canter FE 74 HD',
    gpsDeviceId: 'dev-03',
    gpsStatus: 'online',
    startAt: '2026-08-10T14:00:00Z',
    assignmentType: 'primary',
    status: 'active',
    assignedBy: 'Agus Wijaya (Depo Manager Surabaya)',
    reason: 'Rute Feeder Gresik-Sidoarjo',
    createdAt: '2026-08-10T14:00:00Z',
  },
  {
    assignmentId: 'asgn-004',
    tenantId: 'tenant-tln-01',
    driverId: 'drv-04',
    driverName: 'Dedi Prasetyo',
    vehicleId: 'veh-04',
    vehiclePlate: 'B 9011 KIX',
    vehicleName: 'Hino Dutro 130 HD',
    gpsDeviceId: 'dev-04',
    gpsStatus: 'offline',
    startAt: '2026-07-01T06:00:00Z',
    endAt: '2026-08-01T18:00:00Z',
    assignmentType: 'temporary',
    status: 'completed',
    assignedBy: 'Hendrikus Setiawan',
    reason: 'Penugasan sementara peremajaan unit',
    createdAt: '2026-07-01T06:00:00Z',
  },
];

export const mockShiftMasters: ShiftMaster[] = [
  {
    id: 'shift-m-01',
    tenantId: 'tenant-tln-01',
    name: 'Shift Pagi (Morning Duty)',
    startTime: '06:00',
    endTime: '14:00',
    breakMinutes: 60,
    timezone: 'Asia/Jakarta',
    status: 'active',
  },
  {
    id: 'shift-m-02',
    tenantId: 'tenant-tln-01',
    name: 'Shift Sore (Afternoon Duty)',
    startTime: '14:00',
    endTime: '22:00',
    breakMinutes: 60,
    timezone: 'Asia/Jakarta',
    status: 'active',
  },
  {
    id: 'shift-m-03',
    tenantId: 'tenant-tln-01',
    name: 'Shift Malam (Night Haul)',
    startTime: '22:00',
    endTime: '06:00',
    breakMinutes: 60,
    timezone: 'Asia/Jakarta',
    status: 'active',
  },
];

export const mockDriverShifts: DriverShift[] = [
  {
    driverShiftId: 'ds-101',
    tenantId: 'tenant-tln-01',
    driverId: 'drv-01',
    driverName: 'Sutrisno Hartono',
    shiftId: 'shift-m-01',
    shiftName: 'Shift Pagi (06:00 - 14:00)',
    date: '2026-08-13',
    startAt: '2026-08-13T06:00:00Z',
    endAt: '2026-08-13T14:00:00Z',
    status: 'active',
    assignedBy: 'Dispatcher Jakarta',
    notes: 'On trip TRP-20260813-001',
  },
  {
    driverShiftId: 'ds-102',
    tenantId: 'tenant-tln-01',
    driverId: 'drv-02',
    driverName: 'Ahmad Dahlan',
    shiftId: 'shift-m-01',
    shiftName: 'Shift Pagi (06:00 - 14:00)',
    date: '2026-08-13',
    startAt: '2026-08-13T06:00:00Z',
    endAt: '2026-08-13T14:00:00Z',
    status: 'active',
    assignedBy: 'Dispatcher Cikarang',
    notes: 'On trip TRP-20260813-002',
  },
  {
    driverShiftId: 'ds-103',
    tenantId: 'tenant-tln-01',
    driverId: 'drv-03',
    driverName: 'Cahyo Widodo',
    shiftId: 'shift-m-02',
    shiftName: 'Shift Sore (14:00 - 22:00)',
    date: '2026-08-13',
    startAt: '2026-08-13T14:00:00Z',
    endAt: '2026-08-13T22:00:00Z',
    status: 'scheduled',
    assignedBy: 'Dispatcher Surabaya',
    notes: 'Ready for check-in at 13:45 WIB',
  },
  {
    driverShiftId: 'ds-104',
    tenantId: 'tenant-tln-01',
    driverId: 'drv-05',
    driverName: 'Eko Kurniawan',
    shiftId: 'shift-m-01',
    shiftName: 'Shift Pagi (06:00 - 14:00)',
    date: '2026-08-13',
    startAt: '2026-08-13T06:00:00Z',
    endAt: '2026-08-13T14:00:00Z',
    status: 'completed',
    assignedBy: 'Dispatcher Makassar',
    notes: 'Shift completed cleanly',
  },
];

export const mockDriverDocuments: DriverDocument[] = [
  {
    id: 'doc-01',
    driverId: 'drv-01',
    tenantId: 'tenant-tln-01',
    type: 'sim',
    title: 'SIM B2 Umum (Surat Izin Mengemudi)',
    documentNumber: '9203182390123',
    issueDate: '2023-11-20',
    expiryDate: '2028-11-20',
    status: 'verified',
    documentUrl: 'https://placehold.co/600x400/10b981/ffffff?text=SIM+B2+Umum+Sutrisno',
    notes: 'Diperiksa oleh Tim HR Compliance & Polda Metro Jaya',
    createdAt: '2025-01-10T09:00:00Z',
  },
  {
    id: 'doc-02',
    driverId: 'drv-01',
    tenantId: 'tenant-tln-01',
    type: 'ktp',
    title: 'KTP Elektronik (NIK 3175081203850001)',
    documentNumber: '3175081203850001',
    status: 'verified',
    documentUrl: 'https://placehold.co/600x400/3b82f6/ffffff?text=eKTP+Sutrisno',
    createdAt: '2025-01-10T09:05:00Z',
  },
  {
    id: 'doc-03',
    driverId: 'drv-01',
    tenantId: 'tenant-tln-01',
    type: 'medical_clearance',
    title: 'Surat Keterangan Sehat & Bebas Narkoba (MCU)',
    documentNumber: 'MCU-2025-0811',
    issueDate: '2025-01-15',
    expiryDate: '2026-01-15',
    status: 'verified',
    notes: 'Hasil MCU: Fit for Heavy Vehicle Operations',
    createdAt: '2025-01-15T11:00:00Z',
  },
  {
    id: 'doc-04',
    driverId: 'drv-03',
    tenantId: 'tenant-tln-01',
    type: 'sim',
    title: 'SIM B1 Umum (Surat Izin Mengemudi)',
    documentNumber: '9203182390789',
    issueDate: '2021-09-10',
    expiryDate: '2026-09-10',
    status: 'verified',
    notes: 'Segera diperbarui sebelum masa berlaku berakhir (10 Sep 2026)',
    createdAt: '2025-01-15T08:15:00Z',
  },
  {
    id: 'doc-05',
    driverId: 'drv-04',
    tenantId: 'tenant-tln-01',
    type: 'sim',
    title: 'SIM B1 (Surat Izin Mengemudi - Kedaluwarsa)',
    documentNumber: '9203182390111',
    issueDate: '2020-02-15',
    expiryDate: '2025-02-15',
    status: 'expired',
    notes: 'Masa berlaku telah berakhir. Diperlukan perpanjangan SIM B1 sebelum penugasan.',
    createdAt: '2025-01-20T11:00:00Z',
  },
];

export const mockDriverTrainings: DriverTraining[] = [
  {
    id: 'tr-01',
    driverId: 'drv-01',
    tenantId: 'tenant-tln-01',
    trainingName: 'Defensive Driving & Heavy Vehicle Safety (Level 3)',
    category: 'defensive_driving',
    provider: 'Indonesian Safety Driving Center (ISDC)',
    date: '2025-02-10',
    expiryDate: '2027-02-10',
    status: 'completed',
    score: 95,
    certificateUrl: 'https://placehold.co/600x400/0284c7/ffffff?text=Cert+ISDC+Sutrisno',
    notes: 'Lulus dengan predikat Sangat Baik (Sertifikat berlaku 2 tahun)',
  },
  {
    id: 'tr-02',
    driverId: 'drv-01',
    tenantId: 'tenant-tln-01',
    trainingName: 'Eco-Driving & Fuel Savings Optimization',
    category: 'vehicle_operation',
    provider: 'Isuzu Internal Fleet Academy',
    date: '2024-09-15',
    status: 'completed',
    score: 92,
  },
  {
    id: 'tr-03',
    driverId: 'drv-02',
    tenantId: 'tenant-tln-01',
    trainingName: 'Handling Emergency Brakes & Fatigue Prevention',
    category: 'safety',
    provider: 'Hino Fleet Driving School',
    date: '2024-11-20',
    status: 'completed',
    score: 80,
    notes: 'Disarankan pengulangan modul pemantauan idle dan rem mendadak.',
  },
];

export const mockDriverSafetyEvents: DriverSafetyEvent[] = [
  {
    id: 'se-01',
    driverId: 'drv-01',
    vehicleId: 'veh-01',
    vehiclePlate: 'B 9821 UTX',
    timestamp: '2026-08-12T14:22:10Z',
    type: 'speeding',
    severity: 'warning',
    speedKmH: 88,
    speedLimitKmH: 80,
    location: {
      lat: -6.7211,
      lng: 108.552,
      address: 'Tol Cikopo - Palimanan (Cipali) KM 124',
    },
    details: 'Terdeteksi kecepatan 88 km/jam melebihi batas 80 km/jam selama 45 detik.',
  },
  {
    id: 'se-02',
    driverId: 'drv-02',
    vehicleId: 'veh-02',
    vehiclePlate: 'B 9410 UYY',
    timestamp: '2026-08-11T09:15:30Z',
    type: 'harsh_braking',
    severity: 'warning',
    speedKmH: 62,
    location: {
      lat: -6.2844,
      lng: 107.1706,
      address: 'Kawasan Industri Jababeka 1, Cikarang',
    },
    details: 'Pengereman mendadak deselerasi -0.45g.',
  },
  {
    id: 'se-03',
    driverId: 'drv-02',
    vehicleId: 'veh-02',
    vehiclePlate: 'B 9410 UYY',
    timestamp: '2026-08-11T11:40:00Z',
    type: 'excessive_idling',
    severity: 'info',
    location: {
      lat: -6.289,
      lng: 107.175,
      address: 'Area Parkir Rest Area Cibitung',
    },
    details: 'Mesin menyala diam (idling) selama 28 menit terus-menerus tanpa pergerakan.',
  },
];

export const mockDriverAIIntelligence: Record<string, DriverAIIntelligence> = {
  'drv-01': {
    driverId: 'drv-01',
    safetyScore: 94,
    overallRating: 'Excellent',
    drivingBehaviorSummary:
      'Sutrisno Hartono menunjukkan konsistensi berkendara yang sangat tinggi. Pola pengereman halus, disiplin terhadap batas kecepatan tol trans-Jawa, dan mempertahankan efisiensi BBM Isuzu Giga FVR di tingkat optimal.',
    positivePoints: [
      'Nir-pengereman mendadak (0 Harsh Brakes) selama 30 hari terakhir.',
      'Rata-rata kecepatan stabil pada koridor tol Cipali-Pejagan.',
      'Penghematan konsumsi bahan bakar 8.5% di atas standar armada.',
      'Sertifikat Defensive Driving aktif hingga Feb 2027.',
    ],
    attentionPoints: [
      '1x peringatan batas kecepatan ringan (88 km/jam) di Tol Cipali KM 124.',
      'Perhatikan akumulasi jam mengemudi sebelum rest area Palimanan untuk cegah kelelahan.',
    ],
    recommendations: [
      'Pertahankan gaya berkendara halus pada muatan penuh > 15 Ton.',
      'Direkomendasikan sebagai Instruktur Mentor bagi pengemudi baru armada heavy truck.',
    ],
    confidenceScore: 96,
    riskLevel: 'LOW',
    anomalies: [
      {
        id: 'anom-101',
        title: 'Lonjakan Kecepatan Singkat Cipali',
        description: 'Peningkatan kecepatan 80 -> 88 km/jam selama 45 detik saat mendahului di turunan Cipali.',
        impact: 'Beban emisi BBM naik 2.1% selama durasi kejadian.',
      },
    ],
    coaching: [
      {
        focusArea: 'Speed Management at Downhill Slopes',
        suggestion: 'Gunakan exhaust brake saat melintasi kontur jalan menurun di Tol Cipali untuk menjaga kecepatan di bawah 80 km/jam.',
        priority: 'low',
      },
    ],
  },
  'drv-02': {
    driverId: 'drv-02',
    safetyScore: 82,
    overallRating: 'Fair',
    drivingBehaviorSummary:
      'Ahmad Dahlan memiliki produktivitas jarak yang baik, namun AI mendeteksi kecenderungan pengereman mendadak dan idling berlebih di area kemacetan Cikarang-Jakarta.',
    positivePoints: [
      'Ketepatan waktu pengiriman barang (On-Time Delivery Rate 94%).',
      'Dokumen SIM B2 Umum & eKTP lengkap dan terverifikasi.',
    ],
    attentionPoints: [
      '3x kejadian Harsh Braking dalam minggu ini.',
      'Waktu idle mesin berlebih (45 menit akumulasi) menyerap ~1.8 Liter Solar sia-sia.',
    ],
    recommendations: [
      'Jadwalkan modul singkat Eco-Driving & Anti-Idling.',
      'Gunakan pemantauan jarak aman (safe distance spacing) di area industri padat.',
    ],
    confidenceScore: 91,
    riskLevel: 'MEDIUM',
    anomalies: [
      {
        id: 'anom-102',
        title: 'Waktu Idle Berlebih di Cikarang Rest Area',
        description: 'Mesin Hino Ranger menyala diam 28 menit dengan AC menyala saat menunggu giliran muat.',
        impact: 'Pemborosan BBM estimasi Rp 24.800 per kejadian.',
      },
    ],
    coaching: [
      {
        focusArea: 'Idle Reduction & Engine Shutdown',
        suggestion: 'Matikan mesin jika durasi antrean atau perhentian melebihi 5 menit.',
        priority: 'medium',
      },
      {
        focusArea: 'Smooth Braking Distance',
        suggestion: 'Jaga jarak aman minimal 40 meter saat mengemudikan truk Hino Ranger dengan muatan container.',
        priority: 'high',
      },
    ],
  },
};

export const mockDriverActivityLogs: DriverActivityLog[] = [
  {
    id: 'log-01',
    driverId: 'drv-01',
    tenantId: 'tenant-tln-01',
    timestamp: '2026-08-01T06:00:00Z',
    eventType: 'vehicle_assigned',
    title: 'Penugasan Kendaraan Aktif',
    description: 'Ditugaskan ke kendaraan B 9821 UTX (Isuzu Giga FVR 34 P) dengan GPS IMEI 864201049283011.',
    performedBy: 'Hendrikus Setiawan (Fleet Manager)',
  },
  {
    id: 'log-02',
    driverId: 'drv-01',
    tenantId: 'tenant-tln-01',
    timestamp: '2025-02-10T10:00:00Z',
    eventType: 'training_completed',
    title: 'Pelatihan Pelatihan Selesai',
    description: 'Menyelesaikan modul ISDC Defensive Driving Level 3 dengan skor 95/100.',
    performedBy: 'HR Training Department',
  },
  {
    id: 'log-03',
    driverId: 'drv-04',
    tenantId: 'tenant-tln-01',
    timestamp: '2026-08-01T00:00:00Z',
    eventType: 'status_changed',
    title: 'Perubahan Status Pengemudi',
    description: 'Status pengemudi diubah dari ACTIVE menjadi SUSPENDED karena SIM B1 kedaluwarsa.',
    performedBy: 'System Auto Compliance Engine',
  },
];

export const MOCK_DRIVERS = mockDriversExtended;
