import {
  TankerVehicle,
  TankerDeliveryOrder,
  TankerDriver,
  TankerCleaningLog
} from '../types';

export const MOCK_TANKER_FLEETS: TankerVehicle[] = [
  {
    id: 'tank-01',
    hullNumber: 'TANK-BBM-2401',
    plateNumber: 'B 9142 TFU',
    truckType: 'SEMITRAILER_TANKER',
    tankMaterial: 'ALUMINIUM_ALLOY_5182',
    totalCapacityLiters: 24000,
    numberOfCompartments: 3,
    dedicatedCargo: 'BBM_PERTALITE',
    currentStatus: 'EN_ROUTE_LOADED',
    driverName: 'Bambang Supriyanto',
    driverPhone: '0812-9844-1120',
    coDriverName: 'Hendra Setiawan',
    currentLocationName: 'Tol Jakarta-Cikampek KM 38 (Arah Karawang)',
    destinationName: 'SPBU 34.413.09 Karawang Timur',
    assignedDepot: 'TBBM Plumpang Jakarta',
    speedKmh: 62,
    maxCorridorSpeedKmh: 70,
    sloshLateralGForce: 0.14,
    isRolloverWarning: false,
    isRedZoneStopAlert: false,
    elockMasterStatus: 'LOCKED_SECURE',
    unauthorizedDrainAlert: false,
    teraMetrologiExpiry: '2026-11-15',
    hydrotestExpiry: '2027-04-20',
    kirExpiry: '2026-10-30',
    b3LicenseExpiry: '2027-01-10',
    fuelLevelPct: 82,
    loadedWeightTon: 28.4,
    grossVehicleWeightTon: 36.0,
    compartments: [
      {
        id: 'comp-01-1',
        compartmentNo: 1,
        capacityLiters: 8000,
        currentVolumeLiters: 7995,
        liquidType: 'BBM_PERTALITE',
        levelMm: 1840,
        ullageMm: 160,
        temperatureC: 30.2,
        densityKgM3: 742,
        waterBottomMm: 0,
        manholeStatus: 'CLOSED_LOCKED',
        dischargeValveStatus: 'CLOSED_LOCKED',
        bottomLoadingValveStatus: 'CLOSED'
      },
      {
        id: 'comp-01-2',
        compartmentNo: 2,
        capacityLiters: 8000,
        currentVolumeLiters: 8000,
        liquidType: 'BBM_PERTAMAX',
        levelMm: 1850,
        ullageMm: 150,
        temperatureC: 30.0,
        densityKgM3: 755,
        waterBottomMm: 0,
        manholeStatus: 'CLOSED_LOCKED',
        dischargeValveStatus: 'CLOSED_LOCKED',
        bottomLoadingValveStatus: 'CLOSED'
      },
      {
        id: 'comp-01-3',
        compartmentNo: 3,
        capacityLiters: 8000,
        currentVolumeLiters: 7990,
        liquidType: 'BBM_BIOSOLAR',
        levelMm: 1835,
        ullageMm: 165,
        temperatureC: 29.8,
        densityKgM3: 840,
        waterBottomMm: 0,
        manholeStatus: 'CLOSED_LOCKED',
        dischargeValveStatus: 'CLOSED_LOCKED',
        bottomLoadingValveStatus: 'CLOSED'
      }
    ]
  },
  {
    id: 'tank-02',
    hullNumber: 'CPO-TAN-3208',
    plateNumber: 'BK 8819 CP',
    truckType: 'SEMITRAILER_TANKER',
    tankMaterial: 'STAINLESS_STEEL_SS304',
    totalCapacityLiters: 32000,
    numberOfCompartments: 4,
    dedicatedCargo: 'CPO_CRUDE_PALM_OIL',
    currentStatus: 'EN_ROUTE_LOADED',
    driverName: 'Rudi Hartono',
    driverPhone: '0813-7721-9903',
    currentLocationName: 'Jl. Lintas Sumatera KM 145 (Kandis - Duri)',
    destinationName: 'Pelabuhan Bulking Dumai PT Sinar Mas',
    assignedDepot: 'PKS Mill Riau Mandiri',
    speedKmh: 48,
    maxCorridorSpeedKmh: 60,
    sloshLateralGForce: 0.18,
    isRolloverWarning: false,
    isRedZoneStopAlert: false,
    elockMasterStatus: 'LOCKED_SECURE',
    unauthorizedDrainAlert: false,
    teraMetrologiExpiry: '2027-02-18',
    hydrotestExpiry: '2027-08-14',
    kirExpiry: '2026-12-05',
    b3LicenseExpiry: '2027-06-20',
    fuelLevelPct: 74,
    loadedWeightTon: 34.8,
    grossVehicleWeightTon: 42.0,
    compartments: [
      {
        id: 'comp-02-1',
        compartmentNo: 1,
        capacityLiters: 8000,
        currentVolumeLiters: 8000,
        liquidType: 'CPO_CRUDE_PALM_OIL',
        levelMm: 1920,
        ullageMm: 120,
        temperatureC: 48.5,
        densityKgM3: 890,
        waterBottomMm: 0,
        manholeStatus: 'CLOSED_LOCKED',
        dischargeValveStatus: 'CLOSED_LOCKED',
        bottomLoadingValveStatus: 'CLOSED'
      },
      {
        id: 'comp-02-2',
        compartmentNo: 2,
        capacityLiters: 8000,
        currentVolumeLiters: 8000,
        liquidType: 'CPO_CRUDE_PALM_OIL',
        levelMm: 1920,
        ullageMm: 120,
        temperatureC: 48.2,
        densityKgM3: 890,
        waterBottomMm: 0,
        manholeStatus: 'CLOSED_LOCKED',
        dischargeValveStatus: 'CLOSED_LOCKED',
        bottomLoadingValveStatus: 'CLOSED'
      },
      {
        id: 'comp-02-3',
        compartmentNo: 3,
        capacityLiters: 8000,
        currentVolumeLiters: 7990,
        liquidType: 'CPO_CRUDE_PALM_OIL',
        levelMm: 1915,
        ullageMm: 125,
        temperatureC: 48.0,
        densityKgM3: 891,
        waterBottomMm: 0,
        manholeStatus: 'CLOSED_LOCKED',
        dischargeValveStatus: 'CLOSED_LOCKED',
        bottomLoadingValveStatus: 'CLOSED'
      },
      {
        id: 'comp-02-4',
        compartmentNo: 4,
        capacityLiters: 8000,
        currentVolumeLiters: 7995,
        liquidType: 'CPO_CRUDE_PALM_OIL',
        levelMm: 1918,
        ullageMm: 122,
        temperatureC: 47.9,
        densityKgM3: 890,
        waterBottomMm: 0,
        manholeStatus: 'CLOSED_LOCKED',
        dischargeValveStatus: 'CLOSED_LOCKED',
        bottomLoadingValveStatus: 'CLOSED'
      }
    ]
  },
  {
    id: 'tank-03',
    hullNumber: 'CHEM-ACID-1603',
    plateNumber: 'B 9031 UXZ',
    truckType: 'RIGID_TANKER',
    tankMaterial: 'STAINLESS_STEEL_SS316L',
    totalCapacityLiters: 16000,
    numberOfCompartments: 2,
    dedicatedCargo: 'CHEMICAL_ACID',
    currentStatus: 'UNLOADING_DISCHARGE',
    driverName: 'Suryadi Kusuma',
    driverPhone: '0811-3320-119',
    currentLocationName: 'Kawasan Industri Cilegon (PT Chandra Asri)',
    destinationName: 'Plant Petrokimia Cilegon',
    assignedDepot: 'Terminal Kimia Merak',
    speedKmh: 0,
    maxCorridorSpeedKmh: 60,
    sloshLateralGForce: 0.0,
    isRolloverWarning: false,
    isRedZoneStopAlert: false,
    elockMasterStatus: 'AUTHORIZED_UNLOCKED',
    unauthorizedDrainAlert: false,
    teraMetrologiExpiry: '2026-09-10',
    hydrotestExpiry: '2027-03-12',
    kirExpiry: '2026-11-20',
    b3LicenseExpiry: '2026-12-31',
    fuelLevelPct: 65,
    loadedWeightTon: 22.1,
    grossVehicleWeightTon: 26.0,
    compartments: [
      {
        id: 'comp-03-1',
        compartmentNo: 1,
        capacityLiters: 8000,
        currentVolumeLiters: 2400,
        liquidType: 'CHEMICAL_ACID',
        levelMm: 620,
        ullageMm: 1380,
        temperatureC: 28.0,
        densityKgM3: 1830, // H2SO4 heavy density
        waterBottomMm: 0,
        manholeStatus: 'CLOSED_LOCKED',
        dischargeValveStatus: 'OPEN_DISCHARGING',
        bottomLoadingValveStatus: 'CLOSED'
      },
      {
        id: 'comp-03-2',
        compartmentNo: 2,
        capacityLiters: 8000,
        currentVolumeLiters: 8000,
        liquidType: 'CHEMICAL_ACID',
        levelMm: 1860,
        ullageMm: 140,
        temperatureC: 28.1,
        densityKgM3: 1830,
        waterBottomMm: 0,
        manholeStatus: 'CLOSED_LOCKED',
        dischargeValveStatus: 'CLOSED_LOCKED',
        bottomLoadingValveStatus: 'CLOSED'
      }
    ]
  },
  {
    id: 'tank-04',
    hullNumber: 'LPG-SKID-1504',
    plateNumber: 'D 8991 AH',
    truckType: 'RIGID_TANKER',
    tankMaterial: 'CARBON_STEEL_Q235B',
    totalCapacityLiters: 15000,
    numberOfCompartments: 1,
    dedicatedCargo: 'LPG_BULK',
    currentStatus: 'LOADING_GANTRY',
    driverName: 'Agus Priyono',
    driverPhone: '0852-1109-8832',
    currentLocationName: 'Gantry Skid Tank SPPBE Padalarang',
    destinationName: 'SPPBE Sukabumi Mandiri',
    assignedDepot: 'Depot LPG Balongan / Padalarang',
    speedKmh: 0,
    maxCorridorSpeedKmh: 65,
    sloshLateralGForce: 0.0,
    isRolloverWarning: false,
    isRedZoneStopAlert: false,
    elockMasterStatus: 'AUTHORIZED_UNLOCKED',
    unauthorizedDrainAlert: false,
    teraMetrologiExpiry: '2026-10-05',
    hydrotestExpiry: '2027-05-18',
    kirExpiry: '2026-12-15',
    b3LicenseExpiry: '2027-02-28',
    fuelLevelPct: 90,
    loadedWeightTon: 18.2,
    grossVehicleWeightTon: 24.0,
    compartments: [
      {
        id: 'comp-04-1',
        compartmentNo: 1,
        capacityLiters: 15000,
        currentVolumeLiters: 12500,
        liquidType: 'LPG_BULK',
        levelMm: 1650,
        ullageMm: 350,
        temperatureC: 27.5,
        densityKgM3: 540, // LPG Liquid
        waterBottomMm: 0,
        manholeStatus: 'CLOSED_LOCKED',
        dischargeValveStatus: 'CLOSED_LOCKED',
        bottomLoadingValveStatus: 'CONNECTED_GANTRY'
      }
    ]
  },
  {
    id: 'tank-05',
    hullNumber: 'TANK-BBM-1605',
    plateNumber: 'B 9720 TFR',
    truckType: 'RIGID_TANKER',
    tankMaterial: 'ALUMINIUM_ALLOY_5182',
    totalCapacityLiters: 16000,
    numberOfCompartments: 2,
    dedicatedCargo: 'BBM_PERTALITE',
    currentStatus: 'CLEANING_PURGING',
    driverName: 'Denny Maulana',
    driverPhone: '0878-9901-2244',
    currentLocationName: 'Tank Cleaning Bay Pool Plumpang',
    destinationName: 'Pool Plumpang',
    assignedDepot: 'TBBM Plumpang Jakarta',
    speedKmh: 0,
    maxCorridorSpeedKmh: 70,
    sloshLateralGForce: 0.0,
    isRolloverWarning: false,
    isRedZoneStopAlert: false,
    elockMasterStatus: 'AUTHORIZED_UNLOCKED',
    unauthorizedDrainAlert: false,
    teraMetrologiExpiry: '2027-01-12',
    hydrotestExpiry: '2027-07-09',
    kirExpiry: '2027-01-15',
    b3LicenseExpiry: '2027-05-10',
    fuelLevelPct: 55,
    loadedWeightTon: 9.8, // Empty
    grossVehicleWeightTon: 26.0,
    compartments: [
      {
        id: 'comp-05-1',
        compartmentNo: 1,
        capacityLiters: 8000,
        currentVolumeLiters: 0,
        liquidType: 'BBM_PERTALITE',
        levelMm: 0,
        ullageMm: 2000,
        temperatureC: 32.0,
        densityKgM3: 0,
        waterBottomMm: 0,
        manholeStatus: 'OPEN_ALERT',
        dischargeValveStatus: 'CLOSED_LOCKED',
        bottomLoadingValveStatus: 'CLOSED'
      },
      {
        id: 'comp-05-2',
        compartmentNo: 2,
        capacityLiters: 8000,
        currentVolumeLiters: 0,
        liquidType: 'BBM_PERTALITE',
        levelMm: 0,
        ullageMm: 2000,
        temperatureC: 32.0,
        densityKgM3: 0,
        waterBottomMm: 0,
        manholeStatus: 'OPEN_ALERT',
        dischargeValveStatus: 'CLOSED_LOCKED',
        bottomLoadingValveStatus: 'CLOSED'
      }
    ]
  }
];

export const MOCK_DELIVERY_ORDERS: TankerDeliveryOrder[] = [
  {
    id: 'do-01',
    spbNumber: 'SPPB/BBM/PLP/2026/08/901',
    doNumber: 'DO-PERTAMINA-88129',
    consignor: 'Integrated Terminal Jakarta - Plumpang',
    consignee: 'SPBU 34.413.09 Karawang Timur',
    consigneeAddress: 'Jl. Raya Klari KM 7, Karawang, Jawa Barat',
    assignedTankerHull: 'TANK-BBM-2401',
    driverName: 'Bambang Supriyanto',
    productType: 'BBM_PERTALITE',
    orderedVolumeLiters: 24000,
    gantryLoadedGrossLiters: 24000,
    gantryLoadedNet15Liters: 23985,
    gantryLoadingTempC: 30.2,
    gantryDensity: 742,
    departureTime: '2026-08-21 07:30',
    estimatedArrivalTime: '2026-08-21 10:15',
    status: 'IN_TRANSIT',
    lossStatus: 'WITHIN_TOLERANCE',
    elockSecurityOtp: '891044',
    eSealBarcode: 'ES-PLP-992014-A'
  },
  {
    id: 'do-02',
    spbNumber: 'SPB/CPO/RIAU/2026/08/412',
    doNumber: 'DO-CPO-WILMAR-5521',
    consignor: 'PKS Mill PT Riau Agro Mandiri',
    consignee: 'PT Wilmar Nabati Indonesia - Dumai Bulking Terminal',
    consigneeAddress: 'Kawasan Industri Pelabuhan Dumai, Riau',
    assignedTankerHull: 'CPO-TAN-3208',
    driverName: 'Rudi Hartono',
    productType: 'CPO_CRUDE_PALM_OIL',
    orderedVolumeLiters: 32000,
    gantryLoadedGrossLiters: 32000,
    gantryLoadedNet15Liters: 31960,
    gantryLoadingTempC: 48.5,
    gantryDensity: 890,
    departureTime: '2026-08-21 05:45',
    estimatedArrivalTime: '2026-08-21 11:30',
    status: 'IN_TRANSIT',
    lossStatus: 'WITHIN_TOLERANCE',
    elockSecurityOtp: '334182',
    eSealBarcode: 'ES-CPO-77401-X'
  },
  {
    id: 'do-03',
    spbNumber: 'SPB/B3/MERAK/2026/08/119',
    doNumber: 'DO-ACID-CHANDRA-092',
    consignor: 'PT Sulfindo Adiusaha Merak',
    consignee: 'PT Chandra Asri Petrochemical Tbk',
    consigneeAddress: 'Jl. Raya Anyer KM 123, Ciwandan, Cilegon, Banten',
    assignedTankerHull: 'CHEM-ACID-1603',
    driverName: 'Suryadi Kusuma',
    productType: 'CHEMICAL_ACID',
    orderedVolumeLiters: 16000,
    gantryLoadedGrossLiters: 16000,
    gantryLoadedNet15Liters: 16000,
    gantryLoadingTempC: 28.0,
    gantryDensity: 1830,
    departureTime: '2026-08-21 08:00',
    estimatedArrivalTime: '2026-08-21 09:30',
    actualArrivalTime: '2026-08-21 09:25',
    unloadingStartTime: '2026-08-21 09:40',
    status: 'DISCHARGING',
    dischargedVolumeLiters: 5600,
    volumeLossLiters: 8,
    lossPercentage: 0.05,
    lossStatus: 'WITHIN_TOLERANCE',
    elockSecurityOtp: '502911',
    eSealBarcode: 'ES-MRK-1109-Z'
  },
  {
    id: 'do-04',
    spbNumber: 'SPB/LPG/BLG/2026/08/044',
    doNumber: 'DO-LPG-SKID-7729',
    consignor: 'Depot LPG Padalarang Pertamina Patra Niaga',
    consignee: 'SPPBE PT Sukabumi Gas Mandiri',
    consigneeAddress: 'Jl. Pelabuhan II KM 9, Cikembar, Sukabumi',
    assignedTankerHull: 'LPG-SKID-1504',
    driverName: 'Agus Priyono',
    productType: 'LPG_BULK',
    orderedVolumeLiters: 15000,
    gantryLoadedGrossLiters: 15000,
    gantryLoadedNet15Liters: 15000,
    gantryLoadingTempC: 27.5,
    gantryDensity: 540,
    departureTime: '2026-08-21 10:30',
    estimatedArrivalTime: '2026-08-21 14:00',
    status: 'LOADING',
    lossStatus: 'PENDING_UNLOAD',
    elockSecurityOtp: '912440',
    eSealBarcode: 'ES-LPG-33019-B'
  }
];

export const MOCK_TANKER_DRIVERS: TankerDriver[] = [
  {
    id: 'drv-01',
    name: 'Bambang Supriyanto',
    simNumber: '9208-1123-9901 (B2 Umum)',
    b3CertNumber: 'BNSP-B3-HAZMAT-2024-881',
    b3CertExpiry: '2027-05-14',
    phone: '0812-9844-1120',
    assignedTankerHull: 'TANK-BBM-2401',
    depotBase: 'TBBM Plumpang',
    medicalCheckupDate: '2026-08-15',
    alcoholTestResult: '0.00_PROMIL_FIT',
    bloodPressure: '120/80 mmHg',
    dmsScore: 98,
    totalLoadedTrips: 412,
    zeroLossRatePct: 99.7,
    status: 'ACTIVE_DRIVING'
  },
  {
    id: 'drv-02',
    name: 'Rudi Hartono',
    simNumber: '8812-4412-0091 (B2 Umum)',
    b3CertNumber: 'BNSP-CPO-TRANS-2023-402',
    b3CertExpiry: '2026-11-20',
    phone: '0813-7721-9903',
    assignedTankerHull: 'CPO-TAN-3208',
    depotBase: 'PKS Mill Riau',
    medicalCheckupDate: '2026-08-10',
    alcoholTestResult: '0.00_PROMIL_FIT',
    bloodPressure: '125/82 mmHg',
    dmsScore: 96,
    totalLoadedTrips: 580,
    zeroLossRatePct: 99.4,
    status: 'ACTIVE_DRIVING'
  },
  {
    id: 'drv-03',
    name: 'Suryadi Kusuma',
    simNumber: '7611-3001-9912 (B2 Umum)',
    b3CertNumber: 'BNSP-B3-CORROSIVE-2025-104',
    b3CertExpiry: '2028-02-10',
    phone: '0811-3320-119',
    assignedTankerHull: 'CHEM-ACID-1603',
    depotBase: 'Terminal Merak',
    medicalCheckupDate: '2026-08-18',
    alcoholTestResult: '0.00_PROMIL_FIT',
    bloodPressure: '118/78 mmHg',
    dmsScore: 99,
    totalLoadedTrips: 340,
    zeroLossRatePct: 99.9,
    status: 'ACTIVE_DRIVING'
  },
  {
    id: 'drv-04',
    name: 'Agus Priyono',
    simNumber: '9002-1188-7721 (B2 Umum)',
    b3CertNumber: 'BNSP-LPG-PRESSURE-2024-662',
    b3CertExpiry: '2027-09-08',
    phone: '0852-1109-8832',
    assignedTankerHull: 'LPG-SKID-1504',
    depotBase: 'Depot LPG Padalarang',
    medicalCheckupDate: '2026-08-05',
    alcoholTestResult: '0.00_PROMIL_FIT',
    bloodPressure: '122/80 mmHg',
    dmsScore: 97,
    totalLoadedTrips: 290,
    zeroLossRatePct: 99.6,
    status: 'ACTIVE_DRIVING'
  }
];

export const MOCK_CLEANING_LOGS: TankerCleaningLog[] = [
  {
    id: 'cln-01',
    tankerHull: 'TANK-BBM-1605',
    cleaningDate: '2026-08-21 08:30',
    cleaningBay: 'Bay #2 High Pressure Hot Water & Steam',
    previousCargo: 'BBM_BIOSOLAR',
    nextCargoPlanned: 'BBM_PERTALITE',
    cleaningMethod: 'STEAM_JET_DEGASSING',
    dryingMethod: 'BLOWER_HOT_AIR',
    inspectorName: 'Ir. Hendra Gunawan (QC K3)',
    gasFreeMeterPpm: 0,
    cleanCertificateNumber: 'CERT-CLN-PLP-2026-891',
    isApproved: true
  },
  {
    id: 'cln-02',
    tankerHull: 'CPO-TAN-2804',
    cleaningDate: '2026-08-20 14:15',
    cleaningBay: 'Bay #1 Food Grade CIP Station',
    previousCargo: 'CPO_CRUDE_PALM_OIL',
    nextCargoPlanned: 'OLEIN_COOKING_OIL',
    cleaningMethod: 'CAUSTIC_CHEMICAL_WASH',
    dryingMethod: 'INERT_NITROGEN_PURGING',
    inspectorName: 'Siti Rahayu, S.T. (Food Safety Lead)',
    gasFreeMeterPpm: 0,
    cleanCertificateNumber: 'CERT-CLN-FOOD-2026-440',
    isApproved: true
  }
];
