import {
  SecuricorArmoredVehicle,
  CitMissionRecord,
  SmartAtmCassette,
  SecurityGuardPatrol
} from '../types';

export const MOCK_ARMORED_FLEETS: SecuricorArmoredVehicle[] = [
  {
    id: 'cit-01',
    hullNumber: 'ARMOR-CIT-01',
    plateNumber: 'B 9110 SEC',
    vehicleType: 'ARMORED_CIT_VAN',
    ballisticLevel: 'CEN_B6_STANAG',
    runFlatTyreStatus: 'OPTIMAL_100KM',
    interlockingDoors: 'LOCKED_SECURE',
    vaultDoorStatus: 'LOCKED_DUAL_KEY',
    dropChuteActive: true,
    gpsLocation: {
      lat: -6.2088,
      lng: 106.8456,
      speedKmh: 42,
      address: 'Jl. Jend. Sudirman Kav. 1, Jakarta Pusat',
      corridorName: 'Secure Corridor Utama Sudirman-Thamrin',
    },
    currentStatus: 'EN_ROUTE_TRANSIT',
    currentCashPayloadIdr: 14.5, // 14.5 Milyar
    insuredCoverageIdr: 30.0,
    chiefEscortOfficer: 'Kapten (Purn) Hendra Kurniawan',
    armedPoliceEscort: 'Aiptu Bambang Sutrisno (Polda Metro Jaya)',
    driverName: 'Suryadi Pratama (Grade-A Defensive Armored)',
    cctvLiveFeedsCount: 6,
    silentDuressArmed: true,
    smokeDyePackArmed: true,
    lastVaultOpenTimestamp: '2026-08-21 08:30 WIB (Vault CPC Thamrin)',
    assignedBankClient: 'PT Bank Central Asia Tbk (BCA)',
    nextCheckpointName: 'ATM Center Grand Indonesia Mall',
    ktaSenpiExpiry: '2027-11-30',
  },
  {
    id: 'cit-02',
    hullNumber: 'ARMOR-CIT-02',
    plateNumber: 'B 9245 SEC',
    vehicleType: 'HEAVY_ARMORED_TRUCK',
    ballisticLevel: 'CEN_B7_ARMOR_PIERCING',
    runFlatTyreStatus: 'OPTIMAL_100KM',
    interlockingDoors: 'LOCKED_SECURE',
    vaultDoorStatus: 'LOCKED_DUAL_KEY',
    dropChuteActive: false,
    gpsLocation: {
      lat: -6.1754,
      lng: 106.8272,
      speedKmh: 28,
      address: 'Jl. MH Thamrin No. 2, Bank Indonesia Headquarter',
      corridorName: 'Ring 1 VVIP Bank Indonesia Corridor',
    },
    currentStatus: 'CASH_LOADING',
    currentCashPayloadIdr: 45.0, // 45 Milyar BI Clearing
    insuredCoverageIdr: 100.0,
    chiefEscortOfficer: 'Mayor (Purn) Teguh Wicaksono',
    armedPoliceEscort: 'Bripka Andi Wijaya & Briptu Ilham (Brimob)',
    driverName: 'Rahmat Hidayat (Tactical Convoy Driver)',
    cctvLiveFeedsCount: 8,
    silentDuressArmed: true,
    smokeDyePackArmed: true,
    lastVaultOpenTimestamp: '2026-08-21 09:15 WIB (BI Vault Room)',
    assignedBankClient: 'Bank Indonesia - Khazanah Nasional',
    nextCheckpointName: 'Cash Processing Center (CPC) Simatupang',
    ktaSenpiExpiry: '2027-08-15',
  },
  {
    id: 'cit-03',
    hullNumber: 'ARMOR-CIT-03',
    plateNumber: 'B 9388 SEC',
    vehicleType: 'ARMORED_CIT_VAN',
    ballisticLevel: 'CEN_B6_STANAG',
    runFlatTyreStatus: 'OPTIMAL_100KM',
    interlockingDoors: 'AIRLOCK_OPEN',
    vaultDoorStatus: 'OPENED_AUTHORIZED',
    dropChuteActive: true,
    gpsLocation: {
      lat: -6.2255,
      lng: 106.8095,
      speedKmh: 0,
      address: 'Pacific Place Mall SCBD, Lobby Barat ATM Zone',
      corridorName: 'SCBD Financial Corridor Zone A',
    },
    currentStatus: 'ATM_SERVICING',
    currentCashPayloadIdr: 8.2, // 8.2 Milyar
    insuredCoverageIdr: 25.0,
    chiefEscortOfficer: 'Agus Setiawan (Senior CIT Lead)',
    armedPoliceEscort: 'Aipda Dedi Prasetyo (Polsek Senayan)',
    driverName: 'Fajar Nugroho',
    cctvLiveFeedsCount: 6,
    silentDuressArmed: true,
    smokeDyePackArmed: true,
    lastVaultOpenTimestamp: '2026-08-21 09:42 WIB (Active Dual-Key Session)',
    assignedBankClient: 'PT Bank Mandiri (Persero) Tbk',
    nextCheckpointName: 'ATM Galeri Menara Mandiri Gatot Subroto',
    ktaSenpiExpiry: '2027-05-20',
  },
  {
    id: 'cit-04',
    hullNumber: 'ARMOR-CIT-04',
    plateNumber: 'B 9801 SEC',
    vehicleType: 'TACTICAL_ESCORT_SUV',
    ballisticLevel: 'VPAM_VR9',
    runFlatTyreStatus: 'OPTIMAL_100KM',
    interlockingDoors: 'LOCKED_SECURE',
    vaultDoorStatus: 'LOCKED_DUAL_KEY',
    dropChuteActive: false,
    gpsLocation: {
      lat: -6.1256,
      lng: 106.6558,
      speedKmh: 68,
      address: 'Tol Prof. Sedyatmo Km 22 (Bandara Soekarno Hatta)',
      corridorName: 'Airport Bullion & Valas Transit Line',
    },
    currentStatus: 'EN_ROUTE_TRANSIT',
    currentCashPayloadIdr: 22.0, // Valas & Gold Bullion
    insuredCoverageIdr: 50.0,
    chiefEscortOfficer: 'Lettu (Purn) Rudi Hartono',
    armedPoliceEscort: 'Ipda Arif Setiadi (Polres Bandara Soetta)',
    driverName: 'Joko Susilo',
    cctvLiveFeedsCount: 6,
    silentDuressArmed: true,
    smokeDyePackArmed: true,
    lastVaultOpenTimestamp: '2026-08-21 07:45 WIB (Cargo Kargo Bandara)',
    assignedBankClient: 'PT Bank Negara Indonesia (Persero) Tbk',
    nextCheckpointName: 'BNI Kantor Besar Harmoni Vault',
    ktaSenpiExpiry: '2028-01-10',
  },
  {
    id: 'cit-05',
    hullNumber: 'ARMOR-CIT-05',
    plateNumber: 'B 9042 SEC',
    vehicleType: 'ARMORED_CIT_VAN',
    ballisticLevel: 'CEN_B6_STANAG',
    runFlatTyreStatus: 'OPTIMAL_100KM',
    interlockingDoors: 'LOCKED_SECURE',
    vaultDoorStatus: 'LOCKED_DUAL_KEY',
    dropChuteActive: true,
    gpsLocation: {
      lat: -6.2912,
      lng: 106.7994,
      speedKmh: 0,
      address: 'Central Vault Room Cilandak TB Simatupang HQ',
      corridorName: 'Base Headquarters Security Perimeter',
    },
    currentStatus: 'STANDBY_VAULT',
    currentCashPayloadIdr: 0,
    insuredCoverageIdr: 20.0,
    chiefEscortOfficer: 'Eko Sulistyo',
    armedPoliceEscort: 'Bripka Wawan Darmawan',
    driverName: 'Danang Tri Wicaksono',
    cctvLiveFeedsCount: 6,
    silentDuressArmed: true,
    smokeDyePackArmed: true,
    lastVaultOpenTimestamp: '2026-08-20 18:00 WIB',
    assignedBankClient: 'Standby Ready Reserve Unit',
    nextCheckpointName: 'Standby Quick Response Alert 1',
    ktaSenpiExpiry: '2027-10-05',
  }
];

export const MOCK_CIT_MISSIONS: CitMissionRecord[] = [
  {
    id: 'cit-m-01',
    missionCode: 'CIT-20260821-BCA-001',
    clientBank: 'PT Bank Central Asia Tbk (BCA)',
    serviceType: 'ATM_REPLENISHMENT',
    assignedHull: 'ARMOR-CIT-01',
    originVault: 'CPC Khazanah Thamrin Tower B',
    destinationNode: '12 Titik ATM Mall & Galeri Sudirman - Kuningan',
    totalCashDeclaredIdr: 14500000000,
    cassettesCount: 48,
    dualCustodyOfficerA: 'Kapten (Purn) Hendra Kurniawan',
    dualCustodyOfficerB: 'Suryadi Pratama',
    status: 'EN_ROUTE_TRANSIT',
    scheduledTime: '08:00 WIB',
    departureTime: '08:35 WIB',
    estimatedArrival: '14:30 WIB',
    policeBadgeNumber: 'POL-782910-PMJ',
    otpVaultToken: 'OTP-8942-BCA-SEC',
  },
  {
    id: 'cit-m-02',
    missionCode: 'CIT-20260821-BI-002',
    clientBank: 'Bank Indonesia - Khazanah Nasional',
    serviceType: 'BANK_INDONESIA_CLEARING',
    assignedHull: 'ARMOR-CIT-02',
    originVault: 'Khazanah Pusat Gedung Bank Indonesia',
    destinationNode: 'CPC Central TB Simatupang & Bank Mandiri Head',
    totalCashDeclaredIdr: 45000000000,
    cassettesCount: 120,
    dualCustodyOfficerA: 'Mayor (Purn) Teguh Wicaksono',
    dualCustodyOfficerB: 'Rahmat Hidayat',
    status: 'CASH_LOADING',
    scheduledTime: '09:00 WIB',
    departureTime: '09:40 WIB (Pending Clearance)',
    estimatedArrival: '16:00 WIB',
    policeBadgeNumber: 'POL-663911-BRIMOB',
    otpVaultToken: 'OTP-9021-BI-SEC',
  },
  {
    id: 'cit-m-03',
    missionCode: 'CIT-20260821-MDR-003',
    clientBank: 'PT Bank Mandiri (Persero) Tbk',
    serviceType: 'ATM_REPLENISHMENT',
    assignedHull: 'ARMOR-CIT-03',
    originVault: 'CPC Mandiri Kebon Sirih',
    destinationNode: 'ATM Cluster SCBD, Senayan City, Pacific Place',
    totalCashDeclaredIdr: 8200000000,
    cassettesCount: 32,
    dualCustodyOfficerA: 'Agus Setiawan',
    dualCustodyOfficerB: 'Fajar Nugroho',
    status: 'ATM_SERVICING',
    scheduledTime: '08:30 WIB',
    departureTime: '09:00 WIB',
    estimatedArrival: '13:00 WIB',
    policeBadgeNumber: 'POL-554109-PMJ',
    otpVaultToken: 'OTP-3341-MDR-SEC',
  },
  {
    id: 'cit-m-04',
    missionCode: 'CIT-20260821-BNI-004',
    clientBank: 'PT Bank Negara Indonesia (Persero) Tbk',
    serviceType: 'RETAIL_CASH_PICKUP',
    assignedHull: 'ARMOR-CIT-04',
    originVault: 'Cargo Khusus Bandara Internasional Soetta',
    destinationNode: 'BNI Kantor Besar Harmoni Pusat',
    totalCashDeclaredIdr: 22000000000,
    cassettesCount: 60,
    dualCustodyOfficerA: 'Lettu (Purn) Rudi Hartono',
    dualCustodyOfficerB: 'Joko Susilo',
    status: 'EN_ROUTE_TRANSIT',
    scheduledTime: '07:00 WIB',
    departureTime: '07:50 WIB',
    estimatedArrival: '11:00 WIB',
    policeBadgeNumber: 'POL-910283-SOETTA',
    otpVaultToken: 'OTP-7712-BNI-SEC',
  }
];

export const MOCK_ATM_CASSETTES: SmartAtmCassette[] = [
  {
    id: 'cst-01',
    cassetteCode: 'CST-BCA-100K-001',
    atmId: 'ATM-BCA-GI-01',
    atmLocation: 'Grand Indonesia East Mall Lt. LG',
    denomination: 'IDR_100K',
    billCount: 2500,
    totalAmountIdr: 250000000,
    antiTheftSmokeStainArmed: true,
    rfidSealNumber: 'RFID-SEAL-998102',
    lockStatus: 'SECURED_SEALED',
    lastHandledBy: 'Kapten Hendra (Dual-Key Auth)',
  },
  {
    id: 'cst-02',
    cassetteCode: 'cst-BCA-50K-002',
    atmId: 'ATM-BCA-GI-01',
    atmLocation: 'Grand Indonesia East Mall Lt. LG',
    denomination: 'IDR_50K',
    billCount: 2500,
    totalAmountIdr: 125000000,
    antiTheftSmokeStainArmed: true,
    rfidSealNumber: 'RFID-SEAL-998103',
    lockStatus: 'SECURED_SEALED',
    lastHandledBy: 'Kapten Hendra (Dual-Key Auth)',
  },
  {
    id: 'cst-03',
    cassetteCode: 'CST-MDR-100K-003',
    atmId: 'ATM-MDR-PP-02',
    atmLocation: 'Pacific Place Mall SCBD Lobby Barat',
    denomination: 'IDR_100K',
    billCount: 2500,
    totalAmountIdr: 250000000,
    antiTheftSmokeStainArmed: true,
    rfidSealNumber: 'RFID-SEAL-883019',
    lockStatus: 'OPEN_AUDIT',
    lastHandledBy: 'Agus Setiawan (FLM Replenishment)',
  },
  {
    id: 'cst-04',
    cassetteCode: 'CST-BNI-100K-004',
    atmId: 'ATM-BNI-SEN-01',
    atmLocation: 'Senayan City Lt. 1 Galeri Perbankan',
    denomination: 'IDR_100K',
    billCount: 2500,
    totalAmountIdr: 250000000,
    antiTheftSmokeStainArmed: true,
    rfidSealNumber: 'RFID-SEAL-774022',
    lockStatus: 'SECURED_SEALED',
    lastHandledBy: 'Rudi Hartono (Sealed in Vault)',
  }
];

export const MOCK_GUARD_PATROLS: SecurityGuardPatrol[] = [
  {
    id: 'pat-01',
    guardName: 'Sertu (Purn) Darmawan',
    regNumber: 'SEC-GRD-8821',
    assignedZone: 'Central Vault Khazanah TB Simatupang',
    patrolMode: 'FOOT_PATROL',
    checkpointsCompleted: 14,
    totalCheckpoints: 16,
    lastNfcScanAt: '10 Menit yang lalu (Gate 3 Airlock)',
    lastCheckpointName: 'Post 04 - CCTV Control & Safe Room Outer Ring',
    duressStatus: 'NORMAL_STANDBY',
    bodyCamStreaming: true,
    shift: 'PAGI',
  },
  {
    id: 'pat-02',
    guardName: 'Ahmad Fauzi (Tactical Mobile)',
    regNumber: 'SEC-GRD-7742',
    assignedZone: 'SCBD Financial District Escort Outer Zone',
    patrolMode: 'MOTORCYCLE_MOBILE',
    checkpointsCompleted: 8,
    totalCheckpoints: 10,
    lastNfcScanAt: '5 Menit yang lalu (SCBD Lot 8)',
    lastCheckpointName: 'ATM Zone Mandiri Tower & SCBD Alley',
    duressStatus: 'NORMAL_STANDBY',
    bodyCamStreaming: true,
    shift: 'PAGI',
  },
  {
    id: 'pat-03',
    guardName: 'Bambang Sugiono',
    regNumber: 'SEC-GRD-9904',
    assignedZone: 'Airport Cargo Transit Corridor Perimeter',
    patrolMode: 'MOTORCYCLE_MOBILE',
    checkpointsCompleted: 12,
    totalCheckpoints: 12,
    lastNfcScanAt: '18 Menit yang lalu (Gate 5 Soetta Cargo)',
    lastCheckpointName: 'Perimeter Checkpoint 06 Valas Terminal',
    duressStatus: 'NORMAL_STANDBY',
    bodyCamStreaming: true,
    shift: 'PAGI',
  }
];
