/**
 * Fleet Intelligence Smart AI - Centralized Permission Catalog & Default Role Templates
 */

import { PermissionDefinition, RoleDefinition, SystemRole } from '../../types/rbac';

export const PERMISSION_MODULE_GROUPS = [
  { id: 'EXECUTIVE_C_LEVEL', title: 'Executive & C-Level Intelligence' },
  { id: 'ARMADA_KENDARAAN', title: 'Armada & Kendaraan' },
  { id: 'TELEMATIKA_OPERASIONAL', title: 'Telematika & Operasional' },
  { id: 'PEMELIHARAAN_BIAYA', title: 'Pemeliharaan & Keuangan' },
  { id: 'LAPORAN_AI', title: 'Laporan, Analitik & AI' },
  { id: 'LANGGANAN_BILLING', title: 'Langganan & Billing SaaS' },
  { id: 'ADMIN_SECURITY', title: 'Administrasi, Role & Sistem' },
];

export const PERMISSION_CATALOG: PermissionDefinition[] = [
  // Command Center (PROMPT 47)
  { key: 'command_center.view', module: 'command_center', action: 'view', label: 'Lihat Live Command Center', description: 'Akses memantau seluruh armada, status darurat, alert, dan peta kontrol telematika real-time', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'command_center.manage', module: 'command_center', action: 'edit', label: 'Kelola Command Center & Filter', description: 'Mengatur filter armada, layout ruang kontrol (Control Room Mode), dan konfigurasi audio alert', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'command_center.emergency', module: 'command_center', action: 'execute', label: 'Akses & Tangani Emergency SOS', description: 'Merespons tombol darurat/panic driver, eskalasi insiden, dan penugasan unit tanggap darurat', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'command_center.acknowledge', module: 'command_center', action: 'approve', label: 'Acknowledge & Selesaikan Alert', description: 'Mengonfirmasi penerimaan alert kritis, mengisi catatan resolusi, dan menyelesaikan tiket insiden', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'command_center.dispatch', module: 'command_center', action: 'execute', label: 'Smart Dispatch dari Command Center', description: 'Menghitung dan menugaskan armada terdekat dengan rekomendasi AI langsung dari peta kontrol', moduleGroup: 'TELEMATIKA_OPERASIONAL' },

  // 0. Executive Dashboard (PROMPT 38)
  { key: 'executive.dashboard.view', module: 'executive', action: 'view', label: 'Lihat Executive Dashboard', description: 'Akses ringkasan performa bisnis armada level Direksi & Owner (See → Understand → Decide → Act)', moduleGroup: 'EXECUTIVE_C_LEVEL' },
  { key: 'executive.dashboard.export', module: 'executive', action: 'export', label: 'Ekspor Executive Briefing & Report', description: 'Mendownload laporan eksekutif harian, mingguan, bulanan format PDF/Excel/CSV', moduleGroup: 'EXECUTIVE_C_LEVEL' },
  { key: 'executive.dashboard.ai', module: 'executive', action: 'view', label: 'Akses AI Executive Insights & Assistant', description: 'Melihat rekomendasi strategis AI, dampak bisnis, estimasi penghematan, dan tanya jawab Ask AI', moduleGroup: 'EXECUTIVE_C_LEVEL' },
  { key: 'executive.dashboard.financial', module: 'executive', action: 'view', label: 'Lihat Ringkasan Finansial Eksekutif', description: 'Melihat rincian TOC/TCO, cost per km, tren anggaran, dan cost alerts di level eksekutif', moduleGroup: 'EXECUTIVE_C_LEVEL' },
  { key: 'executive.dashboard.safety', module: 'executive', action: 'view', label: 'Lihat Skor Keselamatan Eksekutif', description: 'Melihat skor keselamatan armada, alert kritis keselamatan, dan tren insiden', moduleGroup: 'EXECUTIVE_C_LEVEL' },

  // 1. Dashboard
  { key: 'dashboard.view', module: 'dashboard', action: 'view', label: 'Lihat Ringkasan Dashboard Utama', description: 'Akses melihat KPI dan widget operational dashboard', moduleGroup: 'ARMADA_KENDARAAN' },

  // 2. Fleet & Vehicles
  { key: 'fleet.view', module: 'fleet', action: 'view', label: 'Lihat Daftar Armada', description: 'Akses daftar grup dan cabang armada', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'fleet.create', module: 'fleet', action: 'create', label: 'Tambah Armada Baru', description: 'Membuat grup atau cabang armada baru', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'fleet.edit', module: 'fleet', action: 'edit', label: 'Ubah Data Armada', description: 'Mengedit informasi grup armada', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'fleet.delete', module: 'fleet', action: 'delete', label: 'Hapus Armada', description: 'Menghapus struktur grup armada', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'fleet.export', module: 'fleet', action: 'export', label: 'Ekspor Data Armada', description: 'Mendownload laporan daftar armada', moduleGroup: 'ARMADA_KENDARAAN' },

  // Rent Car Management
  { key: 'rent_car.view', module: 'rent_car', action: 'view', label: 'Lihat Rent Car Management', description: 'Melihat inventaris rental, reservasi, dan telematika mobil sewa', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'rent_car.create', module: 'rent_car', action: 'create', label: 'Buat Reservasi & Pelanggan Rental', description: 'Membuat booking sewa baru dan mendaftarkan KYC penyewa', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'rent_car.edit', module: 'rent_car', action: 'edit', label: 'Kelola Serah Terima & Settle Deposit', description: 'Melakukan check-out, check-in, dan rekonsiliasi deposit escrow', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'rent_car.security', module: 'rent_car', action: 'execute', label: 'Eksekusi Remote Starter Kill', description: 'Otorisasi mematikan mesin jarak jauh dan penguncian starter immobilizer', moduleGroup: 'TELEMATIKA_OPERASIONAL' },

  { key: 'vehicle.view', module: 'vehicle', action: 'view', label: 'Lihat Data Kendaraan', description: 'Melihat profil, STNK, KIR, dan status kendaraan', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'vehicle.create', module: 'vehicle', action: 'create', label: 'Tambah Kendaraan', description: 'Registrasi unit armada kendaraan baru', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'vehicle.edit', module: 'vehicle', action: 'edit', label: 'Ubah Kendaraan', description: 'Mengedit spesifikasi, STNK, dan atribut unit', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'vehicle.delete', module: 'vehicle', action: 'delete', label: 'Hapus Kendaraan', description: 'Menghapus unit kendaraan dari sistem', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'vehicle.export', module: 'vehicle', action: 'export', label: 'Ekspor Data Kendaraan', description: 'Mendownload data inventaris kendaraan', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'vehicle.approve', module: 'vehicle', action: 'approve', label: 'Persetujuan Pengoperasian Unit', description: 'Menyetujui rilis kendaraan siap jalan', moduleGroup: 'ARMADA_KENDARAAN' },

  // 3. Driver
  { key: 'driver.view', module: 'driver', action: 'view', label: 'Lihat Data Pengemudi', description: 'Melihat profil driver, SIM, dan skor perilaku', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'driver.create', module: 'driver', action: 'create', label: 'Tambah Driver Baru', description: 'Registrasi akun dan data pengemudi baru', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'driver.edit', module: 'driver', action: 'edit', label: 'Ubah Data Driver', description: 'Mengubah status, SIM, dan penugasan driver', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'driver.delete', module: 'driver', action: 'delete', label: 'Hapus/Suspend Driver', description: 'Menghapus atau menangguhkan akun driver', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'driver.export', module: 'driver', action: 'export', label: 'Ekspor Data Driver', description: 'Mendownload daftar dan score card driver', moduleGroup: 'ARMADA_KENDARAAN' },

  // 4. GPS & Tracking
  { key: 'gps_device.view', module: 'gps_device', action: 'view', label: 'Lihat Perangkat GPS IoT', description: 'Melihat status IMEI, kartu SIM, dan sinyal GPS', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'gps_device.edit', module: 'gps_device', action: 'edit', label: 'Konfigurasi GPS Device', description: 'Mengubah protokol dan interval pengiriman data GPS', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'gps.device.view', module: 'gps_device', action: 'view', label: 'Lihat GPS Device Pool', description: 'Melihat inventaris perangkat GPS telematika', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'gps.protocol.view', module: 'gps_device', action: 'view', label: 'Lihat Gateway GPS & Protokol', description: 'Akses Gateway Protokol Abstraksi GPS (TCP/HTTP/MQTT/WS)', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'gps.sim.view', module: 'gps_device', action: 'view', label: 'Lihat SIM Cards IoT', description: 'Monitoring kuota dan status kartu SIM IoT telematika', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'gps.firmware.view', module: 'gps_device', action: 'view', label: 'Lihat Firmware GPS & OTA', description: 'Akses versi firmware dan jadwal OTA update', moduleGroup: 'TELEMATIKA_OPERASIONAL' },

  { key: 'tracking.view', module: 'tracking', action: 'view', label: 'Live GPS Tracking & Peta', description: 'Memantau posisi real-time dan histori pergerakan armada', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'tracking.export', module: 'tracking', action: 'export', label: 'Ekspor Histori Rute GPS', description: 'Download file GPX/KML atau CSV log perjalanan', moduleGroup: 'TELEMATIKA_OPERASIONAL' },

  // 5. Trip & Dispatch
  { key: 'route.view', module: 'route', action: 'view', label: 'Lihat Master Rute & Koridor', description: 'Melihat master rute jalan, batas tonase, dan koridor geofence rute', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'route.create', module: 'route', action: 'create', label: 'Buat Master Rute Baru', description: 'Menambahkan master rute baru dengan waypoint dan batas koridor', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'route.edit', module: 'route', action: 'edit', label: 'Ubah Data Rute', description: 'Mengedit koridor toleransi, waypoint, dan batas kecepatan rute', moduleGroup: 'TELEMATIKA_OPERASIONAL' },

  { key: 'trip.view', module: 'trip', action: 'view', label: 'Lihat Perjalanan (Trips)', description: 'Melihat jadwal dan status perjalanan armada', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'trip.create', module: 'trip', action: 'create', label: 'Buat Penugasan Perjalanan', description: 'Menjadwalkan rute perjalanan dan manifest kargo', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'trip.edit', module: 'trip', action: 'edit', label: 'Ubah Status Perjalanan', description: 'Mengubah rute, driver, atau waktu estimasi tiba', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'trip.export', module: 'trip', action: 'export', label: 'Ekspor Riwayat Perjalanan', description: 'Download manifest dan statistik perjalanan', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'trip.approve', module: 'trip', action: 'approve', label: 'Setujui Surja Jalan / Trip', description: 'Validasi dan rilis persetujuan surat jalan resmi', moduleGroup: 'TELEMATIKA_OPERASIONAL' },

  { key: 'geofence.view', module: 'geofence', action: 'view', label: 'Lihat Geofence & POI', description: 'Melihat zona depot, gudang, dan poin penting SPBU', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'geofence.create', module: 'geofence', action: 'create', label: 'Buat Area Geofence Baru', description: 'Menggambar area geofence poligon atau lingkaran', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'geofence.edit', module: 'geofence', action: 'edit', label: 'Ubah Geofence & Aturan', description: 'Mengubah radius dan toleransi overstay geofence', moduleGroup: 'TELEMATIKA_OPERASIONAL' },

  { key: 'alert.view', module: 'alert', action: 'view', label: 'Lihat Peringatan Sistem', description: 'Melihat notifikasi pelanggaran kecepatan, overstay, SOS', moduleGroup: 'TELEMATIKA_OPERASIONAL' },

  { key: 'safety.view', module: 'safety', action: 'view', label: 'Lihat Safety Score & Pelanggaran', description: 'Monitoring skor keselamatan berkendara & insiden', moduleGroup: 'TELEMATIKA_OPERASIONAL' },

  { key: 'inspection.view', module: 'inspection', action: 'view', label: 'Lihat Inspeksi & Pre-Trip', description: 'Melihat riwayat dan status inspeksi armada', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'inspection.create', module: 'inspection', action: 'create', label: 'Buat Laporan Inspeksi', description: 'Mengisi checklist inspeksi pra/pasca perjalanan', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'inspection.edit', module: 'inspection', action: 'edit', label: 'Ubah / Verifikasi Inspeksi', description: 'QC verifikasi perbaikan dan template checklist', moduleGroup: 'TELEMATIKA_OPERASIONAL' },
  { key: 'inspection.export', module: 'inspection', action: 'export', label: 'Ekspor Data Inspeksi', description: 'Download riwayat dan sertifikat kepatuhan inspeksi', moduleGroup: 'TELEMATIKA_OPERASIONAL' },

  // 6. Fuel & Maintenance & Finance
  { key: 'fuel.view', module: 'fuel', action: 'view', label: 'Lihat Data Konsumsi BBM', description: 'Melihat catatan pengisian dan grafik efisiensi BBM', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'fuel.create', module: 'fuel', action: 'create', label: 'Input Pengisian BBM', description: 'Mencatat resi pengisian solar/SPBU baru', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'fuel.edit', module: 'fuel', action: 'edit', label: 'Ubah Data BBM Anomali', description: 'Koreksi catatan transaksi BBM', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'fuel.export', module: 'fuel', action: 'export', label: 'Ekspor Audit BBM', description: 'Download rekapan konsumsi dan pengeluaran BBM', moduleGroup: 'PEMELIHARAAN_BIAYA' },

  { key: 'maintenance.view', module: 'maintenance', action: 'view', label: 'Lihat Pemeliharaan & Service', description: 'Melihat Work Order servis berkala dan perbaikan', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'maintenance.create', module: 'maintenance', action: 'create', label: 'Buat Work Order Servis', description: 'Pengajuan perintah kerja perbaikan bengkel', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'maintenance.edit', module: 'maintenance', action: 'edit', label: 'Ubah Status Work Order', description: 'Update progres pengerjaan dan suku cadang', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'maintenance.export', module: 'maintenance', action: 'export', label: 'Ekspor Riwayat Pemeliharaan', description: 'Download rekap servis dan biaya perawatan', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'maintenance.approve', module: 'maintenance', action: 'approve', label: 'Persetujuan Biaya Servis', description: 'Setujui estimasi pengeluaran perbaikan bengkel', moduleGroup: 'PEMELIHARAAN_BIAYA' },

  { key: 'finance.view', module: 'finance', action: 'view', label: 'Lihat Laporan Biaya Operasional', description: 'Akses finansial total biaya armada & TCO', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'finance.create', module: 'finance', action: 'create', label: 'Input Biaya Operasional', description: 'Mencatat pengeluaran tol, parkir, dan retribusi', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'finance.edit', module: 'finance', action: 'edit', label: 'Koreksi Data Keuangan', description: 'Mengubah entri jurnal biaya operasional', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'finance.export', module: 'finance', action: 'export', label: 'Ekspor Laporan Keuangan Armada', description: 'Download statement keuangan Excel/PDF', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'finance.approve', module: 'finance', action: 'approve', label: 'Persetujuan Klaim Reimburse', description: 'Menyetujui klaim pengeluaran driver', moduleGroup: 'PEMELIHARAAN_BIAYA' },

  // Cost Analytics & TOC/TCO (PROMPT 37)
  { key: 'cost.view', module: 'finance', action: 'view', label: 'Lihat Analisis Biaya & TOC/TCO', description: 'Akses melihat intelijen biaya armada, TOC/TCO, cost per km, dan dashboard budget', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'cost.create', module: 'finance', action: 'create', label: 'Input Pengeluaran Biaya Baru', description: 'Menambah transaksi biaya operasional armada', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'cost.edit', module: 'finance', action: 'edit', label: 'Ubah & Koreksi Biaya', description: 'Mengedit data transaksi biaya dan kategori', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'cost.delete', module: 'finance', action: 'delete', label: 'Hapus Catatan Biaya', description: 'Menghapus transaksi biaya operasional', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'cost.export', module: 'finance', action: 'export', label: 'Ekspor Laporan Biaya & TOC', description: 'Download laporan analisa biaya Excel/PDF/CSV', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'cost.approve', module: 'finance', action: 'approve', label: 'Otorisasi & Persetujuan Biaya', description: 'Menyetujui transaksi biaya di atas ambang batas (approval threshold)', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'cost.allocate', module: 'finance', action: 'edit', label: 'Alokasi Biaya Gabungan (Overhead)', description: 'Mendistribusikan biaya bersama secara proporsional ke unit/trip', moduleGroup: 'PEMELIHARAAN_BIAYA' },
  { key: 'cost.audit', module: 'finance', action: 'view', label: 'Audit Rekonsiliasi Telematika', description: 'Cross-verifikasi sensor IoT telematika vs kwitansi klaim dan buku kas', moduleGroup: 'PEMELIHARAAN_BIAYA' },

  // 7. Laporan, Analitik & AI
  { key: 'report.view', module: 'report', action: 'view', label: 'Lihat Laporan Otomatis', description: 'Akses modul laporan operasional mingguan/bulanan', moduleGroup: 'LAPORAN_AI' },
  { key: 'report.export', module: 'report', action: 'export', label: 'Ekspor File Laporan (Excel/PDF)', description: 'Download berkas laporan komprehensif', moduleGroup: 'LAPORAN_AI' },

  { key: 'analytics.view', module: 'analytics', action: 'view', label: 'Lihat Analitik & KPI Armada', description: 'Akses grafik performa, utilitas, dan kecenderungan', moduleGroup: 'LAPORAN_AI' },

  { key: 'route.intelligence.view', module: 'ai', action: 'view', label: 'Lihat AI Route & ETA Intelligence', description: 'Akses dashboard Route Intelligence, dynamic routing, live corridor deviation & ETA prediction', moduleGroup: 'LAPORAN_AI' },
  { key: 'route.intelligence.optimize', module: 'ai', action: 'execute', label: 'Optimasi AI Route & Re-routing', description: 'Menjalankan optimasi multi-objective rute dan dispatch alterative route', moduleGroup: 'LAPORAN_AI' },

  { key: 'fleet.intelligence.view', module: 'ai', action: 'view', label: 'Lihat AI Fleet Intelligence', description: 'Akses dashboard AI Fleet Intelligence, health score, utilisasi & performa', moduleGroup: 'LAPORAN_AI' },
  { key: 'fleet.intelligence.analyze', module: 'ai', action: 'view', label: 'Analisis Mendalam Fleet Intelligence', description: 'Menjalankan analisis akar masalah, komparasi periode & cabang', moduleGroup: 'LAPORAN_AI' },
  { key: 'fleet.intelligence.export', module: 'ai', action: 'export', label: 'Ekspor Laporan Fleet Intelligence', description: 'Mendownload laporan analitik kecerdasan armada', moduleGroup: 'LAPORAN_AI' },

  { key: 'driver.intelligence.view', module: 'ai', action: 'view', label: 'Lihat AI Driver Intelligence', description: 'Akses dashboard AI Driver Intelligence, Risk Score, Matrix & Behavior', moduleGroup: 'LAPORAN_AI' },
  { key: 'driver.intelligence.analyze', module: 'ai', action: 'view', label: 'Analisis Mendalam Driver Intelligence', description: 'Menganalisis profil telematika, komparasi driver & tren risiko', moduleGroup: 'LAPORAN_AI' },
  { key: 'driver.intelligence.export', module: 'ai', action: 'export', label: 'Ekspor Laporan Driver Intelligence', description: 'Download Driver Scorecard dan laporan AI Driver Intelligence PDF/Excel', moduleGroup: 'LAPORAN_AI' },

  { key: 'driver.coaching.view', module: 'driver', action: 'view', label: 'Lihat Program Coaching Driver', description: 'Akses daftar antrean coaching dan riwayat sesi', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'driver.coaching.create', module: 'driver', action: 'create', label: 'Jadwalkan Sesi Coaching Driver', description: 'Membuat sesi coaching baru dan generate AI coaching plan', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'driver.coaching.edit', module: 'driver', action: 'edit', label: 'Ubah Sesi Coaching Driver', description: 'Memperbarui catatan supervisor dan action plan coaching', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'driver.coaching.complete', module: 'driver', action: 'edit', label: 'Selesaikan & Evaluasi Sesi Coaching', description: 'Menyelesaikan sesi coaching dan mencatat skor efektivitas', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'driver.coaching.export', module: 'driver', action: 'export', label: 'Ekspor Log Coaching Driver', description: 'Download riwayat dan efektivitas coaching', moduleGroup: 'ARMADA_KENDARAAN' },

  { key: 'ai.view', module: 'ai', action: 'view', label: 'Lihat AI Smart Insights', description: 'Melihat rekomendasi pemeliharaan prediktif & BBM AI', moduleGroup: 'LAPORAN_AI' },
  { key: 'ai.chat', module: 'ai', action: 'create', label: 'Gunakan Fleet AI Copilot Chat', description: 'Berinteraksi langsung dengan AI Smart Fleet Copilot Agent', moduleGroup: 'LAPORAN_AI' },
  { key: 'ai.analyze', module: 'ai', action: 'view', label: 'Analisis Cross-Module AI', description: 'Melakukan analisis gabungan BBM, GPS, dan Maintenance', moduleGroup: 'LAPORAN_AI' },
  { key: 'ai.recommend', module: 'ai', action: 'view', label: 'Lihat Rekomendasi Proaktif AI', description: 'Melihat daftar optimasi biaya & keselamatan', moduleGroup: 'LAPORAN_AI' },
  { key: 'ai.tool.read', module: 'ai', action: 'view', label: 'Eksekusi Tool AI Read-Only', description: 'Mengizinkan AI membaca data telemetri real-time', moduleGroup: 'LAPORAN_AI' },
  { key: 'ai.tool.action', module: 'ai', action: 'edit', label: 'Eksekusi Tool AI Action', description: 'Mengizinkan AI mengusulkan tindakan perubahan data', moduleGroup: 'LAPORAN_AI' },
  { key: 'ai.execute', module: 'ai', action: 'execute', label: 'Terapkan / Eksekusi Tindakan AI', description: 'Konfirmasi dan eksekusi tindakan berisiko tinggi', moduleGroup: 'LAPORAN_AI' },
  { key: 'ai.admin', module: 'ai', action: 'admin', label: 'Kelola Pengaturan & Model AI', description: 'Konfigurasi provider, rate limit, dan policy AI', moduleGroup: 'LAPORAN_AI' },
  { key: 'ai.audit.view', module: 'ai', action: 'view', label: 'Lihat Log Audit & Biaya AI', description: 'Memonitor riwayat eksekusi dan konsumsi token AI', moduleGroup: 'LAPORAN_AI' },
  { key: 'ai.export', module: 'ai', action: 'export', label: 'Ekspor Rekomendasi AI', description: 'Download rangkuman analisis kecerdasan buatan', moduleGroup: 'LAPORAN_AI' },
  { key: 'ai.approve', module: 'ai', action: 'approve', label: 'Terapkan Optimalisasi AI', description: 'Menerapkan saran rute dan penjadwalan dari AI', moduleGroup: 'LAPORAN_AI' },

  // 8. AI Automation Engine (PROMPT 35)
  { key: 'automation.view', module: 'automation', action: 'view', label: 'Lihat AI Automation & Workflow', description: 'Melihat dashboard automasi, workflow aktif, dan template', moduleGroup: 'LAPORAN_AI' },
  { key: 'automation.create', module: 'automation', action: 'create', label: 'Buat Automation Workflow Baru', description: 'Merancang workflow event-condition-AI-action baru', moduleGroup: 'LAPORAN_AI' },
  { key: 'automation.edit', module: 'automation', action: 'edit', label: 'Ubah Automation Workflow', description: 'Mengedit konfigurasi node, kondisi, dan parameter automasi', moduleGroup: 'LAPORAN_AI' },
  { key: 'automation.delete', module: 'automation', action: 'delete', label: 'Hapus Workflow Automasi', description: 'Menghapus workflow automasi dari sistem', moduleGroup: 'LAPORAN_AI' },
  { key: 'automation.execute', module: 'automation', action: 'execute', label: 'Eksekusi Manual / Trigger Automasi', description: 'Menjalankan workflow atau simulasi pengujian secara manual', moduleGroup: 'LAPORAN_AI' },
  { key: 'automation.publish', module: 'automation', action: 'edit', label: 'Rilis & Aktifkan Workflow (Publish)', description: 'Mempublikasikan draft workflow ke status aktif produksi', moduleGroup: 'LAPORAN_AI' },
  { key: 'automation.pause', module: 'automation', action: 'edit', label: 'Jeda / Lanjutkan Automasi (Pause/Resume)', description: 'Menghentikan sementara atau mengaktifkan kembali automasi', moduleGroup: 'LAPORAN_AI' },
  { key: 'automation.test', module: 'automation', action: 'execute', label: 'Uji Coba Dry Run Automasi', description: 'Menjalankan simulasi pengujian tanpa aksi nyata', moduleGroup: 'LAPORAN_AI' },
  { key: 'automation.export', module: 'automation', action: 'export', label: 'Ekspor Workflow & Log Eksekusi', description: 'Mendownload definisi workflow dan audit log automasi', moduleGroup: 'LAPORAN_AI' },
  { key: 'automation.audit', module: 'automation', action: 'view', label: 'Lihat Log Eksekusi & Audit Automasi', description: 'Akses riwayat eksekusi mendalam dan jejak audit AI automasi', moduleGroup: 'LAPORAN_AI' },

  // 9. Admin, Users & Settings
  { key: 'user.view', module: 'user', action: 'view', label: 'Lihat Daftar Pengguna', description: 'Melihat pengguna akun perusahaan dan status aktif', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'user.create', module: 'user', action: 'create', label: 'Undang / Tambah Pengguna', description: 'Mengundang staf baru ke konsol enterprise', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'user.edit', module: 'user', action: 'edit', label: 'Ubah Pengguna & Role Assignment', description: 'Mengganti role, cabang, dan status akun user', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'user.delete', module: 'user', action: 'delete', label: 'Hapus / Nonaktifkan Pengguna', description: 'Mencabut akses login staf perusahaan', moduleGroup: 'ADMIN_SECURITY' },

  { key: 'role.view', module: 'role', action: 'view', label: 'Lihat Daftar Role & Matriks Izin', description: 'Akses melihat matriks kewenangan per Peran', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'role.create', module: 'role', action: 'create', label: 'Buat Custom Role Baru', description: 'Menambah peran khusus kustom perusahaan', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'role.edit', module: 'role', action: 'edit', label: 'Ubah Matriks Matriks Izin Role', description: 'Mengubah izin pada peran yang ada', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'role.delete', module: 'role', action: 'delete', label: 'Hapus Custom Role', description: 'Menghapus peran kustom jika tidak digunakan', moduleGroup: 'ADMIN_SECURITY' },

  { key: 'company.view', module: 'company', action: 'view', label: 'Lihat Profil Perusahaan / Tenant', description: 'Melihat profil perusahaan dan cabang', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'company.edit', module: 'company', action: 'edit', label: 'Ubah Profil & NPWP Perusahaan', description: 'Mengubah identitas legal dan alamat kantor pusat', moduleGroup: 'ADMIN_SECURITY' },

  { key: 'integration.view', module: 'integration', action: 'view', label: 'Lihat Integrasi Gateway GPS', description: 'Melihat status koneksi API / Telematika IoT', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'integration.edit', module: 'integration', action: 'edit', label: 'Konfigurasi Webhook & API Key', description: 'Mengatur kredensial integrasi pihak ketiga', moduleGroup: 'ADMIN_SECURITY' },

  { key: 'audit_log.view', module: 'audit_log', action: 'view', label: 'Lihat Audit Log Keamanan', description: 'Melihat jejak aktivitas otentikasi & perubahan role', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'audit.view', module: 'audit', action: 'view', label: 'Lihat Audit Trail & Activity Log', description: 'Akses penuh ke modul observabilitas, log aktivitas, security, dan diff data', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'audit.export', module: 'audit', action: 'export', label: 'Ekspor Berkas Audit Log', description: 'Mendownload data log audit dalam format CSV, Excel, atau PDF', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'audit.manage', module: 'audit', action: 'admin', label: 'Kelola Kebijakan Retensi Audit', description: 'Mengatur retensi log, immutable lock, dan memvalidasi integritas ledger', moduleGroup: 'ADMIN_SECURITY' },

  { key: 'settings.view', module: 'settings', action: 'view', label: 'Lihat Pengaturan Sistem', description: 'Akses halaman konfigurasi umum tenant', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'settings.edit', module: 'settings', action: 'edit', label: 'Ubah Pengaturan Sistem', description: 'Mengubah parameter ambang batas kecepatan & zona', moduleGroup: 'ADMIN_SECURITY' },

  // 10. Subscription & Billing Engine (PROMPT 41)
  { key: 'billing.view', module: 'subscription', action: 'view', label: 'Lihat Status Langganan & Kuota', description: 'Akses melihat paket langganan aktif, meter kuota, dan siklus tagihan', moduleGroup: 'LANGGANAN_BILLING' },
  { key: 'billing.manage', module: 'subscription', action: 'admin', label: 'Kelola Penuh Subscription & Billing', description: 'Wewenang penuh administrasi billing perusahaan', moduleGroup: 'LANGGANAN_BILLING' },
  { key: 'billing.plan.view', module: 'subscription', action: 'view', label: 'Lihat Katalog & Komparasi Paket', description: 'Melihat perbandingan paket Starter, Pro, Enterprise', moduleGroup: 'LANGGANAN_BILLING' },
  { key: 'billing.plan.manage', module: 'subscription', action: 'admin', label: 'Kelola Katalog Paket SaaS (Super Admin)', description: 'Membuat, mengedit harga, kuota, dan fitur paket berlangganan', moduleGroup: 'LANGGANAN_BILLING' },
  { key: 'billing.subscription.view', module: 'subscription', action: 'view', label: 'Lihat Riwayat Subscription', description: 'Melihat log perubahan paket, perpanjangan, dan status trial', moduleGroup: 'LANGGANAN_BILLING' },
  { key: 'billing.subscription.manage', module: 'subscription', action: 'edit', label: 'Kelola Langganan Tenant (Super Admin)', description: 'Perpanjang trial, suspend, reactivate, atau override kuota custom', moduleGroup: 'LANGGANAN_BILLING' },
  { key: 'billing.invoice.view', module: 'subscription', action: 'view', label: 'Lihat Riwayat Invoice & Tagihan', description: 'Akses daftar tagihan, status pembayaran, dan riwayat transaksi', moduleGroup: 'LANGGANAN_BILLING' },
  { key: 'billing.invoice.download', module: 'subscription', action: 'export', label: 'Download Invoice / Bukti Bayar', description: 'Mendownload faktur tagihan dan kwitansi resmi PDF', moduleGroup: 'LANGGANAN_BILLING' },
  { key: 'billing.payment.view', module: 'subscription', action: 'view', label: 'Lihat Metode Pembayaran', description: 'Melihat konfigurasi kartu kredit, VA, dan auto-renewal', moduleGroup: 'LANGGANAN_BILLING' },
  { key: 'billing.usage.view', module: 'subscription', action: 'view', label: 'Lihat Detail Meter Pemakaian Kuota', description: 'Melihat histori konsumsi kendaraan, device, user, dan AI credits', moduleGroup: 'LANGGANAN_BILLING' },
  { key: 'billing.upgrade', module: 'subscription', action: 'edit', label: 'Upgrade Paket Berlangganan', description: 'Melakukan checkout peningkatan paket ke tingkat lebih tinggi', moduleGroup: 'LANGGANAN_BILLING' },
  { key: 'billing.downgrade', module: 'subscription', action: 'edit', label: 'Downgrade Paket Berlangganan', description: 'Menjadwalkan penurunan paket dengan pemeriksaan kompatibilitas kuota', moduleGroup: 'LANGGANAN_BILLING' },
  { key: 'billing.cancel', module: 'subscription', action: 'delete', label: 'Batalkan Langganan Perusahaan', description: 'Mengajukan pembatalan paket berlangganan di akhir periode', moduleGroup: 'LANGGANAN_BILLING' },

  // 11. Super Admin Control Center (PROMPT 42)
  { key: 'admin.dashboard.view', module: 'super_admin', action: 'view', label: 'Lihat Super Admin Executive Dashboard', description: 'Melihat KPI makro platform SaaS, MRR, ARR, device pool, dan throughput', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'admin.company.manage', module: 'super_admin', action: 'admin', label: 'Kelola Tenant & Perusahaan (Super Admin)', description: 'Akses penuh buat, edit, suspend, reactivate, dan override kuota tenant', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'admin.user.manage', module: 'super_admin', action: 'admin', label: 'Kelola Pengguna Lintas Platform', description: 'Melihat seluruh user lintas tenant, lock/unlock akun, dan force session logout', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'admin.device.manage', module: 'super_admin', action: 'admin', label: 'Kelola Pool Perangkat GPS & IoT SIM', description: 'Monitoring pool GPS global, SIM provider, protokol telematika, dan OTA batch update', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'admin.subscription.manage', module: 'super_admin', action: 'admin', label: 'Kelola Subscription & Custom Plan Global', description: 'Pengaturan paket SaaS global, override kuota custom, dan perpanjangan trial', moduleGroup: 'LANGGANAN_BILLING' },
  { key: 'admin.revenue.view', module: 'super_admin', action: 'view', label: 'Lihat Analitik Finansial & Revenue SaaS', description: 'Akses MRR, ARR, ARPU, Churn Rate, NRR, dan gateway payment breakdown', moduleGroup: 'LANGGANAN_BILLING' },
  { key: 'admin.ai.manage', module: 'super_admin', action: 'admin', label: 'Kelola & Monitoring Konsumsi Token AI', description: 'Pantau penggunaan token Gemini Pro/Flash, cost USD/IDR, dan limit kuota AI tenant', moduleGroup: 'LAPORAN_AI' },
  { key: 'admin.api.manage', module: 'super_admin', action: 'admin', label: 'Monitoring API Gateway & Rate Limits', description: 'Akses metrik throughput API, P95/P99 latency, error rate, dan throttled requests', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'admin.health.view', module: 'super_admin', action: 'view', label: 'Lihat System Health & Microservices', description: 'Monitoring cluster status, ingestion rate, Redis hit rate, dan resource CPU/RAM', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'admin.incident.manage', module: 'super_admin', action: 'admin', label: 'Pusat Manajemen Insiden & Status Page', description: 'Buat update status insiden platform, jadwal maintenance, dan broadcast pengumuman', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'admin.audit.view', module: 'super_admin', action: 'view', label: 'Lihat Audit Trail Lintas Platform', description: 'Akses log audit keamanan global dan jejak investigasi kepatuhan', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'admin.impersonate', module: 'super_admin', action: 'execute', label: 'Akses Support / Impersonate Tenant', description: 'Masuk ke ruang kerja tenant atas izin support dengan audit ketat', moduleGroup: 'ADMIN_SECURITY' },

  // 12. Document Management & Expiry Intelligence (PROMPT 48)
  { key: 'document.view', module: 'document', action: 'view', label: 'Lihat Dokumen & Expiry Tracking', description: 'Melihat repository dokumen armada, driver, dan perusahaan serta status kedaluwarsa', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'document.create', module: 'document', action: 'create', label: 'Unggah Dokumen & OCR Scan', description: 'Mengunggah file dokumen baru, scan kamera mobile, dan ekstraksi AI OCR', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'document.edit', module: 'document', action: 'edit', label: 'Ubah & Perbarui Versi Dokumen', description: 'Mengedit metadata tanggal kedaluwarsa dan mengunggah revisi versi baru', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'document.delete', module: 'document', action: 'delete', label: 'Arsipkan & Hapus Dokumen', description: 'Mengarsipkan atau menghapus berkas dokumen (dilindungi Legal Hold)', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'document.verify', module: 'document', action: 'approve', label: 'Verifikasi & Approval Dokumen', description: 'Memvalidasi, menyetujui, atau menolak permohonan verifikasi dokumen staf', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'document.export', module: 'document', action: 'export', label: 'Ekspor Laporan Kepatuhan Dokumen', description: 'Mendownload laporan kepatuhan dokumen, PDF, Excel, dan CSV', moduleGroup: 'ARMADA_KENDARAAN' },
  { key: 'document.admin', module: 'document', action: 'admin', label: 'Kelola Template Aturan Kepatuhan & Kuota', description: 'Mengatur template kepatuhan per jenis unit/driver dan konfigurasi retensi storage', moduleGroup: 'ADMIN_SECURITY' },

  // 13. Audit Trail & Activity Log (PROMPT 49)
  { key: 'audit.view', module: 'audit', action: 'view', label: 'Lihat Audit Trail & Activity Log', description: 'Melihat riwayat aktivitas user, log forensik keamanan, dan status integritas SHA-256', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'audit.export', module: 'audit', action: 'export', label: 'Ekspor Berkas Log Audit (JSON/CSV)', description: 'Mendownload export log audit terenkripsi dan ringkasan audit trail', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'audit.manage', module: 'audit', action: 'admin', label: 'Kelola Retensi & Konfigurasi Audit', description: 'Mengatur kebijakan retensi log audit, PII redaction rules, dan legal hold', moduleGroup: 'ADMIN_SECURITY' },

  // 14. Enterprise Security & Zero Trust Layer (PROMPT 50)
  { key: 'security.view', module: 'security', action: 'view', label: 'Lihat Enterprise Security Center', description: 'Akses dashboard keamanan Zero Trust, postur keamanan, sesi aktif, dan radar ancaman', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'security.manage', module: 'security', action: 'admin', label: 'Kelola Kebijakan Keamanan & Kepatuhan', description: 'Mengatur password policy, session timeouts, API keys, dan GPS gateway firewall', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'security.execute', module: 'security', action: 'execute', label: 'Eksekusi Disaster Recovery & Emergency Lockdown', description: 'Menjalankan simulasi DR restore rehearsal, snapshot manual, dan lockdown darurat', moduleGroup: 'ADMIN_SECURITY' },

  // 15. Human Resources & Driver Compliance
  { key: 'hr.view', module: 'hr', action: 'view', label: 'Lihat Data Karyawan & Personel Driver', description: 'Melihat profil kepegawaian, verifikasi SIM/KTP/SKCK, dan status kontrak driver', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'hr.create', module: 'hr', action: 'create', label: 'Tambah / Rekrut Karyawan Baru', description: 'Input data staf, onboarding driver baru, dan registrasi berkas HR', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'hr.edit', module: 'hr', action: 'edit', label: 'Ubah Data Kepegawaian & Kepatuhan', description: 'Memperbarui status lisensi SIM, sertifikat pelatihan K3, dan status aktif staf', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'hr.delete', module: 'hr', action: 'delete', label: 'Nonaktifkan / PHK Karyawan', description: 'Menonaktifkan akses staf dan memproses offboarding', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'hr.export', module: 'hr', action: 'export', label: 'Ekspor Rekapitulasi Personel & Kepatuhan', description: 'Download rekap data SDM, absensi, dan sertifikasi driver', moduleGroup: 'ADMIN_SECURITY' },
  { key: 'hr.approve', module: 'hr', action: 'approve', label: 'Persetujuan Rekrutmen & Verifikasi Lisensi', description: 'Validasi kelayakan kerja driver dan persetujuan pengangkatan staf', moduleGroup: 'ADMIN_SECURITY' },
];

const ALL_PERMISSION_KEYS = PERMISSION_CATALOG.map((p) => p.key);

export const DEFAULT_SYSTEM_ROLES: RoleDefinition[] = [
  {
    id: 'super_admin',
    name: 'Super Admin',
    description: 'Administrator platform SaaS utama dengan kontrol global lintas seluruh tenant, penagihan, device pool, dan infrastruktur sistem.',
    scope: 'GLOBAL',
    isSystem: true,
    isActive: true,
    usersCount: 2,
    permissions: ALL_PERMISSION_KEYS,
    granularScope: {
      modules: ['command_center', 'dashboard', 'executive', 'fleet', 'vehicle', 'driver', 'gps_device', 'tracking', 'trip', 'route', 'dispatch', 'geofence', 'alert', 'safety', 'inspection', 'fuel', 'maintenance', 'finance', 'report', 'analytics', 'ai', 'user', 'role', 'company', 'integration', 'audit_log', 'settings', 'subscription', 'super_admin', 'automation', 'document', 'audit', 'security', 'hr'],
      allowedMenus: ['menu_command_center', 'menu_executive_dashboard', 'menu_live_tracking', 'menu_fleet_vehicles', 'menu_drivers', 'menu_trips_dispatch', 'menu_routes', 'menu_geofence', 'menu_fuel', 'menu_maintenance', 'menu_safety_fatigue', 'menu_inspection', 'menu_cost_analytics', 'menu_reports', 'menu_analytics', 'menu_ai_copilot', 'menu_automation', 'menu_documents', 'menu_users_roles', 'menu_security_center', 'menu_subscription', 'menu_settings', 'menu_gps_integration', 'menu_super_admin'],
      allowedActions: ['view', 'create', 'edit', 'delete', 'export', 'approve', 'execute', 'admin'],
      vehicleScope: 'ALL',
      branchScope: 'ALL',
      departmentScope: 'ALL',
      regionScope: 'ALL',
    },
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'company_owner',
    name: 'Company Owner',
    description: 'Pemilik perusahaan dengan wewenang tertinggi atas seluruh keputusan bisnis, finansial, efisiensi operasional, dan laporan eksekutif.',
    scope: 'COMPANY',
    isSystem: true,
    isActive: true,
    usersCount: 2,
    permissions: [
      'executive.dashboard.view',
      'executive.dashboard.export',
      'executive.dashboard.ai',
      'executive.dashboard.financial',
      'executive.dashboard.safety',
      'dashboard.view',
      'fleet.view',
      'fleet.export',
      'vehicle.view',
      'vehicle.export',
      'driver.view',
      'driver.export',
      'tracking.view',
      'tracking.export',
      'trip.view',
      'trip.export',
      'fuel.view',
      'fuel.export',
      'maintenance.view',
      'maintenance.export',
      'finance.view',
      'finance.export',
      'cost.view',
      'cost.export',
      'cost.approve',
      'cost.audit',
      'safety.view',
      'document.view',
      'document.export',
      'analytics.view',
      'report.view',
      'report.export',
      'ai.view',
      'ai.chat',
      'ai.analyze',
      'ai.recommend',
      'ai.export',
      'ai.tool.read',
      'user.view',
      'role.view',
      'settings.view',
      'billing.view',
      'security.view',
    ],
    granularScope: {
      modules: ['executive', 'dashboard', 'fleet', 'vehicle', 'driver', 'tracking', 'trip', 'fuel', 'maintenance', 'finance', 'report', 'analytics', 'ai', 'user', 'role', 'settings', 'subscription', 'security'],
      allowedMenus: ['menu_executive_dashboard', 'menu_command_center', 'menu_live_tracking', 'menu_fleet_vehicles', 'menu_drivers', 'menu_trips_dispatch', 'menu_fuel', 'menu_maintenance', 'menu_safety_fatigue', 'menu_cost_analytics', 'menu_reports', 'menu_analytics', 'menu_ai_copilot', 'menu_documents', 'menu_users_roles', 'menu_security_center', 'menu_subscription', 'menu_settings'],
      allowedActions: ['view', 'export', 'approve', 'admin'],
      vehicleScope: 'ALL',
      branchScope: 'ALL',
      departmentScope: 'ALL',
      regionScope: 'ALL',
    },
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-17T00:00:00Z',
  },
  {
    id: 'company_admin',
    name: 'Company Admin',
    description: 'Administrator tenant perusahaan dengan kewenangan penuh untuk mengelola pengguna, armada, cabang, peran, dan konfigurasi tenant.',
    scope: 'COMPANY',
    isSystem: true,
    isActive: true,
    usersCount: 5,
    permissions: ALL_PERMISSION_KEYS.filter((k) => !k.startsWith('super_admin') && !k.startsWith('admin.')),
    granularScope: {
      modules: ['command_center', 'dashboard', 'executive', 'fleet', 'vehicle', 'driver', 'gps_device', 'tracking', 'trip', 'route', 'dispatch', 'geofence', 'alert', 'safety', 'inspection', 'fuel', 'maintenance', 'finance', 'report', 'analytics', 'ai', 'user', 'role', 'company', 'integration', 'audit_log', 'settings', 'subscription', 'automation', 'document', 'audit', 'security', 'hr'],
      allowedMenus: ['menu_command_center', 'menu_executive_dashboard', 'menu_live_tracking', 'menu_fleet_vehicles', 'menu_drivers', 'menu_trips_dispatch', 'menu_routes', 'menu_geofence', 'menu_fuel', 'menu_maintenance', 'menu_safety_fatigue', 'menu_inspection', 'menu_cost_analytics', 'menu_reports', 'menu_analytics', 'menu_ai_copilot', 'menu_automation', 'menu_documents', 'menu_users_roles', 'menu_security_center', 'menu_subscription', 'menu_settings', 'menu_gps_integration'],
      allowedActions: ['view', 'create', 'edit', 'delete', 'export', 'approve', 'execute', 'admin'],
      vehicleScope: 'ALL',
      branchScope: 'ALL',
      departmentScope: 'ALL',
      regionScope: 'ALL',
    },
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'fleet_manager',
    name: 'Fleet Manager',
    description: 'Manajer armada yang bertanggung jawab atas kesiapan seluruh unit kendaraan, operasional driver, pemeliharaan, efisiensi BBM, dan keselamatan.',
    scope: 'COMPANY',
    isSystem: true,
    isActive: true,
    usersCount: 12,
    permissions: [
      'command_center.view',
      'command_center.manage',
      'command_center.emergency',
      'command_center.acknowledge',
      'dashboard.view',
      'fleet.view',
      'fleet.create',
      'fleet.edit',
      'fleet.export',
      'vehicle.view',
      'vehicle.create',
      'vehicle.edit',
      'vehicle.export',
      'vehicle.approve',
      'driver.view',
      'driver.create',
      'driver.edit',
      'driver.export',
      'gps_device.view',
      'tracking.view',
      'tracking.export',
      'trip.view',
      'trip.create',
      'trip.edit',
      'trip.export',
      'trip.approve',
      'route.view',
      'route.create',
      'route.edit',
      'geofence.view',
      'geofence.create',
      'geofence.edit',
      'alert.view',
      'safety.view',
      'inspection.view',
      'inspection.create',
      'inspection.edit',
      'inspection.export',
      'fuel.view',
      'fuel.create',
      'fuel.edit',
      'fuel.export',
      'maintenance.view',
      'maintenance.create',
      'maintenance.edit',
      'maintenance.export',
      'maintenance.approve',
      'report.view',
      'report.export',
      'analytics.view',
      'ai.view',
      'ai.chat',
      'ai.analyze',
      'ai.recommend',
      'ai.tool.read',
      'document.view',
      'document.create',
      'document.edit',
      'document.verify',
    ],
    granularScope: {
      modules: ['command_center', 'dashboard', 'fleet', 'vehicle', 'driver', 'gps_device', 'tracking', 'trip', 'route', 'geofence', 'alert', 'safety', 'inspection', 'fuel', 'maintenance', 'report', 'analytics', 'ai', 'document'],
      allowedMenus: ['menu_command_center', 'menu_live_tracking', 'menu_fleet_vehicles', 'menu_drivers', 'menu_trips_dispatch', 'menu_routes', 'menu_geofence', 'menu_fuel', 'menu_maintenance', 'menu_safety_fatigue', 'menu_inspection', 'menu_reports', 'menu_analytics', 'menu_ai_copilot', 'menu_documents'],
      allowedActions: ['view', 'create', 'edit', 'export', 'approve', 'execute'],
      vehicleScope: 'ALL',
      branchScope: 'ALL',
      departmentScope: 'DEPT_FLEET_MANAGEMENT',
      regionScope: 'ALL',
    },
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'operations_manager',
    name: 'Operations Manager',
    description: 'Manajer operasional harian yang mengawasi live dispatch, rute pengiriman, pemantauan command center, SLA ketepatan waktu, dan investigasi insiden.',
    scope: 'COMPANY',
    isSystem: true,
    isActive: true,
    usersCount: 8,
    permissions: [
      'command_center.view',
      'command_center.manage',
      'command_center.emergency',
      'command_center.acknowledge',
      'command_center.dispatch',
      'dashboard.view',
      'fleet.view',
      'vehicle.view',
      'driver.view',
      'gps_device.view',
      'tracking.view',
      'tracking.export',
      'trip.view',
      'trip.create',
      'trip.edit',
      'trip.export',
      'trip.approve',
      'route.view',
      'route.create',
      'route.edit',
      'geofence.view',
      'geofence.create',
      'geofence.edit',
      'alert.view',
      'safety.view',
      'inspection.view',
      'fuel.view',
      'report.view',
      'report.export',
      'analytics.view',
      'ai.view',
      'ai.chat',
      'ai.analyze',
      'ai.recommend',
      'ai.tool.read',
      'document.view',
    ],
    granularScope: {
      modules: ['command_center', 'dashboard', 'fleet', 'vehicle', 'driver', 'tracking', 'trip', 'route', 'geofence', 'alert', 'safety', 'inspection', 'fuel', 'report', 'analytics', 'ai', 'document'],
      allowedMenus: ['menu_command_center', 'menu_live_tracking', 'menu_fleet_vehicles', 'menu_drivers', 'menu_trips_dispatch', 'menu_routes', 'menu_geofence', 'menu_safety_fatigue', 'menu_reports', 'menu_analytics', 'menu_ai_copilot'],
      allowedActions: ['view', 'create', 'edit', 'export', 'approve', 'execute'],
      vehicleScope: 'ALL',
      branchScope: 'ALL',
      departmentScope: 'DEPT_OPERATIONS',
      regionScope: 'ALL',
    },
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'dispatcher',
    name: 'Dispatcher',
    description: 'Petugas dispatch perjalanan armada, penjadwalan trip, penugasan surat jalan, dan komunikasi operasional pengemudi per cabang.',
    scope: 'BRANCH',
    isSystem: true,
    isActive: true,
    usersCount: 16,
    permissions: [
      'command_center.view',
      'command_center.emergency',
      'command_center.acknowledge',
      'command_center.dispatch',
      'dashboard.view',
      'vehicle.view',
      'driver.view',
      'tracking.view',
      'trip.view',
      'trip.create',
      'trip.edit',
      'trip.export',
      'trip.approve',
      'route.view',
      'geofence.view',
      'alert.view',
      'driver.intelligence.view',
      'report.view',
    ],
    granularScope: {
      modules: ['command_center', 'dashboard', 'vehicle', 'driver', 'tracking', 'trip', 'route', 'geofence', 'alert', 'report'],
      allowedMenus: ['menu_command_center', 'menu_live_tracking', 'menu_fleet_vehicles', 'menu_drivers', 'menu_trips_dispatch', 'menu_routes', 'menu_geofence', 'menu_reports'],
      allowedActions: ['view', 'create', 'edit', 'export', 'approve', 'execute'],
      vehicleScope: 'BRANCH_ONLY',
      branchScope: 'ASSIGNED_BRANCHES',
      departmentScope: 'DEPT_DISPATCH',
      regionScope: 'ASSIGNED_REGIONS',
    },
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'supervisor',
    name: 'Supervisor',
    description: 'Penyelia lapangan dan cabang yang memantau performa harian armada, kepatuhan K3, coaching driver, serta verifikasi inspeksi pra-jalan.',
    scope: 'BRANCH',
    isSystem: true,
    isActive: true,
    usersCount: 10,
    permissions: [
      'command_center.view',
      'command_center.acknowledge',
      'dashboard.view',
      'vehicle.view',
      'driver.view',
      'driver.edit',
      'tracking.view',
      'trip.view',
      'trip.edit',
      'safety.view',
      'inspection.view',
      'inspection.create',
      'inspection.edit',
      'inspection.export',
      'alert.view',
      'fuel.view',
      'driver.coaching.view',
      'driver.coaching.create',
      'driver.coaching.edit',
      'driver.coaching.complete',
      'report.view',
      'report.export',
      'ai.view',
    ],
    granularScope: {
      modules: ['command_center', 'dashboard', 'vehicle', 'driver', 'tracking', 'trip', 'safety', 'inspection', 'alert', 'fuel', 'report', 'ai'],
      allowedMenus: ['menu_command_center', 'menu_live_tracking', 'menu_fleet_vehicles', 'menu_drivers', 'menu_trips_dispatch', 'menu_safety_fatigue', 'menu_inspection', 'menu_fuel', 'menu_reports'],
      allowedActions: ['view', 'create', 'edit', 'export', 'approve'],
      vehicleScope: 'BRANCH_ONLY',
      branchScope: 'ASSIGNED_BRANCHES',
      departmentScope: 'DEPT_OPERATIONS',
      regionScope: 'ASSIGNED_REGIONS',
    },
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'driver',
    name: 'Driver (Pengemudi)',
    description: 'Akses self-service untuk pengemudi: menerima penugasan perjalanan, input checklist inspeksi unit, catat BBM, dan lihat skor perilaku berkendara.',
    scope: 'SELF',
    isSystem: true,
    isActive: true,
    usersCount: 145,
    permissions: [
      'dashboard.view',
      'vehicle.view',
      'driver.view',
      'tracking.view',
      'trip.view',
      'trip.edit',
      'fuel.view',
      'fuel.create',
      'inspection.view',
      'inspection.create',
      'safety.view',
      'document.view',
      'alert.view',
      'ai.view',
      'ai.chat',
      'ai.tool.read',
    ],
    granularScope: {
      modules: ['dashboard', 'vehicle', 'driver', 'tracking', 'trip', 'fuel', 'inspection', 'safety', 'document', 'alert', 'ai'],
      allowedMenus: ['menu_command_center', 'menu_fleet_vehicles', 'menu_trips_dispatch', 'menu_inspection', 'menu_fuel', 'menu_safety_fatigue', 'menu_ai_copilot'],
      allowedActions: ['view', 'create', 'edit'],
      vehicleScope: 'ASSIGNED_ONLY',
      branchScope: 'ASSIGNED_BRANCHES',
      departmentScope: 'DEPT_OPERATIONS',
      regionScope: 'ASSIGNED_REGIONS',
    },
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'maintenance',
    name: 'Maintenance (Teknisi Bengkel)',
    description: 'Tim teknisi pemeliharaan armada yang mengelola Work Order perbaikan, servis berkala, riwayat suku cadang, dan approval estimasi bengkel.',
    scope: 'BRANCH',
    isSystem: true,
    isActive: true,
    usersCount: 14,
    permissions: [
      'dashboard.view',
      'vehicle.view',
      'vehicle.edit',
      'maintenance.view',
      'maintenance.create',
      'maintenance.edit',
      'maintenance.export',
      'maintenance.approve',
      'inspection.view',
      'inspection.edit',
      'document.view',
      'document.create',
      'report.view',
      'report.export',
      'ai.view',
      'ai.chat',
      'ai.recommend',
      'ai.tool.read',
      'ai.tool.action',
    ],
    granularScope: {
      modules: ['dashboard', 'vehicle', 'maintenance', 'inspection', 'document', 'report', 'ai'],
      allowedMenus: ['menu_fleet_vehicles', 'menu_maintenance', 'menu_inspection', 'menu_documents', 'menu_reports', 'menu_ai_copilot'],
      allowedActions: ['view', 'create', 'edit', 'export', 'approve'],
      vehicleScope: 'BRANCH_ONLY',
      branchScope: 'ASSIGNED_BRANCHES',
      departmentScope: 'DEPT_MAINTENANCE_WORKSHOP',
      regionScope: 'ASSIGNED_REGIONS',
    },
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'finance',
    name: 'Finance (Keuangan)',
    description: 'Pengelola anggaran keuangan armada, verifikasi klaim BBM/SPBU, biaya servis, biaya tol, Total Cost of Ownership (TCO), dan audit billing.',
    scope: 'COMPANY',
    isSystem: true,
    isActive: true,
    usersCount: 6,
    permissions: [
      'dashboard.view',
      'vehicle.view',
      'driver.view',
      'fuel.view',
      'fuel.export',
      'maintenance.view',
      'finance.view',
      'finance.create',
      'finance.edit',
      'finance.export',
      'finance.approve',
      'cost.view',
      'cost.create',
      'cost.edit',
      'cost.delete',
      'cost.export',
      'cost.approve',
      'cost.allocate',
      'cost.audit',
      'report.view',
      'report.export',
      'analytics.view',
      'billing.view',
      'ai.view',
      'ai.chat',
      'ai.analyze',
      'ai.recommend',
      'ai.tool.read',
    ],
    granularScope: {
      modules: ['dashboard', 'vehicle', 'driver', 'fuel', 'maintenance', 'finance', 'report', 'analytics', 'subscription', 'ai'],
      allowedMenus: ['menu_command_center', 'menu_fleet_vehicles', 'menu_fuel', 'menu_maintenance', 'menu_cost_analytics', 'menu_reports', 'menu_analytics', 'menu_subscription', 'menu_ai_copilot'],
      allowedActions: ['view', 'create', 'edit', 'delete', 'export', 'approve'],
      vehicleScope: 'ALL',
      branchScope: 'ALL',
      departmentScope: 'DEPT_FINANCE_ACCOUNTING',
      regionScope: 'ALL',
    },
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'hr',
    name: 'HR (Human Resources)',
    description: 'Pengelola kepatuhan data pengemudi dan personel, sertifikasi SIM BII Umum, K3, riwayat pelanggaran/coaching, rekrutmen, dan dokumen legalitas.',
    scope: 'COMPANY',
    isSystem: true,
    isActive: true,
    usersCount: 4,
    permissions: [
      'dashboard.view',
      'driver.view',
      'driver.create',
      'driver.edit',
      'driver.export',
      'driver.intelligence.view',
      'driver.coaching.view',
      'driver.coaching.create',
      'driver.coaching.export',
      'safety.view',
      'document.view',
      'document.create',
      'document.edit',
      'document.verify',
      'document.export',
      'hr.view',
      'hr.create',
      'hr.edit',
      'hr.export',
      'hr.approve',
      'report.view',
      'report.export',
      'user.view',
    ],
    granularScope: {
      modules: ['dashboard', 'driver', 'safety', 'document', 'hr', 'report', 'user'],
      allowedMenus: ['menu_drivers', 'menu_safety_fatigue', 'menu_documents', 'menu_reports', 'menu_users_roles'],
      allowedActions: ['view', 'create', 'edit', 'export', 'approve'],
      vehicleScope: 'ALL',
      branchScope: 'ALL',
      departmentScope: 'DEPT_HR_PEOPLE',
      regionScope: 'ALL',
    },
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'viewer',
    name: 'Viewer (Hanya Baca)',
    description: 'Akses pengawasan khusus membaca seluruh data armada, status perjalanan real-time, dan laporan tanpa hak untuk menambah atau mengedit.',
    scope: 'COMPANY',
    isSystem: true,
    isActive: true,
    usersCount: 9,
    permissions: [
      'dashboard.view',
      'fleet.view',
      'vehicle.view',
      'driver.view',
      'gps_device.view',
      'tracking.view',
      'trip.view',
      'geofence.view',
      'alert.view',
      'safety.view',
      'fuel.view',
      'maintenance.view',
      'finance.view',
      'cost.view',
      'report.view',
      'analytics.view',
      'ai.view',
      'ai.tool.read',
    ],
    granularScope: {
      modules: ['dashboard', 'fleet', 'vehicle', 'driver', 'gps_device', 'tracking', 'trip', 'geofence', 'alert', 'safety', 'fuel', 'maintenance', 'finance', 'report', 'analytics', 'ai'],
      allowedMenus: ['menu_command_center', 'menu_executive_dashboard', 'menu_live_tracking', 'menu_fleet_vehicles', 'menu_drivers', 'menu_trips_dispatch', 'menu_routes', 'menu_geofence', 'menu_fuel', 'menu_maintenance', 'menu_safety_fatigue', 'menu_reports', 'menu_analytics'],
      allowedActions: ['view'],
      vehicleScope: 'ALL',
      branchScope: 'ALL',
      departmentScope: 'ALL',
      regionScope: 'ALL',
    },
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
];
