/**
 * Fleet Intelligence Smart AI - Centralized Dynamic Navigation Configuration
 * Enforces RBAC permissions across all navigation items
 */

import { ActiveView } from '../context/FleetContext';
import { 
  LayoutDashboard, 
  MapPin, 
  Truck, 
  FolderTree,
  Building2,
  Briefcase,
  Users, 
  Navigation, 
  Map, 
  Fuel, 
  Wrench, 
  ShieldAlert, 
  Bell, 
  Sparkles, 
  BarChart3, 
  FileText, 
  Settings,
  FolderCheck,
  UserCheck,
  Radio,
  Server,
  ShieldCheck,
  Cpu,
  Activity,
  CreditCard,
  Network,
  DownloadCloud,
  LucideIcon,
  Route,
  Waypoints,
  PackageCheck,
  ClipboardCheck,
  Brain,
  Zap,
  Workflow,
  Layers,
  ListChecks,
  AlertTriangle,
  Sliders,
  DollarSign,
  Crown,
  Code2,
  Smartphone,
  Radar,
  Shield,
  FileSpreadsheet,
  Lock,
  Car,
  KeyRound,
  Calendar,
  Receipt,
  TrendingUp,
  Boxes,
  Package,
  Shuffle,
  RotateCcw,
  AlertOctagon,
  ArrowUpRight,
  QrCode,
  Target,
  Bus,
  CalendarClock,
  Ticket,
  Store,
  Compass,
  HardHat,
  Clock,
  RotateCw,
  Scale,
  Tag,
  Pickaxe,
  Share2,
  FileCheck2,
  Bike,
  Disc,
  PackageSearch,
  Flame,
  Droplets,
  Trash2,
  ThermometerSnowflake,
  Video,
  CalendarCheck,
  Key,
  FileCheck
} from 'lucide-react';

export interface NavItemConfig {
  id: ActiveView;
  label: string;
  icon: LucideIcon;
  permission: string; // Permission key required to view item e.g. "vehicle.view"
  badgeType?: 'moving' | 'overdue_maintenance' | 'unread_alerts';
}

export interface NavGroupConfig {
  title?: string;
  items: NavItemConfig[];
}

export const NAVIGATION_CONFIG: NavGroupConfig[] = [
  {
    items: [
      { id: 'dashboard', label: 'Dashboard Utama', icon: LayoutDashboard, permission: 'dashboard.view' },
      { id: 'executive_dashboard', label: 'Executive Dashboard (Direksi)', icon: Crown, permission: 'executive.dashboard.view' },
      { id: 'executive_report', label: 'Laporan Eksekutif C-Level (AI)', icon: FileSpreadsheet, permission: 'executive.dashboard.view' },
    ],
  },
  {
    title: 'OPERATIONS',
    items: [
      { id: 'command_center', label: 'Command Center (Control Room)', icon: Radar, permission: 'command_center.view', badgeType: 'unread_alerts' },
      { id: 'driver_mobile', label: 'Driver Mobile App', icon: Smartphone, permission: 'trip.view', badgeType: 'moving' },
      { id: 'live_tracking', label: 'Live GPS Tracking', icon: MapPin, permission: 'tracking.view', badgeType: 'moving' },
      { id: 'inspection', label: 'Vehicle Inspection (Pre-Trip)', icon: ClipboardCheck, permission: 'inspection.view' },
      { id: 'planned_trips', label: 'Trip Management', icon: Navigation, permission: 'trip.view' },
      { id: 'deliveries', label: 'Delivery & POD', icon: PackageCheck, permission: 'trip.view' },
      { id: 'routes', label: 'Route Management', icon: Waypoints, permission: 'route.view' },
      { id: 'geofence', label: 'Geofencing', icon: Map, permission: 'geofence.view' },
      { id: 'trips', label: 'Trip History', icon: Route, permission: 'trip.view' },
    ],
  },
  {
    title: 'RENT CAR MANAGEMENT',
    items: [
      { id: 'rent_car', label: 'Armada & GPS Live', icon: Car, permission: 'vehicle.view' },
      { id: 'rent_car_bookings', label: 'Reservasi & Sewa', icon: KeyRound, permission: 'vehicle.view' },
      { id: 'rent_car_contracts', label: 'Kontrak Digital', icon: FileText, permission: 'vehicle.view' },
      { id: 'rent_car_calendar', label: 'Kalender Sewa', icon: Calendar, permission: 'vehicle.view' },
      { id: 'rent_car_customers', label: 'Pelanggan & AI KYC', icon: ShieldCheck, permission: 'vehicle.view' },
      { id: 'rent_car_damages', label: 'Klaim & Kerusakan', icon: Wrench, permission: 'vehicle.view' },
      { id: 'rent_car_invoices', label: 'Faktur & Piutang', icon: Receipt, permission: 'vehicle.view' },
      { id: 'rent_car_security', label: 'Anti-Theft & Geofence', icon: ShieldAlert, permission: 'vehicle.view' },
      { id: 'rent_car_tariffs', label: 'Tarif & Deposit', icon: DollarSign, permission: 'vehicle.view' },
      { id: 'rent_car_analytics', label: 'Analitik Laba Rugi', icon: TrendingUp, permission: 'vehicle.view' },
      { id: 'rent_car_ai', label: 'AI Copilot & Radar', icon: Brain, permission: 'vehicle.view' },
      { id: 'rent_car_reports', label: 'Pusat Laporan Rental', icon: FileSpreadsheet, permission: 'vehicle.view' },
    ],
  },
  {
    title: 'LOGISTICS MANAGEMENT SYSTEM',
    items: [
      { id: 'logistics_control_tower', label: 'Menara Kendali (Tower)', icon: Target, permission: 'trip.view' },
      { id: 'logistics_orders', label: 'Order Pengiriman (TMS)', icon: Package, permission: 'trip.view' },
      { id: 'logistics_shipments', label: 'Surat Jalan & Connote', icon: FileText, permission: 'trip.view' },
      { id: 'logistics_pickups', label: 'Pickup & First-Mile', icon: ArrowUpRight, permission: 'trip.view' },
      { id: 'logistics_deliveries', label: 'Last-Mile & ePOD', icon: PackageCheck, permission: 'trip.view' },
      { id: 'logistics_manifests', label: 'Manifest & Konsolidasi', icon: Boxes, permission: 'trip.view' },
      { id: 'logistics_packages', label: 'Barcode Scanner & Koli', icon: QrCode, permission: 'trip.view' },
      { id: 'logistics_routes', label: 'Perencanaan Rute VRP', icon: Waypoints, permission: 'route.view' },
      { id: 'logistics_live_tracking', label: 'Live GPS Kargo Linehaul', icon: MapPin, permission: 'tracking.view', badgeType: 'moving' },
      { id: 'logistics_hubs', label: 'Hub & Transit Depo', icon: Building2, permission: 'vehicle.view' },
      { id: 'logistics_sortation', label: 'Sortation Center & Line', icon: Shuffle, permission: 'trip.view' },
      { id: 'logistics_returns', label: 'Retur Pengirim (RTS)', icon: RotateCcw, permission: 'trip.view' },
      { id: 'logistics_exceptions', label: 'Kendala & Tiket Insiden', icon: AlertOctagon, permission: 'alert.view', badgeType: 'unread_alerts' },
      { id: 'logistics_cod', label: 'COD & Rekonsiliasi Kas', icon: DollarSign, permission: 'cost.view' },
      { id: 'logistics_customers', label: 'Merchant B2B & CRM', icon: Building2, permission: 'driver.view' },
      { id: 'logistics_sla', label: 'Radar Kepatuhan SLA', icon: ShieldCheck, permission: 'analytics.view' },
      { id: 'logistics_analytics', label: 'Analitik Biaya Tonase', icon: BarChart3, permission: 'cost.view' },
      { id: 'logistics_ai', label: 'AI Logistics Copilot', icon: Sparkles, permission: 'ai.view' },
      { id: 'logistics_reports', label: 'Pusat Laporan Logistik', icon: FileSpreadsheet, permission: 'report.view' },
    ],
  },
  {
    title: 'BUS MANAGEMENT SYSTEM (PO BUS)',
    items: [
      { id: 'bus_control_tower', label: 'Menara Kendali PO Bus', icon: Target, permission: 'trip.view' },
      { id: 'bus_trips_schedule', label: 'Jadwal & Ritase Trayek', icon: CalendarClock, permission: 'trip.view' },
      { id: 'bus_ticketing_seat', label: 'Reservasi & Denah Kursi', icon: Ticket, permission: 'trip.view' },
      { id: 'bus_passenger_manifest', label: 'Manifest & E-Boarding', icon: Users, permission: 'trip.view' },
      { id: 'bus_routes_terminals', label: 'Trayek & Rest Area Tol', icon: Waypoints, permission: 'route.view' },
      { id: 'bus_cargo_express', label: 'Kargo Paket Bus (Express)', icon: Package, permission: 'trip.view' },
      { id: 'bus_agents_counter', label: 'Loket Agen & Terminal', icon: Store, permission: 'trip.view' },
      { id: 'bus_crew_roster', label: 'Kru & Roster Supir (Fatigue)', icon: UserCheck, permission: 'driver.view' },
      { id: 'bus_ramp_check', label: 'Ramp Check Kemenhub', icon: ShieldCheck, permission: 'inspection.view' },
      { id: 'bus_ujs_toll_fuel', label: 'UJS, Solar & E-Toll', icon: DollarSign, permission: 'cost.view' },
      { id: 'bus_live_tracking', label: 'Live GPS Telematika Bus', icon: Radio, permission: 'tracking.view', badgeType: 'moving' },
      { id: 'bus_charter_tour', label: 'Sewa Bus Pariwisata', icon: Compass, permission: 'trip.view' },
      { id: 'bus_occupancy_analytics', label: 'Analitik Okupansi & RASK', icon: TrendingUp, permission: 'analytics.view' },
      { id: 'bus_ai_dispatcher', label: 'AI PO Bus Copilot', icon: Sparkles, permission: 'ai.view' },
      { id: 'bus_reports', label: 'Pusat Laporan PO Bus', icon: FileSpreadsheet, permission: 'report.view' },
    ],
  },
  {
    title: 'CONSTRUCTION & HEAVY EQUIPMENT',
    items: [
      { id: 'heavy_equipment_control_tower', label: 'Menara Kendali Alat Berat', icon: Target, permission: 'trip.view' },
      { id: 'heavy_equipment_assets', label: 'Master Alat Berat & SILO', icon: Truck, permission: 'vehicle.view' },
      { id: 'heavy_equipment_projects', label: 'Job Site & Volume BCM', icon: Layers, permission: 'trip.view' },
      { id: 'heavy_equipment_timesheets', label: 'Daily Timesheet (HM)', icon: Clock, permission: 'trip.view' },
      { id: 'heavy_equipment_p2h', label: 'Checklist P2H K3 Harian', icon: ShieldCheck, permission: 'inspection.view' },
      { id: 'heavy_equipment_fuel', label: 'BBM Solar & Fuel Bowser', icon: Fuel, permission: 'fuel.view' },
      { id: 'heavy_equipment_maintenance', label: 'Servis Berkala PS 250-2000', icon: Wrench, permission: 'maintenance.view', badgeType: 'overdue_maintenance' },
      { id: 'heavy_equipment_safety', label: 'K3 Tambang & SIO Operator', icon: HardHat, permission: 'safety.view' },
      { id: 'heavy_equipment_billing', label: 'Sewa & Faktur Rental HM', icon: DollarSign, permission: 'cost.view' },
      { id: 'heavy_equipment_ai', label: 'AI Heavy Fleet Copilot', icon: Sparkles, permission: 'ai.view' },
      { id: 'heavy_equipment_reports', label: 'Pusat Laporan Alat Berat', icon: FileSpreadsheet, permission: 'report.view' },
    ],
  },
  {
    title: 'MINING FLEET & OPERATIONS',
    items: [
      { id: 'mining_control_tower', label: 'Menara Kendali Tambang (Control Tower)', icon: Target, permission: 'trip.view', badgeType: 'moving' },
      { id: 'mining_sites', label: 'Site Tambang & Konsesi IUP', icon: MapPin, permission: 'vehicle.view' },
      { id: 'mining_pits', label: 'Pit Tambang & Geofence (RL)', icon: Compass, permission: 'trip.view' },
      { id: 'mining_benches', label: 'Jenjang Kerja (Bench & Loading)', icon: Layers, permission: 'trip.view' },
      { id: 'mining_materials', label: 'Material & Grade (%Ni/GAR)', icon: Tag, permission: 'vehicle.view' },
      { id: 'mining_equipment', label: 'Armada Tambang & Shovel Excavator', icon: Truck, permission: 'vehicle.view' },
      { id: 'mining_operators', label: 'Operator KIMPER & SIO ESDM', icon: Users, permission: 'driver.view' },
      { id: 'mining_shifts', label: 'Shift Roster & P5M Meeting', icon: Clock, permission: 'trip.view' },
      { id: 'mining_dispatch', label: 'Dispatch & Siklus Hauling', icon: RotateCw, permission: 'trip.view', badgeType: 'moving' },
      { id: 'mining_weighbridge', label: 'Jembatan Timbang & Payload', icon: Scale, permission: 'trip.view' },
      { id: 'mining_fuel', label: 'BBM Solar B35 & Fuel Bowser', icon: Fuel, permission: 'fuel.view' },
      { id: 'mining_safety', label: 'K3 SMKP ESDM & Fatigue DSS', icon: ShieldCheck, permission: 'safety.view', badgeType: 'unread_alerts' },
      { id: 'mining_maintenance', label: 'Plant Maintenance & Ban OTR', icon: Wrench, permission: 'maintenance.view', badgeType: 'overdue_maintenance' },
      { id: 'mining_productivity', label: 'Produktivitas & P&L Unit', icon: TrendingUp, permission: 'cost.view' },
      { id: 'mining_ai', label: 'AI Mining Operations Copilot', icon: Sparkles, permission: 'ai.view' },
      { id: 'mining_reports', label: 'Pusat Laporan LHT & LBT', icon: FileSpreadsheet, permission: 'report.view' },
    ],
  },
  {
    title: 'PICKUP & DELIVERY SYSTEM (PUD)',
    items: [
      { id: 'pud_control_tower', label: 'Menara Kendali PUD (Control Tower)', icon: Target, permission: 'trip.view', badgeType: 'moving' },
      { id: 'pud_pickups', label: 'Permintaan Pickup (First-Mile)', icon: ArrowUpRight, permission: 'trip.view' },
      { id: 'pud_deliveries', label: 'Pengiriman Drop-off (Last-Mile)', icon: PackageCheck, permission: 'trip.view' },
      { id: 'pud_dispatch', label: 'Smart Dispatch & Alokasi Kurir', icon: Zap, permission: 'trip.view' },
      { id: 'pud_epod', label: 'Bukti Serah Terima (ePOD & ePOP)', icon: FileCheck2, permission: 'trip.view' },
      { id: 'pud_live_couriers', label: 'Live Tracking Kurir & Radar GPS', icon: Radio, permission: 'tracking.view', badgeType: 'moving' },
      { id: 'pud_route_optimizer', label: 'Optimasi Rute Multi-Stop (VRP)', icon: Waypoints, permission: 'route.view' },
      { id: 'pud_failed_undelivered', label: 'Kendala & Gagal Antar (NDR)', icon: AlertOctagon, permission: 'alert.view', badgeType: 'unread_alerts' },
      { id: 'pud_cod', label: 'COD & Rekonsiliasi Kas Kurir', icon: DollarSign, permission: 'cost.view' },
      { id: 'pud_tracking_link', label: 'Tautan Pelacakan & WhatsApp SMS', icon: Share2, permission: 'trip.view' },
      { id: 'pud_couriers', label: 'Roster Kurir & Kinerja Insentif', icon: Users, permission: 'driver.view' },
      { id: 'pud_tariffs', label: 'Tarif Zona & Kalkulator Ongkir', icon: Tag, permission: 'cost.view' },
      { id: 'pud_ai_copilot', label: 'AI PUD Operations Copilot', icon: Sparkles, permission: 'ai.view' },
      { id: 'pud_reports', label: 'Pusat Laporan & KPI PUD', icon: FileSpreadsheet, permission: 'report.view' },
    ],
  },
  {
    title: 'DUMP TRUCK MANAGEMENT (DTMS)',
    items: [
      { id: 'dtms_control_tower', label: 'Menara Kendali DTMS (Control Tower)', icon: Target, permission: 'trip.view', badgeType: 'moving' },
      { id: 'dtms_fleets', label: 'Armada & Spesifikasi Dump Truck', icon: Truck, permission: 'vehicle.view' },
      { id: 'dtms_cycles', label: 'Siklus Hauling & Cycle Time', icon: RotateCw, permission: 'trip.view', badgeType: 'moving' },
      { id: 'dtms_payload', label: 'Jembatan Timbang & Overload', icon: Scale, permission: 'trip.view' },
      { id: 'dtms_haul_roads', label: 'Haul Road & Kecepatan Segmen', icon: MapPin, permission: 'route.view' },
      { id: 'dtms_dispatch', label: 'Smart Dispatch & Match Factor', icon: Zap, permission: 'trip.view' },
      { id: 'dtms_fuel', label: 'Konsumsi Solar & Fuel Bowser', icon: Fuel, permission: 'fuel.view' },
      { id: 'dtms_tires', label: 'Ban OTR & TPMS Sensor (TKPH)', icon: Disc, permission: 'maintenance.view' },
      { id: 'dtms_telematics', label: 'Hoist Hidrolik & Sensor PTO', icon: Radio, permission: 'tracking.view' },
      { id: 'dtms_drivers', label: 'Operator KIMPER & Fatigue DSS', icon: Users, permission: 'driver.view', badgeType: 'unread_alerts' },
      { id: 'dtms_safety', label: 'K3 Tambang & Anti-Rollover', icon: ShieldCheck, permission: 'safety.view' },
      { id: 'dtms_maintenance', label: 'Perawatan PM & P2H Harian', icon: Wrench, permission: 'maintenance.view', badgeType: 'overdue_maintenance' },
      { id: 'dtms_billing', label: 'Tarif Hauling & P&L Ritase', icon: DollarSign, permission: 'cost.view' },
      { id: 'dtms_ai', label: 'AI DTMS Operations Copilot', icon: Sparkles, permission: 'ai.view' },
      { id: 'dtms_reports', label: 'Pusat Laporan LHT & LBT', icon: FileSpreadsheet, permission: 'report.view' },
    ],
  },
  {
    title: 'TAXI MANAGEMENT SYSTEM (TMS)',
    items: [
      { id: 'taxi_control_tower', label: 'Menara Kendali Taksi (Control Tower)', icon: Target, permission: 'trip.view', badgeType: 'moving' },
      { id: 'taxi_fleets', label: 'Master Armada Taksi (Sedan/MPV/EV)', icon: Car, permission: 'vehicle.view' },
      { id: 'taxi_taximeter', label: 'Argometer & Tarif SK Dishub', icon: DollarSign, permission: 'cost.view' },
      { id: 'taxi_orders', label: 'Smart Dispatching & On-Demand Order', icon: Navigation, permission: 'trip.view', badgeType: 'moving' },
      { id: 'taxi_revenue', label: 'Setoran Kasir Pool & Bagi Hasil', icon: Receipt, permission: 'cost.view' },
      { id: 'taxi_pools', label: 'Pool & Pangkalan Bandara FIFO', icon: MapPin, permission: 'trip.view' },
      { id: 'taxi_energy', label: 'BBM, SPBG & SPKLU EV Charging', icon: Fuel, permission: 'fuel.view' },
      { id: 'taxi_drivers', label: 'Pengemudi, KTA & Roster Shift', icon: Users, permission: 'driver.view' },
      { id: 'taxi_safety', label: 'Kamera MDVR, Panic SOS & Safety', icon: ShieldCheck, permission: 'safety.view', badgeType: 'unread_alerts' },
      { id: 'taxi_maintenance', label: 'Perawatan Bengkel & Uji Tera/KIR', icon: Wrench, permission: 'maintenance.view', badgeType: 'overdue_maintenance' },
      { id: 'taxi_lost_found', label: 'Lost & Found Penumpang', icon: PackageSearch, permission: 'trip.view' },
      { id: 'taxi_cashless', label: 'Pembayaran Non-Tunai QRIS & EDC', icon: CreditCard, permission: 'cost.view' },
      { id: 'taxi_ai_copilot', label: 'AI Taxi Demand & Dispatch Radar', icon: Sparkles, permission: 'ai.view' },
      { id: 'taxi_reports', label: 'Pusat Laporan LOH & Audit Utilisasi', icon: FileSpreadsheet, permission: 'report.view' },
    ],
  },
  {
    title: 'TANKER TRUCK MANAGEMENT SYSTEM (TTMS)',
    items: [
      { id: 'tanker_control_tower', label: 'Menara Kendali Tangki (Control Tower)', icon: Activity, permission: 'trip.view', badgeType: 'moving' },
      { id: 'tanker_fleets', label: 'Master Armada Tangki & Bejana', icon: Truck, permission: 'vehicle.view' },
      { id: 'tanker_compartments', label: 'Sensor Kompartemen & Susut (Losses)', icon: Layers, permission: 'vehicle.view' },
      { id: 'tanker_elocks', label: 'Smart E-Lock & Segel Elektronik', icon: Lock, permission: 'safety.view', badgeType: 'unread_alerts' },
      { id: 'tanker_loading_orders', label: 'Order DO & Gantry Loading Meter', icon: FileText, permission: 'trip.view', badgeType: 'moving' },
      { id: 'tanker_unloading', label: 'Bongkar Muatan & Flowmeter SPBU', icon: DownloadCloud, permission: 'trip.view' },
      { id: 'tanker_geofences', label: 'Koridor Jalur & Zona Merah (Red Zone)', icon: ShieldAlert, permission: 'safety.view' },
      { id: 'tanker_safety_hazmat', label: 'Keselamatan B3, MSDS & Anti-Rollover', icon: Flame, permission: 'safety.view', badgeType: 'unread_alerts' },
      { id: 'tanker_cleaning', label: 'Pencucian Tangki, CIP & Degassing', icon: Sparkles, permission: 'maintenance.view' },
      { id: 'tanker_drivers', label: 'Pengemudi B3 & Roster Kelelahan', icon: Users, permission: 'driver.view' },
      { id: 'tanker_maintenance', label: 'Perawatan, Hydrotest & Tera Legal', icon: Wrench, permission: 'maintenance.view', badgeType: 'overdue_maintenance' },
      { id: 'tanker_billing', label: 'Tarif Angkutan & Klaim Susut', icon: DollarSign, permission: 'cost.view' },
      { id: 'tanker_ai_copilot', label: 'AI Tanker Safety & Loss Copilot', icon: Sparkles, permission: 'ai.view' },
      { id: 'tanker_reports', label: 'Pusat Laporan Audit & Rekap Losses', icon: FileSpreadsheet, permission: 'report.view' },
    ],
  },
  {
    title: 'WASTE TRANSPORT FLEET MANAGEMENT SYSTEM',
    items: [
      { id: 'waste_control_tower', label: 'Menara Kendali Angkutan Sampah', icon: Target, permission: 'trip.view', badgeType: 'moving' },
      { id: 'waste_fleets', label: 'Master Armada Pengangkut Limbah', icon: Truck, permission: 'vehicle.view' },
      { id: 'waste_routes', label: 'Jadwal & Rute Pengumpulan TPS', icon: MapPin, permission: 'route.view', badgeType: 'moving' },
      { id: 'waste_manifest_festronik', label: 'Manifest Elektronik Festronik B3', icon: FileCheck2, permission: 'trip.view' },
      { id: 'waste_weighbridge', label: 'Jembatan Timbang & Tipping TPA', icon: Scale, permission: 'trip.view' },
      { id: 'waste_containers', label: 'Sensor Smart Bin & RFID Tracking', icon: Radio, permission: 'vehicle.view' },
      { id: 'waste_medical_biohazard', label: 'Limbah Medis Cold Box Biohazard', icon: ThermometerSnowflake, permission: 'safety.view', badgeType: 'unread_alerts' },
      { id: 'waste_sludge_vacuum', label: 'Armada Vacuum & Sedot Tinja/IPAL', icon: Droplets, permission: 'trip.view' },
      { id: 'waste_safety_compliance', label: 'K3 Lingkungan, APD & Spill Kit', icon: ShieldCheck, permission: 'safety.view' },
      { id: 'waste_crews', label: 'Kinerja Petugas & Insentif Ritase', icon: Users, permission: 'driver.view' },
      { id: 'waste_maintenance', label: 'Perawatan Hidrolik & Disinfeksi', icon: Wrench, permission: 'maintenance.view', badgeType: 'overdue_maintenance' },
      { id: 'waste_billing', label: 'Tarif Retribusi & Billing Invoicing', icon: DollarSign, permission: 'cost.view' },
      { id: 'waste_ai_copilot', label: 'AI Waste Operations Copilot', icon: Sparkles, permission: 'ai.view' },
      { id: 'waste_reports', label: 'Pusat Laporan & Neraca B3 KLHK', icon: FileSpreadsheet, permission: 'report.view' },
    ],
  },
  {
    title: 'SECURICOR & SECURITY FLEET MANAGEMENT SYSTEM',
    items: [
      { id: 'securicor_control_tower', label: 'Menara Kendali Lapis Baja (CIT Control Tower)', icon: ShieldAlert, permission: 'trip.view', badgeType: 'moving' },
      { id: 'securicor_armored_fleets', label: 'Master Armada Lapis Baja (B6/B7 Ballistic)', icon: Shield, permission: 'vehicle.view' },
      { id: 'securicor_cit_missions', label: 'Manifest Misi Cash-in-Transit (CIT)', icon: FileText, permission: 'trip.view', badgeType: 'moving' },
      { id: 'securicor_smart_vault', label: 'Khazanah Brankas & Kaset Smart Dye/Smoke', icon: Lock, permission: 'trip.view' },
      { id: 'securicor_atm_replenishment', label: 'Pengisian Kas ATM & First Line Maint (FLM)', icon: CreditCard, permission: 'trip.view' },
      { id: 'securicor_patrol_guards', label: 'Patroli Pengamanan & Live Bodycam', icon: Video, permission: 'safety.view' },
      { id: 'securicor_duress_emergency', label: 'Pusat Alarm Duress, SOS & Anti-Hijack', icon: Radio, permission: 'safety.view', badgeType: 'unread_alerts' },
      { id: 'securicor_armed_officers', label: 'Pengawal Bersenjata & Izin Senpi (IKH)', icon: UserCheck, permission: 'driver.view' },
      { id: 'securicor_geofence_corridors', label: 'Koridor Hijau Rute & No-Stop Zone', icon: Navigation, permission: 'route.view' },
      { id: 'securicor_armor_maintenance', label: 'Perawatan Balistik & Solenoid Kunci', icon: Wrench, permission: 'maintenance.view', badgeType: 'overdue_maintenance' },
      { id: 'securicor_insurance_billing', label: 'Asuransi Kas CIT & Tarif Penagihan Bank', icon: DollarSign, permission: 'cost.view' },
      { id: 'securicor_ai_copilot', label: 'AI Securicor Tactical Threat Copilot', icon: Sparkles, permission: 'ai.view' },
      { id: 'securicor_reports', label: 'Pusat Laporan Audit Bank Indonesia (PUPR)', icon: FileSpreadsheet, permission: 'report.view' },
    ],
  },
  {
    title: 'CORPORATE COMPANY VEHICLE MANAGEMENT SYSTEM',
    items: [
      { id: 'corp_control_tower', label: 'Menara Kendali Pool Mobil (GA Control Tower)', icon: Building2, permission: 'trip.view', badgeType: 'moving' },
      { id: 'corp_vehicles', label: 'Master Kendaraan, Pool & Mobil Jabatan', icon: Car, permission: 'vehicle.view' },
      { id: 'corp_bookings', label: 'Pemesanan & Reservasi E-Booking Dinas', icon: CalendarCheck, permission: 'trip.view', badgeType: 'moving' },
      { id: 'corp_keybox', label: 'Smart Keybox Locker B1 & Virtual Key', icon: Key, permission: 'trip.view' },
      { id: 'corp_inspections', label: 'Inspeksi Pra/Pasca & Checklist Baret', icon: ClipboardCheck, permission: 'safety.view' },
      { id: 'corp_drivers', label: 'Supir Pool Kantor & Chauffeur VIP', icon: Users, permission: 'driver.view' },
      { id: 'corp_fuel_toll', label: 'Kartu BBM Korporat, E-Toll & Kasbon', icon: Fuel, permission: 'cost.view' },
      { id: 'corp_policy_compliance', label: 'Car Policy, Jam Malam & Geofence', icon: ShieldAlert, permission: 'safety.view', badgeType: 'unread_alerts' },
      { id: 'corp_compliance_lease', label: 'Kontrak Sewa Vendor (TRAC/MPM) & STNK', icon: FileCheck, permission: 'cost.view' },
      { id: 'corp_maintenance', label: 'Servis Berkala & Bengkel Dealer', icon: Wrench, permission: 'maintenance.view', badgeType: 'overdue_maintenance' },
      { id: 'corp_cost_centers', label: 'Alokasi Beban Cost Center Divisi', icon: DollarSign, permission: 'cost.view' },
      { id: 'corp_ai_copilot', label: 'AI Corporate Fleet Optimizer Copilot', icon: Sparkles, permission: 'ai.view' },
      { id: 'corp_reports', label: 'Laporan Eksekutif, TCO & ESG Green Fleet', icon: FileSpreadsheet, permission: 'report.view' },
    ],
  },
  {
    title: 'ARMADA & MASTER DATA',
    items: [
      { id: 'vehicles', label: 'Kendaraan & Master GPS', icon: Truck, permission: 'vehicle.view' },
      { id: 'vehicle_groups', label: 'Grup Kendaraan', icon: FolderTree, permission: 'vehicle.view' },
      { id: 'branches', label: 'Cabang & Depo', icon: Building2, permission: 'vehicle.view' },
      { id: 'departments', label: 'Departemen', icon: Briefcase, permission: 'vehicle.view' },
      { id: 'drivers', label: 'Pengemudi (Drivers)', icon: Users, permission: 'driver.view' },
    ],
  },
  {
    title: 'ORGANISASI & MULTI-TENANT',
    items: [
      { id: 'organizations', label: 'Struktur Organisasi & Tree', icon: Layers, permission: 'settings.view' },
      { id: 'tenants', label: 'Perusahaan SaaS (Tenants)', icon: Building2, permission: 'settings.view' },
      { id: 'fleets', label: 'Sub-Grup Armada (Fleets)', icon: Truck, permission: 'vehicle.view' },
      { id: 'security_isolation', label: 'Security & Isolation Lab', icon: ShieldCheck, permission: 'settings.view' },
    ],
  },
  {
    title: 'GPS & DEVICE MANAGEMENT',
    items: [
      { id: 'gps_devices', label: 'GPS Devices', icon: Cpu, permission: 'gps.device.view' },
      { id: 'gps_integration', label: 'Protocol Abstraction', icon: Network, permission: 'gps.protocol.view' },
      { id: 'gps_health', label: 'Device Health', icon: Activity, permission: 'gps.device.view' },
      { id: 'gps_sims', label: 'SIM Cards', icon: CreditCard, permission: 'gps.sim.view' },
      { id: 'gps_protocols', label: 'Protocols', icon: Network, permission: 'gps.protocol.view' },
      { id: 'gps_firmware', label: 'Firmware', icon: DownloadCloud, permission: 'gps.firmware.view' },
    ],
  },
  {
    title: 'TELEMATIKA & EFISIENSI',
    items: [
      { id: 'fuel', label: 'Monitoring BBM', icon: Fuel, permission: 'fuel.view' },
      { id: 'maintenance', label: 'Pemeliharaan (WO)', icon: Wrench, permission: 'maintenance.view', badgeType: 'overdue_maintenance' },
      { id: 'cost_analytics', label: 'Analisis Biaya & TOC/TCO', icon: DollarSign, permission: 'cost.view' },
      { id: 'safety', label: 'Keselamatan (Safety)', icon: ShieldAlert, permission: 'safety.view' },
      { id: 'fatigue', label: 'Manajemen Kelelahan', icon: Activity, permission: 'safety.view' },
      { id: 'alerts', label: 'Peringatan System', icon: Bell, permission: 'alert.view', badgeType: 'unread_alerts' },
    ],
  },
  {
    title: 'INTELLIGENCE & LAPORAN',
    items: [
      { id: 'daily_briefing', label: 'AI Fleet Daily Briefing', icon: Sparkles, permission: 'ai.view' },
      { id: 'fleet_assistant', label: 'AI Fleet Assistant', icon: Sparkles, permission: 'ai.view' },
      { id: 'route_intelligence', label: 'AI Route & ETA Intelligence', icon: Navigation, permission: 'ai.view' },
      { id: 'fleet_intelligence', label: 'AI Fleet Intelligence', icon: Brain, permission: 'ai.view' },
      { id: 'driver_intelligence', label: 'AI Driver Intelligence', icon: UserCheck, permission: 'driver.intelligence.view' },
      { id: 'fuel_intelligence', label: 'AI Fuel Intelligence', icon: Fuel, permission: 'fuel.view' },
      { id: 'maintenance_intelligence', label: 'AI Predictive Maintenance', icon: Wrench, permission: 'maintenance.view' },
      { id: 'safety_intelligence', label: 'AI Safety Intelligence', icon: ShieldCheck, permission: 'safety.view' },
      { id: 'ai_intelligence', label: 'AI Copilot & Hub', icon: Sparkles, permission: 'ai.view' },
      { id: 'analytics', label: 'Analitik & KPI', icon: BarChart3, permission: 'analytics.view' },
      { id: 'reports', label: 'Laporan Otomatis', icon: FileText, permission: 'report.view' },
      { id: 'documents', label: 'Dokumen & Legalitas AI', icon: FolderCheck, permission: 'document.view' },
    ],
  },
  {
    title: 'AI AUTOMATION ENGINE',
    items: [
      { id: 'automation', label: 'Automation Dashboard', icon: Zap, permission: 'automation.view' },
      { id: 'automation_workflows', label: 'Workflows', icon: Workflow, permission: 'automation.view' },
      { id: 'automation_templates', label: 'Templates', icon: Layers, permission: 'automation.view' },
      { id: 'automation_logs', label: 'Execution Logs', icon: ListChecks, permission: 'automation.view' },
      { id: 'automation_failed', label: 'Failed Automations', icon: AlertTriangle, permission: 'automation.view' },
      { id: 'automation_settings', label: 'Settings', icon: Sliders, permission: 'automation.view' },
    ],
  },
  {
    title: 'PENGATURAN & OTORISASI',
    items: [
      { id: 'users', label: 'Pengguna & Role', icon: UserCheck, permission: 'user.view' },
      { id: 'roles_permissions', label: 'Matriks Role & RBAC', icon: ShieldCheck, permission: 'role.view' },
      { id: 'enterprise_security', label: 'Enterprise Security Center', icon: Lock, permission: 'security.view' },
      { id: 'audit', label: 'Audit Trail & Activity Log', icon: Shield, permission: 'audit.view' },
      { id: 'subscription', label: 'Langganan & Billing', icon: CreditCard, permission: 'billing.view' },
      { id: 'developer_portal', label: 'Developer API & Webhooks', icon: Code2, permission: 'settings.view' },
      { id: 'gps_server', label: 'GPS Server & Supabase', icon: Server, permission: 'integration.view' },
      { id: 'integrations', label: 'Gateway GPS IoT', icon: Radio, permission: 'integration.view' },
      { id: 'settings', label: 'Pengaturan Tenant', icon: Settings, permission: 'settings.view' },
    ],
  },
  {
    title: 'SUPER ADMIN ROOT',
    items: [
      { id: 'super_admin', label: 'Super Admin Control Center', icon: ShieldAlert, permission: 'admin.company.manage' },
    ],
  },
];
