/**
 * Fleet Intelligence Smart AI - Centralized Route & Page Metadata Configuration
 * Used by Breadcrumb, PageHeader, Document Title, and RBAC Permission Guards
 */

import { ActiveView } from '../context/FleetContext';

export interface RouteMetadata {
  id: ActiveView;
  title: string;
  description: string;
  breadcrumb: string[];
  permission: string;
  path: string;
}

export const ROUTE_METADATA_MAP: Record<ActiveView, RouteMetadata> = {
  command_center: {
    id: 'command_center',
    title: 'Command Center & Control Room',
    description: 'Pusat komando operasional telematika armada 24/7: Pemantauan darurat SOS, mitigasi risiko realtime, peta live telemetri, dan rekomendasi dispatch AI.',
    breadcrumb: ['Operations', 'Command Center'],
    permission: 'command_center.view',
    path: '/app/command-center',
  },
  executive_dashboard: {
    id: 'executive_dashboard',
    title: 'Executive Dashboard (Direksi & Owner)',
    description: 'Fleet business overview and AI-powered decision intelligence (See → Understand → Decide → Act).',
    breadcrumb: ['Executive', 'Dashboard Direksi'],
    permission: 'executive.dashboard.view',
    path: '/executive',
  },
  executive_report: {
    id: 'executive_report',
    title: 'Laporan Intelijen Eksekutif C-Level & Board',
    description: 'Laporan komprehensif berkala (MTD/QTD/YTD), audit telematika zero-hallucination, analisa 5-Why, proyeksi prediktif, dan papan persetujuan keputusan direksi.',
    breadcrumb: ['Executive', 'Laporan Eksekutif C-Level'],
    permission: 'executive.dashboard.view',
    path: '/executive/report',
  },
  executive_print: {
    id: 'executive_print',
    title: 'Executive Report Print Preview',
    description: 'Format cetak resmi laporan eksekutif armada untuk C-Level & Board of Directors.',
    breadcrumb: ['Executive', 'Print Report'],
    permission: 'executive.dashboard.export',
    path: '/executive/print',
  },
  dashboard: {
    id: 'dashboard',
    title: 'Dashboard Utama Operasional',
    description: 'Ringkasan performa armada, status telemetri GPS live, dan matriks kesehatan operasional.',
    breadcrumb: ['Overview', 'Dashboard Utama'],
    permission: 'dashboard.view',
    path: '/app/dashboard',
  },
  live_tracking: {
    id: 'live_tracking',
    title: 'Live GPS Tracking & Telematika',
    description: 'Pemantauan lokasi kendaraan real-time, status mesin, kecepatan, dan pemutaran ulang rute (Route Playback).',
    breadcrumb: ['Operations', 'Live Tracking'],
    permission: 'tracking.view',
    path: '/app/tracking',
  },
  inspection: {
    id: 'inspection',
    title: 'Vehicle Inspection & Smart Pre-Trip',
    description: 'Pemeriksaan pra-keberangkatan digital, kepatuhan K3, audit kondisi fisik armada, dan auto-grounding.',
    breadcrumb: ['Operations', 'Inspeksi & Pre-Trip'],
    permission: 'inspection.view',
    path: '/app/inspection',
  },
  vehicles: {
    id: 'vehicles',
    title: 'Manajemen Kendaraan & Master Aset',
    description: 'Inventarisasi unit kendaraan, sensor IoT telematika, odometer, dan alokasi cabang.',
    breadcrumb: ['Fleet', 'Kendaraan Master'],
    permission: 'vehicle.view',
    path: '/app/fleet/vehicles',
  },
  vehicle_groups: {
    id: 'vehicle_groups',
    title: 'Grup Kendaraan & Sub-Armada',
    description: 'Pengelompokan unit armada berdasarkan wilayah kerja, jenis kargo, dan manajer grup.',
    breadcrumb: ['Fleet', 'Grup Kendaraan'],
    permission: 'vehicle.view',
    path: '/app/fleet/groups',
  },
  organizations: {
    id: 'organizations',
    title: 'Multi-Tenant SaaS & Struktur Organisasi',
    description: 'Pusat kendali entitas perusahaan, pohon hirarki organisasi, alokasi cabang depo, dan batas isolasi tenant.',
    breadcrumb: ['Organisasi', 'Multi-Tenant SaaS'],
    permission: 'settings.view',
    path: '/app/organization',
  },
  tenants: {
    id: 'tenants',
    title: 'Manajemen Perusahaan SaaS (Tenants)',
    description: 'Daftar entitas perusahaan terdaftar, paket langganan, kuota armada, dan konfigurasi NPWP.',
    breadcrumb: ['Organisasi', 'Perusahaan SaaS'],
    permission: 'settings.view',
    path: '/app/organization/tenants',
  },
  fleets: {
    id: 'fleets',
    title: 'Sub-Grup Armada (Fleets)',
    description: 'Manajemen sub-armada khusus berdasarkan jenis unit, rute operasional, dan supervisor.',
    breadcrumb: ['Organisasi', 'Sub-Armada'],
    permission: 'vehicle.view',
    path: '/app/organization/fleets',
  },
  security_isolation: {
    id: 'security_isolation',
    title: 'Cross-Tenant Security & Isolation Lab',
    description: 'Suite pengujian isolasi data row-level security (RLS), anti-IDOR, dan boundary verification antar-tenant.',
    breadcrumb: ['Organisasi', 'Security Lab'],
    permission: 'settings.view',
    path: '/app/organization/security',
  },
  branches: {
    id: 'branches',
    title: 'Cabang & Depo Operasional',
    description: 'Manajemen kantor cabang, depo pelabuhan, alamat lokasi, dan manajer cabang.',
    breadcrumb: ['Fleet', 'Cabang & Depo'],
    permission: 'vehicle.view',
    path: '/app/fleet/branches',
  },
  departments: {
    id: 'departments',
    title: 'Departemen Perusahaan',
    description: 'Struktur departemen internal pengelola unit kendaraan dan alokasi operasional.',
    breadcrumb: ['Fleet', 'Departemen'],
    permission: 'vehicle.view',
    path: '/app/fleet/departments',
  },
  drivers: {
    id: 'drivers',
    title: 'Manajemen Pengemudi (Drivers)',
    description: 'Profil driver, masa berlaku SIM, skor keselamatan berkendara (Safety Score), dan histori pelanggaran.',
    breadcrumb: ['Fleet', 'Pengemudi'],
    permission: 'driver.view',
    path: '/app/drivers',
  },
  planned_trips: {
    id: 'planned_trips',
    title: 'Trip Management & Planned Trips',
    description: 'Perencanaan perjalanan operasional, penugasan armada & driver, kalkulasi ETA, waypoint & dispatch perintah jalan.',
    breadcrumb: ['Operations', 'Trip Management'],
    permission: 'trip.view',
    path: '/app/trips',
  },
  routes: {
    id: 'routes',
    title: 'Route Management & Master Routes',
    description: 'Perencanaan rute master, optimasi multi-objective, pembatasan jalan & tonase, rute alternatif, versi rute & deteksi deviasi.',
    breadcrumb: ['Operations', 'Route Management'],
    permission: 'route.view',
    path: '/app/routes',
  },
  trips: {
    id: 'trips',
    title: 'Trip History & Playback',
    description: 'Histori perjalanan historis berdasarkan telemetry GPS, pemutaran ulang rute (Route Playback), dan analisa anomali AI.',
    breadcrumb: ['Operations', 'Trip History'],
    permission: 'trip.view',
    path: '/app/trip-history',
  },
  geofence: {
    id: 'geofence',
    title: 'Geofence Zona LOKASI & POI',
    description: 'Pengaturan batas wilayah virtual (Geofencing), checkpoint Depot, POI Pelanggan, dan otomatisasi alert masuk/keluar.',
    breadcrumb: ['Operations', 'Geofences'],
    permission: 'geofence.view',
    path: '/app/geofences',
  },
  deliveries: {
    id: 'deliveries',
    title: 'Delivery Management & Proof of Delivery (POD)',
    description: 'Manajemen pengiriman kargo, jadwal penyerahan, pelacakan pelanggan real-time, bukti digital POD, dan AI SLA Analytics.',
    breadcrumb: ['Operations', 'Delivery & POD'],
    permission: 'trip.view',
    path: '/app/deliveries',
  },
  fuel: {
    id: 'fuel',
    title: 'Monitoring Efisiensi BBM (Fuel)',
    description: 'Integrasi sensor tangki BBM, deteksi pencurian/fuel drop, konsumsi L/100km, dan audit klaim rekap BBM.',
    breadcrumb: ['Management', 'Fuel Monitoring'],
    permission: 'fuel.view',
    path: '/app/fuel',
  },
  maintenance: {
    id: 'maintenance',
    title: 'Pemeliharaan & Work Orders (Bengkel)',
    description: 'Penjadwalan servis berkala, SPK perbaikan, manajemen suku cadang, dan biaya pemeliharaan.',
    breadcrumb: ['Management', 'Maintenance Work Orders'],
    permission: 'maintenance.view',
    path: '/app/maintenance',
  },
  safety: {
    id: 'safety',
    title: 'Keselamatan & Perilaku Pengemudi',
    description: 'Analisis insiden pengereman mendadak (harsh braking), tikungan tajam, speeding, dan alarm kelelahan (fatigue).',
    breadcrumb: ['Operations', 'Safety Score'],
    permission: 'safety.view',
    path: '/app/safety',
  },
  fatigue: {
    id: 'fatigue',
    title: 'Manajemen Kelelahan & Fatigue Intelligence',
    description: 'Pemantauan risiko kelelahan pengemudi, analisis jam mengemudi, istirahat, shift kerja, dan paparan mengemudi malam.',
    breadcrumb: ['Operations', 'Fatigue Management'],
    permission: 'safety.view',
    path: '/app/fatigue',
  },
  cost_analytics: {
    id: 'cost_analytics',
    title: 'Analisis Biaya Operasional (TOC) & TCO Armada',
    description: 'Pusat intelijen biaya armada terpadu: struktur TOC/TCO, cost per KM/Trip, alokasi proporsional, proyeksi AI, dan audit rekonsiliasi telematika.',
    breadcrumb: ['Operations', 'Analisis Biaya & TOC'],
    permission: 'cost.view',
    path: '/app/cost-analytics',
  },
  alerts: {
    id: 'alerts',
    title: 'Peringatan & Alarm Telematika',
    description: 'Daftar insiden darurat, SOS button, kabel GPS terputus, overspeed, dan notifikasi ambang batas.',
    breadcrumb: ['Operations', 'Alerts System'],
    permission: 'alert.view',
    path: '/app/alerts',
  },
  notifications: {
    id: 'notifications',
    title: 'Pusat Notifikasi Enterprise',
    description: 'Semua riwayat notifikasi sistem, peringatan keamanan, pesanan servis, dan pengumuman tenant.',
    breadcrumb: ['System', 'Pusat Notifikasi'],
    permission: 'dashboard.view',
    path: '/app/notifications',
  },
  route_intelligence: {
    id: 'route_intelligence',
    title: 'AI Route & ETA Intelligence',
    description: 'Pusat intelijen rute terpadu, prediksi live ETA, deteksi deviasi koridor real-time, optimasi multi-stop, analitik kemacetan & AI advisory.',
    breadcrumb: ['Intelligence', 'AI Route Intelligence'],
    permission: 'ai.view',
    path: '/app/route-intelligence',
  },
  fleet_intelligence: {
    id: 'fleet_intelligence',
    title: 'AI Fleet Intelligence Engine',
    description: 'Intelligence layer analisis kesehatan armada, utilisasi, performa kendaraan, anomali operasional, dan rekomendasi proaktif.',
    breadcrumb: ['Intelligence', 'Fleet Intelligence'],
    permission: 'ai.view',
    path: '/app/intelligence',
  },
  driver_intelligence: {
    id: 'driver_intelligence',
    title: 'AI Driver Intelligence & Safety Telematics',
    description: 'Pusat evaluasi risiko pengemudi, analisis perilaku mengemudi, ranking leaderboard, rekomendasi keselamatan proaktif, dan program coaching non-punitif.',
    breadcrumb: ['Intelligence', 'Driver Intelligence'],
    permission: 'driver.intelligence.view',
    path: '/app/driver-intelligence',
  },
  fuel_intelligence: {
    id: 'fuel_intelligence',
    title: 'AI Fuel Intelligence & Efficiency Analytics',
    description: 'Pusat analitik konsumsi BBM, baseline L/100km, deteksi anomali & kebocoran tangki, audit SPBU, dan rekomendasi efisiensi penghematan.',
    breadcrumb: ['Intelligence', 'AI Fuel Intelligence'],
    permission: 'fuel.view',
    path: '/app/fuel-intelligence',
  },
  maintenance_intelligence: {
    id: 'maintenance_intelligence',
    title: 'Predictive Maintenance & AI Health Intelligence',
    description: 'Pusat intelijen pemeliharaan prediktif armada, telemetri CAN-Bus, prakiraan kerusakan komponen, antrean P1-P4, dan optimasi biaya bengkel.',
    breadcrumb: ['Intelligence', 'Predictive Maintenance'],
    permission: 'maintenance.view',
    path: '/app/predictive-maintenance',
  },
  safety_intelligence: {
    id: 'safety_intelligence',
    title: 'AI Safety Intelligence & Risk Analytics',
    description: 'Intelijen keselamatan armada komprehensif, rekonstruksi telemetri 10Hz, analisis akar masalah 5-Why, prediksi risiko live trip, dan program coaching keselamatan.',
    breadcrumb: ['Intelligence', 'AI Safety Intelligence'],
    permission: 'safety.view',
    path: '/app/safety-intelligence',
  },
  daily_briefing: {
    id: 'daily_briefing',
    title: 'AI Fleet Daily Briefing (06:00 WIB)',
    description: 'Laporan kecerdasan harian armada berbasis AI: Skor kesehatan armada, indeks risiko, deteksi anomali BBM, prioritas servis prediktif, dan rekomendasi mitigasi proaktif.',
    breadcrumb: ['Intelligence', 'AI Daily Briefing'],
    permission: 'ai.view',
    path: '/app/daily-briefing',
  },
  fleet_daily_briefing: {
    id: 'fleet_daily_briefing',
    title: 'AI Fleet Daily Briefing (06:00 WIB)',
    description: 'Laporan kecerdasan harian armada berbasis AI: Skor kesehatan armada, indeks risiko, deteksi anomali BBM, prioritas servis prediktif, dan rekomendasi mitigasi proaktif.',
    breadcrumb: ['Intelligence', 'AI Daily Briefing'],
    permission: 'ai.view',
    path: '/app/daily-briefing',
  },
  fleet_assistant: {
    id: 'fleet_assistant',
    title: 'AI Fleet Assistant & Conversational Telematics',
    description: 'Asisten cerdas telematika armada berbasis AI lintas domain untuk analisis data, pencarian unit, investigasi anomali BBM, dan eksekusi tindakan operasional.',
    breadcrumb: ['Intelligence', 'AI Fleet Assistant'],
    permission: 'ai.view',
    path: '/app/fleet-assistant',
  },
  ai_intelligence: {
    id: 'ai_intelligence',
    title: 'AI Intelligence Hub & Assistant',
    description: 'Rekomendasi kecerdasan buatan untuk optimasi rute, prediksi kerusakan mesin, dan anomali BBM.',
    breadcrumb: ['Intelligence', 'AI Intelligence'],
    permission: 'ai.view',
    path: '/app/ai',
  },
  automation: {
    id: 'automation',
    title: 'AI Automation Engine & Event Triggers',
    description: 'Mesin orkestrasi alur kerja otomasi armada berbasis event telematika real-time, evaluasi kondisi AST, inferensi AI, dan tindakan otomatis.',
    breadcrumb: ['Intelligence', 'AI Automation Engine'],
    permission: 'automation.view',
    path: '/app/automation',
  },
  automation_workflows: {
    id: 'automation_workflows',
    title: 'Daftar Alur Kerja Automasi',
    description: 'Manajemen workflow automasi aktif, draft, dan riwayat revisi.',
    breadcrumb: ['Intelligence', 'Automation', 'Workflows'],
    permission: 'automation.view',
    path: '/app/automation/workflows',
  },
  automation_builder: {
    id: 'automation_builder',
    title: 'Visual DAG & NLP Automation Builder',
    description: 'Perancang grafis pipeline otomasi DAG dan perumus prompt AI Natural Language.',
    breadcrumb: ['Intelligence', 'Automation', 'Builder'],
    permission: 'automation.view',
    path: '/app/automation/builder',
  },
  automation_templates: {
    id: 'automation_templates',
    title: 'Katalog Template Automasi',
    description: 'Koleksi alur kerja best-practice logistik dan telematika siap pakai.',
    breadcrumb: ['Intelligence', 'Automation', 'Templates'],
    permission: 'automation.view',
    path: '/app/automation/templates',
  },
  automation_logs: {
    id: 'automation_logs',
    title: 'Audit Trail & Log Eksekusi Automasi',
    description: 'Jejak audit eksekusi DAG, evaluasi aturan kondisi, dan pengiriman notifikasi.',
    breadcrumb: ['Intelligence', 'Automation', 'Logs'],
    permission: 'automation.view',
    path: '/app/automation/logs',
  },
  automation_failed: {
    id: 'automation_failed',
    title: 'Insiden Eksekusi Automasi Gagal',
    description: 'Daftar kegagalan eksekusi automasi dan fasilitas retry otomatis/manual.',
    breadcrumb: ['Intelligence', 'Automation', 'Failed Executions'],
    permission: 'automation.view',
    path: '/app/automation/failed',
  },
  automation_settings: {
    id: 'automation_settings',
    title: 'Pengaturan & Tata Kelola Engine Automasi',
    description: 'Konfigurasi batas laju, anggaran AI token, webhook, dan jejak audit tata kelola.',
    breadcrumb: ['Intelligence', 'Automation', 'Settings'],
    permission: 'automation.view',
    path: '/app/automation/settings',
  },
  analytics: {
    id: 'analytics',
    title: 'Analitik Performa & Matriks KPI',
    description: 'Visualisasi grafis utilisasi armada, total Cost per KM, rasio idling, dan perbandingan performa cabang.',
    breadcrumb: ['Intelligence', 'Analytics'],
    permission: 'analytics.view',
    path: '/app/analytics',
  },
  reports: {
    id: 'reports',
    title: 'Laporan Otomatis & Export Data',
    description: 'Generator rekapitulasi harian/bulanan, laporan pajak bbm, log kilometer, dan ekspor PDF/Excel.',
    breadcrumb: ['Intelligence', 'Reports'],
    permission: 'report.view',
    path: '/app/reports',
  },
  documents: {
    id: 'documents',
    title: 'Manajemen Dokumen STNK & KIR',
    description: 'Masa berlaku STNK, KIR Uji Coba, Asuransi armada, dan jadwal perpanjangan izin jalan.',
    breadcrumb: ['Fleet', 'Dokumen Legalitas'],
    permission: 'vehicle.view',
    path: '/app/documents',
  },
  users: {
    id: 'users',
    title: 'Pengguna & Otorisasi Akun',
    description: 'Daftar staf perusahaan, otorisasi cabang, penugasan role, dan status akun.',
    breadcrumb: ['System', 'Pengguna Perusahaan'],
    permission: 'user.view',
    path: '/app/users',
  },
  roles_permissions: {
    id: 'roles_permissions',
    title: 'Matriks Hak Akses & RBAC',
    description: 'Konfigurasi role kustom, otorisasi resource action, dan audit log perubahan otorisasi.',
    breadcrumb: ['System', 'Matriks RBAC'],
    permission: 'role.view',
    path: '/app/roles-permissions',
  },
  integrations: {
    id: 'integrations',
    title: 'Gateway GPS IoT & API External',
    description: 'Koneksi sensor GPS pihak ketiga, Webhook REST API, dan status konektivitas server gateway.',
    breadcrumb: ['System', 'Integrasi IoT'],
    permission: 'integration.view',
    path: '/app/integrations',
  },
  settings: {
    id: 'settings',
    title: 'Pengaturan Perusahaan & Tenant',
    description: 'Konfigurasi identitas tenant, zona waktu, batas ambang kecepatan, dan otentikasi 2FA.',
    breadcrumb: ['System', 'Pengaturan Tenant'],
    permission: 'settings.view',
    path: '/app/settings',
  },
  profile: {
    id: 'profile',
    title: 'Profil Pengguna & Keamanan Akun',
    description: 'Informasi personal staf, penugasan cabang, log sesi aktif, dan kredensial keamanan.',
    breadcrumb: ['System', 'Profil Pengguna'],
    permission: 'dashboard.view',
    path: '/app/profile',
  },
  gps_devices: {
    id: 'gps_devices',
    title: 'GPS Device Master Management',
    description: 'Pengelolaan inventaris perangkat GPS tracker, registrasi IMEI, integrasi kendaraan, dan status konektivitas gateway.',
    breadcrumb: ['GPS & Tracking', 'GPS Devices'],
    permission: 'gps.device.view',
    path: '/app/gps/devices',
  },
  gps_integration: {
    id: 'gps_integration',
    title: 'GPS Integration & Protocol Abstraction Layer',
    description: 'Vendor-agnostic telematics integration layer: Multi-transport ingestion, Canonical Normalization, Dead Letter Queue & Simulator.',
    breadcrumb: ['GPS & Tracking', 'Protocol Abstraction Layer'],
    permission: 'gps.protocol.view',
    path: '/app/gps/integration',
  },
  gps_server: {
    id: 'gps_server',
    title: 'Enterprise GPS Server & Supabase Database',
    description: 'Gateway Ingestion Server Telemetri Multi-Protokol (Teltonika, JT808, Concox) dengan PostgreSQL PostGIS & Realtime WebSockets.',
    breadcrumb: ['System', 'GPS Server & Supabase'],
    permission: 'integration.view',
    path: '/app/gps/server',
  },
  gps_server_dashboard: {
    id: 'gps_server_dashboard',
    title: 'GPS Server Control Center',
    description: 'Gateway Ingestion Server Telemetri Multi-Protokol (Teltonika, JT808, Concox) dengan PostgreSQL PostGIS & Realtime WebSockets.',
    breadcrumb: ['System', 'GPS Server Control Center'],
    permission: 'integration.view',
    path: '/app/gps/server-dashboard',
  },
  gps_health: {
    id: 'gps_health',
    title: 'GPS Device Health & Diagnostics',
    description: 'Pusat pemantauan kesehatan perangkat GPS, performa pingsat, sinyal satelit, dan diagnostik otomatis.',
    breadcrumb: ['GPS & Tracking', 'Device Health'],
    permission: 'gps.device.view',
    path: '/app/gps/devices/health',
  },
  gps_sims: {
    id: 'gps_sims',
    title: 'SIM Card & M2M Cellular Management',
    description: 'Manajemen kartu SIM M2M, konfigurasi APN, pemantauan kuota data, dan histori penugasan perangkat.',
    breadcrumb: ['GPS & Tracking', 'SIM Cards'],
    permission: 'gps.sim.view',
    path: '/app/gps/sims',
  },
  gps_protocols: {
    id: 'gps_protocols',
    title: 'GPS Telematics Protocol Gateway',
    description: 'Katalog protokol telematika (GT06, Teltonika, Queclink, JT808), port gateway, dan adaptor parser.',
    breadcrumb: ['GPS & Tracking', 'Protocols'],
    permission: 'gps.protocol.view',
    path: '/app/gps/protocols',
  },
  gps_firmware: {
    id: 'gps_firmware',
    title: 'Firmware Repository & OTA Update',
    description: 'Pengelolaan versi firmware perangkat GPS, matriks kompatibilitas vendor, dan pembaruan perangkat lunak.',
    breadcrumb: ['GPS & Tracking', 'Firmware'],
    permission: 'gps.firmware.view',
    path: '/app/gps/firmware',
  },
  developer_portal: {
    id: 'developer_portal',
    title: 'External API & Developer Platform',
    description: 'Pusat integrasi API REST, kredensial API Keys terenkripsi SHA-256, OpenAPI 3.0 Explorer, Webhooks HMAC, dan sandbox ERP/TMS.',
    breadcrumb: ['Developer', 'External API & Webhooks'],
    permission: 'settings.view',
    path: '/app/developer',
  },
  external_api: {
    id: 'external_api',
    title: 'External API & Developer Platform',
    description: 'Pusat integrasi API REST, kredensial API Keys terenkripsi SHA-256, OpenAPI 3.0 Explorer, Webhooks HMAC, dan sandbox ERP/TMS.',
    breadcrumb: ['Developer', 'External API & Webhooks'],
    permission: 'settings.view',
    path: '/app/developer',
  },
  subscription: {
    id: 'subscription',
    title: 'Paket Berlangganan & Billing SaaS',
    description: 'Pusat manajemen paket langganan armada, monitoring kuota unit & AI, riwayat invoice, faktur pajak PPN 11%, dan payment gateway.',
    breadcrumb: ['System', 'Langganan & Billing'],
    permission: 'billing.view',
    path: '/app/subscription',
  },
  super_admin: {
    id: 'super_admin',
    title: 'Super Admin Control Center',
    description: 'Pusat kendali tertinggi platform SaaS multi-tenant: Perusahaan, Pengguna, Telematika IoT, Billing MRR, AI Compute, dan Incident Response.',
    breadcrumb: ['Platform Root', 'Super Admin Control Center'],
    permission: 'admin.company.manage',
    path: '/app/super-admin',
  },
  driver_mobile: {
    id: 'driver_mobile',
    title: 'Driver Mobile Experience & Workspace',
    description: 'PWA Mobile workspace khusus pengemudi: Navigasi rute live, inspeksi pre-trip, e-POD digital signature, pelaporan insiden, dan emergency SOS panic button.',
    breadcrumb: ['Operations', 'Driver Mobile App'],
    permission: 'trip.view',
    path: '/app/driver-mobile',
  },
  audit: {
    id: 'audit',
    title: 'Audit Trail & Activity Log',
    description: 'Pencatatan komprehensif, imutabel (append-only), dan isolasi tenant atas semua aktivitas sistem, otentikasi, CRUD data, dan AI.',
    breadcrumb: ['Sistem', 'Audit Trail & Activity Log'],
    permission: 'audit.view',
    path: '/app/audit',
  },
  enterprise_security: {
    id: 'enterprise_security',
    title: 'Enterprise Security & Zero Trust Center',
    description: 'Pusat keamanan enterprise: Enkripsi AES-256-GCM, manajemen sesi aktif, rate limiting, isolasi tenant & cabang, AI DLP, GPS firewall, dan disaster recovery.',
    breadcrumb: ['Sistem', 'Enterprise Security'],
    permission: 'security.view',
    path: '/app/security',
  },
  rent_car: {
    id: 'rent_car',
    title: 'Rent Car Management System',
    description: 'Sistem manajemen sewa mobil lengkap: Reservasi armada, inspeksi serah terima digital 360°, anti-theft immobilizer starter kill, AI KYC pelanggan & deposit escrow.',
    breadcrumb: ['Rent Car', 'Armada & GPS Live'],
    permission: 'vehicle.view',
    path: '/app/rent-car',
  },
  rent_car_bookings: {
    id: 'rent_car_bookings',
    title: 'Reservasi & Sewa Rental Mobil',
    description: 'Pipeline pemesanan rental mobil, jadwal check-in & check-out, penugasan driver, dan faktur penagihan.',
    breadcrumb: ['Rent Car', 'Reservasi & Sewa'],
    permission: 'vehicle.view',
    path: '/app/rent-car/bookings',
  },
  rent_car_contracts: {
    id: 'rent_car_contracts',
    title: 'Kontrak Digital & E-Signature Sewa',
    description: 'Penerbitan surat perjanjian sewa menyewa (SPK/SPM), klausul hukum, batas kilometer, dan tanda tangan digital ganda.',
    breadcrumb: ['Rent Car', 'Kontrak Digital'],
    permission: 'vehicle.view',
    path: '/app/rent-car/contracts',
  },
  rent_car_calendar: {
    id: 'rent_car_calendar',
    title: 'Kalender Ketersediaan & Timeline Sewa',
    description: 'Visualisasi timeline sewa armada, jadwal booking mendatang, dan monitoring unit yang sedang aktif beroperasi.',
    breadcrumb: ['Rent Car', 'Kalender Sewa'],
    permission: 'vehicle.view',
    path: '/app/rent-car/calendar',
  },
  rent_car_customers: {
    id: 'rent_car_customers',
    title: 'CRM Pelanggan & AI Fraud KYC Shield',
    description: 'Verifikasi identitas e-KTP/SIM, penilaian skor risiko anti-fraud, dan pencegahan penggelapan armada.',
    breadcrumb: ['Rent Car', 'Pelanggan & KYC'],
    permission: 'vehicle.view',
    path: '/app/rent-car/customers',
  },
  rent_car_damages: {
    id: 'rent_car_damages',
    title: 'Klaim & Inspeksi Kerusakan 360°',
    description: 'Peta kerusakan visual 360°, estimasi biaya perbaikan, klaim asuransi CDW, dan pemotongan deposit escrow.',
    breadcrumb: ['Rent Car', 'Klaim & Kerusakan'],
    permission: 'vehicle.view',
    path: '/app/rent-car/damages',
  },
  rent_car_invoices: {
    id: 'rent_car_invoices',
    title: 'Faktur, Pembayaran & Piutang Rental',
    description: 'Penerbitan faktur sewa, pelunasan bertahap (DP, Full Payment), perhitungan PPN 11%, dan rekonsiliasi deposit escrow.',
    breadcrumb: ['Rent Car', 'Faktur & Piutang'],
    permission: 'vehicle.view',
    path: '/app/rent-car/invoices',
  },
  rent_car_security: {
    id: 'rent_car_security',
    title: 'Keamanan Telematika & Remote Starter Kill',
    description: 'Pemantauan perimeter geofence rental, deteksi parkir malam hari, sabotase GPS, dan kunci starter jarak jauh (Immobilizer).',
    breadcrumb: ['Rent Car', 'Keamanan & Anti-Theft'],
    permission: 'vehicle.view',
    path: '/app/rent-car/security',
  },
  rent_car_tariffs: {
    id: 'rent_car_tariffs',
    title: 'Matriks Tarif Sewa & Deposit Escrow',
    description: 'Pengaturan rate card harian/mingguan/bulanan, paket sopir, all-in, dan monitoring rekening escrow deposit jaminan.',
    breadcrumb: ['Rent Car', 'Tarif & Deposit'],
    permission: 'vehicle.view',
    path: '/app/rent-car/tariffs',
  },
  rent_car_analytics: {
    id: 'rent_car_analytics',
    title: 'Analitik Laba Rugi & Profitabilitas Unit',
    description: 'Evaluasi RevPAV (Revenue per Available Vehicle), utilisasi armada, ROI unit kendaraan, dan margin laba bersih.',
    breadcrumb: ['Rent Car', 'Analitik Laba Rugi'],
    permission: 'vehicle.view',
    path: '/app/rent-car/analytics',
  },
  rent_car_ai: {
    id: 'rent_car_ai',
    title: 'AI Copilot & Smart Rental Radar',
    description: 'Deteksi anomali rute AI, prediksi keterlambatan pengembalian armada, dan rekomendasi harga dinamis (*dynamic pricing*).',
    breadcrumb: ['Rent Car', 'AI Copilot & Radar'],
    permission: 'vehicle.view',
    path: '/app/rent-car/ai',
  },
  rent_car_reports: {
    id: 'rent_car_reports',
    title: 'Pusat Laporan & Audit Rental Mobil',
    description: 'Ekspor laporan operasional rental, log transaksi deposit, rekonsiliasi kas, dan kepatuhan armada legalitas.',
    breadcrumb: ['Rent Car', 'Pusat Laporan'],
    permission: 'vehicle.view',
    path: '/app/rent-car/reports',
  },
  rent_car_inspection: {
    id: 'rent_car_inspection',
    title: 'Inspeksi & Serah Terima Digital 360°',
    description: 'Inspeksi visual bodi, pin kerusakan 360°, checklist kelengkapan dan e-signature serah terima.',
    breadcrumb: ['Rent Car', 'Inspeksi Serah Terima'],
    permission: 'vehicle.view',
    path: '/app/rent-car/inspection',
  },
  rent_car_crm: {
    id: 'rent_car_crm',
    title: 'Manajemen Data & KYC Pelanggan Rental',
    description: 'Database pelanggan, verifikasi identitas, dan manajemen blacklist anti penggelapan.',
    breadcrumb: ['Rent Car', 'Pelanggan CRM'],
    permission: 'vehicle.view',
    path: '/app/rent-car/crm',
  },
  rent_car_telematics: {
    id: 'rent_car_telematics',
    title: 'Telematika & Geofence Mobil Rental',
    description: 'Live GPS perimeter, deteksi pelanggaran batas wilayah, dan remote starter-kill.',
    breadcrumb: ['Rent Car', 'Telematika Live'],
    permission: 'vehicle.view',
    path: '/app/rent-car/telematics',
  },
  security: {
    id: 'security',
    title: 'Enterprise Security & Zero Trust Center',
    description: 'Pusat keamanan enterprise: Enkripsi AES-256-GCM, manajemen sesi aktif, rate limiting, isolasi tenant & cabang, AI DLP, GPS firewall, dan disaster recovery.',
    breadcrumb: ['Sistem', 'Enterprise Security'],
    permission: 'security.view',
    path: '/app/security',
  },
};
