/**
 * Fleet Intelligence Smart AI - Centralized Route & Page Metadata Configuration
 * Used by Breadcrumb, PageHeader, Document Title, and RBAC Permission Guards
 */

import { ActiveView } from '../context/FleetContext';

export interface RouteMetadata {
  id: ActiveView;
  title: string;
  description: string;
  breadcrumb: string[];
  permission: string;
  path: string;
}

export const ROUTE_METADATA_MAP: Record<ActiveView, RouteMetadata> = {
  command_center: {
    id: 'command_center',
    title: 'Command Center & Control Room',
    description: 'Pusat komando operasional telematika armada 24/7: Pemantauan darurat SOS, mitigasi risiko realtime, peta live telemetri, dan rekomendasi dispatch AI.',
    breadcrumb: ['Operations', 'Command Center'],
    permission: 'command_center.view',
    path: '/app/command-center',
  },
  executive_dashboard: {
    id: 'executive_dashboard',
    title: 'Executive Dashboard (Direksi & Owner)',
    description: 'Fleet business overview and AI-powered decision intelligence (See → Understand → Decide → Act).',
    breadcrumb: ['Executive', 'Dashboard Direksi'],
    permission: 'executive.dashboard.view',
    path: '/executive',
  },
  executive_report: {
    id: 'executive_report',
    title: 'Laporan Intelijen Eksekutif C-Level & Board',
    description: 'Laporan komprehensif berkala (MTD/QTD/YTD), audit telematika zero-hallucination, analisa 5-Why, proyeksi prediktif, dan papan persetujuan keputusan direksi.',
    breadcrumb: ['Executive', 'Laporan Eksekutif C-Level'],
    permission: 'executive.dashboard.view',
    path: '/executive/report',
  },
  executive_print: {
    id: 'executive_print',
    title: 'Executive Report Print Preview',
    description: 'Format cetak resmi laporan eksekutif armada untuk C-Level & Board of Directors.',
    breadcrumb: ['Executive', 'Print Report'],
    permission: 'executive.dashboard.export',
    path: '/executive/print',
  },
  dashboard: {
    id: 'dashboard',
    title: 'Dashboard Utama Operasional',
    description: 'Ringkasan performa armada, status telemetri GPS live, dan matriks kesehatan operasional.',
    breadcrumb: ['Overview', 'Dashboard Utama'],
    permission: 'dashboard.view',
    path: '/app/dashboard',
  },
  live_tracking: {
    id: 'live_tracking',
    title: 'Live GPS Tracking & Telematika',
    description: 'Pemantauan lokasi kendaraan real-time, status mesin, kecepatan, dan pemutaran ulang rute (Route Playback).',
    breadcrumb: ['Operations', 'Live Tracking'],
    permission: 'tracking.view',
    path: '/app/tracking',
  },
  inspection: {
    id: 'inspection',
    title: 'Vehicle Inspection & Smart Pre-Trip',
    description: 'Pemeriksaan pra-keberangkatan digital, kepatuhan K3, audit kondisi fisik armada, dan auto-grounding.',
    breadcrumb: ['Operations', 'Inspeksi & Pre-Trip'],
    permission: 'inspection.view',
    path: '/app/inspection',
  },
  vehicles: {
    id: 'vehicles',
    title: 'Manajemen Kendaraan & Master Aset',
    description: 'Inventarisasi unit kendaraan, sensor IoT telematika, odometer, dan alokasi cabang.',
    breadcrumb: ['Fleet', 'Kendaraan Master'],
    permission: 'vehicle.view',
    path: '/app/fleet/vehicles',
  },
  vehicle_groups: {
    id: 'vehicle_groups',
    title: 'Grup Kendaraan & Sub-Armada',
    description: 'Pengelompokan unit armada berdasarkan wilayah kerja, jenis kargo, dan manajer grup.',
    breadcrumb: ['Fleet', 'Grup Kendaraan'],
    permission: 'vehicle.view',
    path: '/app/fleet/groups',
  },
  organizations: {
    id: 'organizations',
    title: 'Multi-Tenant SaaS & Struktur Organisasi',
    description: 'Pusat kendali entitas perusahaan, pohon hirarki organisasi, alokasi cabang depo, dan batas isolasi tenant.',
    breadcrumb: ['Organisasi', 'Multi-Tenant SaaS'],
    permission: 'settings.view',
    path: '/app/organization',
  },
  tenants: {
    id: 'tenants',
    title: 'Manajemen Perusahaan SaaS (Tenants)',
    description: 'Daftar entitas perusahaan terdaftar, paket langganan, kuota armada, dan konfigurasi NPWP.',
    breadcrumb: ['Organisasi', 'Perusahaan SaaS'],
    permission: 'settings.view',
    path: '/app/organization/tenants',
  },
  fleets: {
    id: 'fleets',
    title: 'Sub-Grup Armada (Fleets)',
    description: 'Manajemen sub-armada khusus berdasarkan jenis unit, rute operasional, dan supervisor.',
    breadcrumb: ['Organisasi', 'Sub-Armada'],
    permission: 'vehicle.view',
    path: '/app/organization/fleets',
  },
  security_isolation: {
    id: 'security_isolation',
    title: 'Cross-Tenant Security & Isolation Lab',
    description: 'Suite pengujian isolasi data row-level security (RLS), anti-IDOR, dan boundary verification antar-tenant.',
    breadcrumb: ['Organisasi', 'Security Lab'],
    permission: 'settings.view',
    path: '/app/organization/security',
  },
  branches: {
    id: 'branches',
    title: 'Cabang & Depo Operasional',
    description: 'Manajemen kantor cabang, depo pelabuhan, alamat lokasi, dan manajer cabang.',
    breadcrumb: ['Fleet', 'Cabang & Depo'],
    permission: 'vehicle.view',
    path: '/app/fleet/branches',
  },
  departments: {
    id: 'departments',
    title: 'Departemen Perusahaan',
    description: 'Struktur departemen internal pengelola unit kendaraan dan alokasi operasional.',
    breadcrumb: ['Fleet', 'Departemen'],
    permission: 'vehicle.view',
    path: '/app/fleet/departments',
  },
  drivers: {
    id: 'drivers',
    title: 'Manajemen Pengemudi (Drivers)',
    description: 'Profil driver, masa berlaku SIM, skor keselamatan berkendara (Safety Score), dan histori pelanggaran.',
    breadcrumb: ['Fleet', 'Pengemudi'],
    permission: 'driver.view',
    path: '/app/drivers',
  },
  planned_trips: {
    id: 'planned_trips',
    title: 'Trip Management & Planned Trips',
    description: 'Perencanaan perjalanan operasional, penugasan armada & driver, kalkulasi ETA, waypoint & dispatch perintah jalan.',
    breadcrumb: ['Operations', 'Trip Management'],
    permission: 'trip.view',
    path: '/app/trips',
  },
  routes: {
    id: 'routes',
    title: 'Route Management & Master Routes',
    description: 'Perencanaan rute master, optimasi multi-objective, pembatasan jalan & tonase, rute alternatif, versi rute & deteksi deviasi.',
    breadcrumb: ['Operations', 'Route Management'],
    permission: 'route.view',
    path: '/app/routes',
  },
  trips: {
    id: 'trips',
    title: 'Trip History & Playback',
    description: 'Histori perjalanan historis berdasarkan telemetry GPS, pemutaran ulang rute (Route Playback), dan analisa anomali AI.',
    breadcrumb: ['Operations', 'Trip History'],
    permission: 'trip.view',
    path: '/app/trip-history',
  },
  geofence: {
    id: 'geofence',
    title: 'Geofence Zona LOKASI & POI',
    description: 'Pengaturan batas wilayah virtual (Geofencing), checkpoint Depot, POI Pelanggan, dan otomatisasi alert masuk/keluar.',
    breadcrumb: ['Operations', 'Geofences'],
    permission: 'geofence.view',
    path: '/app/geofences',
  },
  deliveries: {
    id: 'deliveries',
    title: 'Delivery Management & Proof of Delivery (POD)',
    description: 'Manajemen pengiriman kargo, jadwal penyerahan, pelacakan pelanggan real-time, bukti digital POD, dan AI SLA Analytics.',
    breadcrumb: ['Operations', 'Delivery & POD'],
    permission: 'trip.view',
    path: '/app/deliveries',
  },
  fuel: {
    id: 'fuel',
    title: 'Monitoring Efisiensi BBM (Fuel)',
    description: 'Integrasi sensor tangki BBM, deteksi pencurian/fuel drop, konsumsi L/100km, dan audit klaim rekap BBM.',
    breadcrumb: ['Management', 'Fuel Monitoring'],
    permission: 'fuel.view',
    path: '/app/fuel',
  },
  maintenance: {
    id: 'maintenance',
    title: 'Pemeliharaan & Work Orders (Bengkel)',
    description: 'Penjadwalan servis berkala, SPK perbaikan, manajemen suku cadang, dan biaya pemeliharaan.',
    breadcrumb: ['Management', 'Maintenance Work Orders'],
    permission: 'maintenance.view',
    path: '/app/maintenance',
  },
  safety: {
    id: 'safety',
    title: 'Keselamatan & Perilaku Pengemudi',
    description: 'Analisis insiden pengereman mendadak (harsh braking), tikungan tajam, speeding, dan alarm kelelahan (fatigue).',
    breadcrumb: ['Operations', 'Safety Score'],
    permission: 'safety.view',
    path: '/app/safety',
  },
  fatigue: {
    id: 'fatigue',
    title: 'Manajemen Kelelahan & Fatigue Intelligence',
    description: 'Pemantauan risiko kelelahan pengemudi, analisis jam mengemudi, istirahat, shift kerja, dan paparan mengemudi malam.',
    breadcrumb: ['Operations', 'Fatigue Management'],
    permission: 'safety.view',
    path: '/app/fatigue',
  },
  cost_analytics: {
    id: 'cost_analytics',
    title: 'Analisis Biaya Operasional (TOC) & TCO Armada',
    description: 'Pusat intelijen biaya armada terpadu: struktur TOC/TCO, cost per KM/Trip, alokasi proporsional, proyeksi AI, dan audit rekonsiliasi telematika.',
    breadcrumb: ['Operations', 'Analisis Biaya & TOC'],
    permission: 'cost.view',
    path: '/app/cost-analytics',
  },
  alerts: {
    id: 'alerts',
    title: 'Peringatan & Alarm Telematika',
    description: 'Daftar insiden darurat, SOS button, kabel GPS terputus, overspeed, dan notifikasi ambang batas.',
    breadcrumb: ['Operations', 'Alerts System'],
    permission: 'alert.view',
    path: '/app/alerts',
  },
  notifications: {
    id: 'notifications',
    title: 'Pusat Notifikasi Enterprise',
    description: 'Semua riwayat notifikasi sistem, peringatan keamanan, pesanan servis, dan pengumuman tenant.',
    breadcrumb: ['System', 'Pusat Notifikasi'],
    permission: 'dashboard.view',
    path: '/app/notifications',
  },
  route_intelligence: {
    id: 'route_intelligence',
    title: 'AI Route & ETA Intelligence',
    description: 'Pusat intelijen rute terpadu, prediksi live ETA, deteksi deviasi koridor real-time, optimasi multi-stop, analitik kemacetan & AI advisory.',
    breadcrumb: ['Intelligence', 'AI Route Intelligence'],
    permission: 'ai.view',
    path: '/app/route-intelligence',
  },
  fleet_intelligence: {
    id: 'fleet_intelligence',
    title: 'AI Fleet Intelligence Engine',
    description: 'Intelligence layer analisis kesehatan armada, utilisasi, performa kendaraan, anomali operasional, dan rekomendasi proaktif.',
    breadcrumb: ['Intelligence', 'Fleet Intelligence'],
    permission: 'ai.view',
    path: '/app/intelligence',
  },
  driver_intelligence: {
    id: 'driver_intelligence',
    title: 'AI Driver Intelligence & Safety Telematics',
    description: 'Pusat evaluasi risiko pengemudi, analisis perilaku mengemudi, ranking leaderboard, rekomendasi keselamatan proaktif, dan program coaching non-punitif.',
    breadcrumb: ['Intelligence', 'Driver Intelligence'],
    permission: 'driver.intelligence.view',
    path: '/app/driver-intelligence',
  },
  fuel_intelligence: {
    id: 'fuel_intelligence',
    title: 'AI Fuel Intelligence & Efficiency Analytics',
    description: 'Pusat analitik konsumsi BBM, baseline L/100km, deteksi anomali & kebocoran tangki, audit SPBU, dan rekomendasi efisiensi penghematan.',
    breadcrumb: ['Intelligence', 'AI Fuel Intelligence'],
    permission: 'fuel.view',
    path: '/app/fuel-intelligence',
  },
  maintenance_intelligence: {
    id: 'maintenance_intelligence',
    title: 'Predictive Maintenance & AI Health Intelligence',
    description: 'Pusat intelijen pemeliharaan prediktif armada, telemetri CAN-Bus, prakiraan kerusakan komponen, antrean P1-P4, dan optimasi biaya bengkel.',
    breadcrumb: ['Intelligence', 'Predictive Maintenance'],
    permission: 'maintenance.view',
    path: '/app/predictive-maintenance',
  },
  safety_intelligence: {
    id: 'safety_intelligence',
    title: 'AI Safety Intelligence & Risk Analytics',
    description: 'Intelijen keselamatan armada komprehensif, rekonstruksi telemetri 10Hz, analisis akar masalah 5-Why, prediksi risiko live trip, dan program coaching keselamatan.',
    breadcrumb: ['Intelligence', 'AI Safety Intelligence'],
    permission: 'safety.view',
    path: '/app/safety-intelligence',
  },
  daily_briefing: {
    id: 'daily_briefing',
    title: 'AI Fleet Daily Briefing (06:00 WIB)',
    description: 'Laporan kecerdasan harian armada berbasis AI: Skor kesehatan armada, indeks risiko, deteksi anomali BBM, prioritas servis prediktif, dan rekomendasi mitigasi proaktif.',
    breadcrumb: ['Intelligence', 'AI Daily Briefing'],
    permission: 'ai.view',
    path: '/app/daily-briefing',
  },
  fleet_daily_briefing: {
    id: 'fleet_daily_briefing',
    title: 'AI Fleet Daily Briefing (06:00 WIB)',
    description: 'Laporan kecerdasan harian armada berbasis AI: Skor kesehatan armada, indeks risiko, deteksi anomali BBM, prioritas servis prediktif, dan rekomendasi mitigasi proaktif.',
    breadcrumb: ['Intelligence', 'AI Daily Briefing'],
    permission: 'ai.view',
    path: '/app/daily-briefing',
  },
  fleet_assistant: {
    id: 'fleet_assistant',
    title: 'AI Fleet Assistant & Conversational Telematics',
    description: 'Asisten cerdas telematika armada berbasis AI lintas domain untuk analisis data, pencarian unit, investigasi anomali BBM, dan eksekusi tindakan operasional.',
    breadcrumb: ['Intelligence', 'AI Fleet Assistant'],
    permission: 'ai.view',
    path: '/app/fleet-assistant',
  },
  ai_intelligence: {
    id: 'ai_intelligence',
    title: 'AI Intelligence Hub & Assistant',
    description: 'Rekomendasi kecerdasan buatan untuk optimasi rute, prediksi kerusakan mesin, dan anomali BBM.',
    breadcrumb: ['Intelligence', 'AI Intelligence'],
    permission: 'ai.view',
    path: '/app/ai',
  },
  automation: {
    id: 'automation',
    title: 'AI Automation Engine & Event Triggers',
    description: 'Mesin orkestrasi alur kerja otomasi armada berbasis event telematika real-time, evaluasi kondisi AST, inferensi AI, dan tindakan otomatis.',
    breadcrumb: ['Intelligence', 'AI Automation Engine'],
    permission: 'automation.view',
    path: '/app/automation',
  },
  automation_workflows: {
    id: 'automation_workflows',
    title: 'Daftar Alur Kerja Automasi',
    description: 'Manajemen workflow automasi aktif, draft, dan riwayat revisi.',
    breadcrumb: ['Intelligence', 'Automation', 'Workflows'],
    permission: 'automation.view',
    path: '/app/automation/workflows',
  },
  automation_builder: {
    id: 'automation_builder',
    title: 'Visual DAG & NLP Automation Builder',
    description: 'Perancang grafis pipeline otomasi DAG dan perumus prompt AI Natural Language.',
    breadcrumb: ['Intelligence', 'Automation', 'Builder'],
    permission: 'automation.view',
    path: '/app/automation/builder',
  },
  automation_templates: {
    id: 'automation_templates',
    title: 'Katalog Template Automasi',
    description: 'Koleksi alur kerja best-practice logistik dan telematika siap pakai.',
    breadcrumb: ['Intelligence', 'Automation', 'Templates'],
    permission: 'automation.view',
    path: '/app/automation/templates',
  },
  automation_logs: {
    id: 'automation_logs',
    title: 'Audit Trail & Log Eksekusi Automasi',
    description: 'Jejak audit eksekusi DAG, evaluasi aturan kondisi, dan pengiriman notifikasi.',
    breadcrumb: ['Intelligence', 'Automation', 'Logs'],
    permission: 'automation.view',
    path: '/app/automation/logs',
  },
  automation_failed: {
    id: 'automation_failed',
    title: 'Insiden Eksekusi Automasi Gagal',
    description: 'Daftar kegagalan eksekusi automasi dan fasilitas retry otomatis/manual.',
    breadcrumb: ['Intelligence', 'Automation', 'Failed Executions'],
    permission: 'automation.view',
    path: '/app/automation/failed',
  },
  automation_settings: {
    id: 'automation_settings',
    title: 'Pengaturan & Tata Kelola Engine Automasi',
    description: 'Konfigurasi batas laju, anggaran AI token, webhook, dan jejak audit tata kelola.',
    breadcrumb: ['Intelligence', 'Automation', 'Settings'],
    permission: 'automation.view',
    path: '/app/automation/settings',
  },
  analytics: {
    id: 'analytics',
    title: 'Analitik Performa & Matriks KPI',
    description: 'Visualisasi grafis utilisasi armada, total Cost per KM, rasio idling, dan perbandingan performa cabang.',
    breadcrumb: ['Intelligence', 'Analytics'],
    permission: 'analytics.view',
    path: '/app/analytics',
  },
  reports: {
    id: 'reports',
    title: 'Laporan Otomatis & Export Data',
    description: 'Generator rekapitulasi harian/bulanan, laporan pajak bbm, log kilometer, dan ekspor PDF/Excel.',
    breadcrumb: ['Intelligence', 'Reports'],
    permission: 'report.view',
    path: '/app/reports',
  },
  documents: {
    id: 'documents',
    title: 'Manajemen Dokumen STNK & KIR',
    description: 'Masa berlaku STNK, KIR Uji Coba, Asuransi armada, dan jadwal perpanjangan izin jalan.',
    breadcrumb: ['Fleet', 'Dokumen Legalitas'],
    permission: 'vehicle.view',
    path: '/app/documents',
  },
  users: {
    id: 'users',
    title: 'Pengguna & Otorisasi Akun',
    description: 'Daftar staf perusahaan, otorisasi cabang, penugasan role, dan status akun.',
    breadcrumb: ['System', 'Pengguna Perusahaan'],
    permission: 'user.view',
    path: '/app/users',
  },
  roles_permissions: {
    id: 'roles_permissions',
    title: 'Matriks Hak Akses & RBAC',
    description: 'Konfigurasi role kustom, otorisasi resource action, dan audit log perubahan otorisasi.',
    breadcrumb: ['System', 'Matriks RBAC'],
    permission: 'role.view',
    path: '/app/roles-permissions',
  },
  integrations: {
    id: 'integrations',
    title: 'Gateway GPS IoT & API External',
    description: 'Koneksi sensor GPS pihak ketiga, Webhook REST API, dan status konektivitas server gateway.',
    breadcrumb: ['System', 'Integrasi IoT'],
    permission: 'integration.view',
    path: '/app/integrations',
  },
  settings: {
    id: 'settings',
    title: 'Pengaturan Perusahaan & Tenant',
    description: 'Konfigurasi identitas tenant, zona waktu, batas ambang kecepatan, dan otentikasi 2FA.',
    breadcrumb: ['System', 'Pengaturan Tenant'],
    permission: 'settings.view',
    path: '/app/settings',
  },
  profile: {
    id: 'profile',
    title: 'Profil Pengguna & Keamanan Akun',
    description: 'Informasi personal staf, penugasan cabang, log sesi aktif, dan kredensial keamanan.',
    breadcrumb: ['System', 'Profil Pengguna'],
    permission: 'dashboard.view',
    path: '/app/profile',
  },
  gps_devices: {
    id: 'gps_devices',
    title: 'GPS Device Master Management',
    description: 'Pengelolaan inventaris perangkat GPS tracker, registrasi IMEI, integrasi kendaraan, dan status konektivitas gateway.',
    breadcrumb: ['GPS & Tracking', 'GPS Devices'],
    permission: 'gps.device.view',
    path: '/app/gps/devices',
  },
  gps_integration: {
    id: 'gps_integration',
    title: 'GPS Integration & Protocol Abstraction Layer',
    description: 'Vendor-agnostic telematics integration layer: Multi-transport ingestion, Canonical Normalization, Dead Letter Queue & Simulator.',
    breadcrumb: ['GPS & Tracking', 'Protocol Abstraction Layer'],
    permission: 'gps.protocol.view',
    path: '/app/gps/integration',
  },
  gps_server: {
    id: 'gps_server',
    title: 'Enterprise GPS Server & Supabase Database',
    description: 'Gateway Ingestion Server Telemetri Multi-Protokol (Teltonika, JT808, Concox) dengan PostgreSQL PostGIS & Realtime WebSockets.',
    breadcrumb: ['System', 'GPS Server & Supabase'],
    permission: 'integration.view',
    path: '/app/gps/server',
  },
  gps_server_dashboard: {
    id: 'gps_server_dashboard',
    title: 'GPS Server Control Center',
    description: 'Gateway Ingestion Server Telemetri Multi-Protokol (Teltonika, JT808, Concox) dengan PostgreSQL PostGIS & Realtime WebSockets.',
    breadcrumb: ['System', 'GPS Server Control Center'],
    permission: 'integration.view',
    path: '/app/gps/server-dashboard',
  },
  gps_health: {
    id: 'gps_health',
    title: 'GPS Device Health & Diagnostics',
    description: 'Pusat pemantauan kesehatan perangkat GPS, performa pingsat, sinyal satelit, dan diagnostik otomatis.',
    breadcrumb: ['GPS & Tracking', 'Device Health'],
    permission: 'gps.device.view',
    path: '/app/gps/devices/health',
  },
  gps_sims: {
    id: 'gps_sims',
    title: 'SIM Card & M2M Cellular Management',
    description: 'Manajemen kartu SIM M2M, konfigurasi APN, pemantauan kuota data, dan histori penugasan perangkat.',
    breadcrumb: ['GPS & Tracking', 'SIM Cards'],
    permission: 'gps.sim.view',
    path: '/app/gps/sims',
  },
  gps_protocols: {
    id: 'gps_protocols',
    title: 'GPS Telematics Protocol Gateway',
    description: 'Katalog protokol telematika (GT06, Teltonika, Queclink, JT808), port gateway, dan adaptor parser.',
    breadcrumb: ['GPS & Tracking', 'Protocols'],
    permission: 'gps.protocol.view',
    path: '/app/gps/protocols',
  },
  gps_firmware: {
    id: 'gps_firmware',
    title: 'Firmware Repository & OTA Update',
    description: 'Pengelolaan versi firmware perangkat GPS, matriks kompatibilitas vendor, dan pembaruan perangkat lunak.',
    breadcrumb: ['GPS & Tracking', 'Firmware'],
    permission: 'gps.firmware.view',
    path: '/app/gps/firmware',
  },
  developer_portal: {
    id: 'developer_portal',
    title: 'External API & Developer Platform',
    description: 'Pusat integrasi API REST, kredensial API Keys terenkripsi SHA-256, OpenAPI 3.0 Explorer, Webhooks HMAC, dan sandbox ERP/TMS.',
    breadcrumb: ['Developer', 'External API & Webhooks'],
    permission: 'settings.view',
    path: '/app/developer',
  },
  external_api: {
    id: 'external_api',
    title: 'External API & Developer Platform',
    description: 'Pusat integrasi API REST, kredensial API Keys terenkripsi SHA-256, OpenAPI 3.0 Explorer, Webhooks HMAC, dan sandbox ERP/TMS.',
    breadcrumb: ['Developer', 'External API & Webhooks'],
    permission: 'settings.view',
    path: '/app/developer',
  },
  subscription: {
    id: 'subscription',
    title: 'Paket Berlangganan & Billing SaaS',
    description: 'Pusat manajemen paket langganan armada, monitoring kuota unit & AI, riwayat invoice, faktur pajak PPN 11%, dan payment gateway.',
    breadcrumb: ['System', 'Langganan & Billing'],
    permission: 'billing.view',
    path: '/app/subscription',
  },
  super_admin: {
    id: 'super_admin',
    title: 'Super Admin Control Center',
    description: 'Pusat kendali tertinggi platform SaaS multi-tenant: Perusahaan, Pengguna, Telematika IoT, Billing MRR, AI Compute, dan Incident Response.',
    breadcrumb: ['Platform Root', 'Super Admin Control Center'],
    permission: 'admin.company.manage',
    path: '/app/super-admin',
  },
  driver_mobile: {
    id: 'driver_mobile',
    title: 'Driver Mobile Experience & Workspace',
    description: 'PWA Mobile workspace khusus pengemudi: Navigasi rute live, inspeksi pre-trip, e-POD digital signature, pelaporan insiden, dan emergency SOS panic button.',
    breadcrumb: ['Operations', 'Driver Mobile App'],
    permission: 'trip.view',
    path: '/app/driver-mobile',
  },
  audit: {
    id: 'audit',
    title: 'Audit Trail & Activity Log',
    description: 'Pencatatan komprehensif, imutabel (append-only), dan isolasi tenant atas semua aktivitas sistem, otentikasi, CRUD data, dan AI.',
    breadcrumb: ['Sistem', 'Audit Trail & Activity Log'],
    permission: 'audit.view',
    path: '/app/audit',
  },
  enterprise_security: {
    id: 'enterprise_security',
    title: 'Enterprise Security & Zero Trust Center',
    description: 'Pusat keamanan enterprise: Enkripsi AES-256-GCM, manajemen sesi aktif, rate limiting, isolasi tenant & cabang, AI DLP, GPS firewall, dan disaster recovery.',
    breadcrumb: ['Sistem', 'Enterprise Security'],
    permission: 'security.view',
    path: '/app/security',
  },
  rent_car: {
    id: 'rent_car',
    title: 'Rent Car Management System',
    description: 'Sistem manajemen sewa mobil lengkap: Reservasi armada, inspeksi serah terima digital 360°, anti-theft immobilizer starter kill, AI KYC pelanggan & deposit escrow.',
    breadcrumb: ['Rent Car', 'Armada & GPS Live'],
    permission: 'vehicle.view',
    path: '/app/rent-car',
  },
  rent_car_bookings: {
    id: 'rent_car_bookings',
    title: 'Reservasi & Sewa Rental Mobil',
    description: 'Pipeline pemesanan rental mobil, jadwal check-in & check-out, penugasan driver, dan faktur penagihan.',
    breadcrumb: ['Rent Car', 'Reservasi & Sewa'],
    permission: 'vehicle.view',
    path: '/app/rent-car/bookings',
  },
  rent_car_contracts: {
    id: 'rent_car_contracts',
    title: 'Kontrak Digital & E-Signature Sewa',
    description: 'Penerbitan surat perjanjian sewa menyewa (SPK/SPM), klausul hukum, batas kilometer, dan tanda tangan digital ganda.',
    breadcrumb: ['Rent Car', 'Kontrak Digital'],
    permission: 'vehicle.view',
    path: '/app/rent-car/contracts',
  },
  rent_car_calendar: {
    id: 'rent_car_calendar',
    title: 'Kalender Ketersediaan & Timeline Sewa',
    description: 'Visualisasi timeline sewa armada, jadwal booking mendatang, dan monitoring unit yang sedang aktif beroperasi.',
    breadcrumb: ['Rent Car', 'Kalender Sewa'],
    permission: 'vehicle.view',
    path: '/app/rent-car/calendar',
  },
  rent_car_customers: {
    id: 'rent_car_customers',
    title: 'CRM Pelanggan & AI Fraud KYC Shield',
    description: 'Verifikasi identitas e-KTP/SIM, penilaian skor risiko anti-fraud, dan pencegahan penggelapan armada.',
    breadcrumb: ['Rent Car', 'Pelanggan & KYC'],
    permission: 'vehicle.view',
    path: '/app/rent-car/customers',
  },
  rent_car_damages: {
    id: 'rent_car_damages',
    title: 'Klaim & Inspeksi Kerusakan 360°',
    description: 'Peta kerusakan visual 360°, estimasi biaya perbaikan, klaim asuransi CDW, dan pemotongan deposit escrow.',
    breadcrumb: ['Rent Car', 'Klaim & Kerusakan'],
    permission: 'vehicle.view',
    path: '/app/rent-car/damages',
  },
  rent_car_invoices: {
    id: 'rent_car_invoices',
    title: 'Faktur, Pembayaran & Piutang Rental',
    description: 'Penerbitan faktur sewa, pelunasan bertahap (DP, Full Payment), perhitungan PPN 11%, dan rekonsiliasi deposit escrow.',
    breadcrumb: ['Rent Car', 'Faktur & Piutang'],
    permission: 'vehicle.view',
    path: '/app/rent-car/invoices',
  },
  rent_car_security: {
    id: 'rent_car_security',
    title: 'Keamanan Telematika & Remote Starter Kill',
    description: 'Pemantauan perimeter geofence rental, deteksi parkir malam hari, sabotase GPS, dan kunci starter jarak jauh (Immobilizer).',
    breadcrumb: ['Rent Car', 'Keamanan & Anti-Theft'],
    permission: 'vehicle.view',
    path: '/app/rent-car/security',
  },
  rent_car_tariffs: {
    id: 'rent_car_tariffs',
    title: 'Matriks Tarif Sewa & Deposit Escrow',
    description: 'Pengaturan rate card harian/mingguan/bulanan, paket sopir, all-in, dan monitoring rekening escrow deposit jaminan.',
    breadcrumb: ['Rent Car', 'Tarif & Deposit'],
    permission: 'vehicle.view',
    path: '/app/rent-car/tariffs',
  },
  rent_car_analytics: {
    id: 'rent_car_analytics',
    title: 'Analitik Laba Rugi & Profitabilitas Unit',
    description: 'Evaluasi RevPAV (Revenue per Available Vehicle), utilisasi armada, ROI unit kendaraan, dan margin laba bersih.',
    breadcrumb: ['Rent Car', 'Analitik Laba Rugi'],
    permission: 'vehicle.view',
    path: '/app/rent-car/analytics',
  },
  rent_car_ai: {
    id: 'rent_car_ai',
    title: 'AI Copilot & Smart Rental Radar',
    description: 'Deteksi anomali rute AI, prediksi keterlambatan pengembalian armada, dan rekomendasi harga dinamis (*dynamic pricing*).',
    breadcrumb: ['Rent Car', 'AI Copilot & Radar'],
    permission: 'vehicle.view',
    path: '/app/rent-car/ai',
  },
  rent_car_reports: {
    id: 'rent_car_reports',
    title: 'Pusat Laporan & Audit Rental Mobil',
    description: 'Ekspor laporan operasional rental, log transaksi deposit, rekonsiliasi kas, dan kepatuhan armada legalitas.',
    breadcrumb: ['Rent Car', 'Pusat Laporan'],
    permission: 'vehicle.view',
    path: '/app/rent-car/reports',
  },
  rent_car_inspection: {
    id: 'rent_car_inspection',
    title: 'Inspeksi & Serah Terima Digital 360°',
    description: 'Inspeksi visual bodi, pin kerusakan 360°, checklist kelengkapan dan e-signature serah terima.',
    breadcrumb: ['Rent Car', 'Inspeksi Serah Terima'],
    permission: 'vehicle.view',
    path: '/app/rent-car/inspection',
  },
  rent_car_crm: {
    id: 'rent_car_crm',
    title: 'Manajemen Data & KYC Pelanggan Rental',
    description: 'Database pelanggan, verifikasi identitas, dan manajemen blacklist anti penggelapan.',
    breadcrumb: ['Rent Car', 'Pelanggan CRM'],
    permission: 'vehicle.view',
    path: '/app/rent-car/crm',
  },
  rent_car_telematics: {
    id: 'rent_car_telematics',
    title: 'Telematika & Geofence Mobil Rental',
    description: 'Live GPS perimeter, deteksi pelanggaran batas wilayah, dan remote starter-kill.',
    breadcrumb: ['Rent Car', 'Telematika Live'],
    permission: 'vehicle.view',
    path: '/app/rent-car/telematics',
  },
  logistics: {
    id: 'logistics',
    title: 'Logistics Management System (TMS)',
    description: 'Pusat operasional transportasi logistik nusantara: Sales Order Booking, Surat Jalan e-Waybill, Staging Hub, Cross-Docking & Last-Mile ePOD.',
    breadcrumb: ['Logistics', 'Overview'],
    permission: 'trip.view',
    path: '/app/logistics',
  },
  logistics_control_tower: {
    id: 'logistics_control_tower',
    title: 'Menara Kendali Logistik (Control Tower)',
    description: 'Real-time monitoring KPI muatan kargo, SLA On-Time Delivery, kapasitas hub, dan status armada linehaul.',
    breadcrumb: ['Logistics', 'Menara Kendali'],
    permission: 'trip.view',
    path: '/app/logistics/control-tower',
  },
  logistics_orders: {
    id: 'logistics_orders',
    title: 'Order Pengiriman (Sales & Booking TMS)',
    description: 'Kelola pemesanan logistik B2B, merchant marketplace, koli volumetrik, dan booking armada pengiriman.',
    breadcrumb: ['Logistics', 'Order Pengiriman'],
    permission: 'trip.view',
    path: '/app/logistics/orders',
  },
  logistics_shipments: {
    id: 'logistics_shipments',
    title: 'Surat Jalan Elektronik (e-Waybill & Connote)',
    description: 'Format Surat Jalan standar Kemenhub & Asperindo dengan verifikasi QR Code legalitas muatan.',
    breadcrumb: ['Logistics', 'Surat Jalan'],
    permission: 'trip.view',
    path: '/app/logistics/shipments',
  },
  logistics_pickups: {
    id: 'logistics_pickups',
    title: 'Pickup & First-Mile Dispatching',
    description: 'Jadwal penjemputan paket dari gudang merchant/shipper dan serah terima kargo ke armada pickup.',
    breadcrumb: ['Logistics', 'Pickup & First-Mile'],
    permission: 'trip.view',
    path: '/app/logistics/pickups',
  },
  logistics_deliveries: {
    id: 'logistics_deliveries',
    title: 'Last-Mile Delivery & Electronic POD (e-POD)',
    description: 'Verifikasi tanda tangan digital penerima barang, foto geotag penyerahan, dan konfirmasi penyelesaian resi.',
    breadcrumb: ['Logistics', 'Last-Mile & ePOD'],
    permission: 'trip.view',
    path: '/app/logistics/deliveries',
  },
  logistics_manifests: {
    id: 'logistics_manifests',
    title: 'Manifest & Konsolidasi Kargo Antar-Hub',
    description: 'Grouping muatan kargo tronton & wingbox, tracking nomor segel fisik, dan utilisasi kapasitas CBM/Tonase.',
    breadcrumb: ['Logistics', 'Manifest & Konsolidasi'],
    permission: 'trip.view',
    path: '/app/logistics/manifests',
  },
  logistics_packages: {
    id: 'logistics_packages',
    title: 'Barcode Scanner & Koli Paket',
    description: 'Scanner barcode genggam (PDA/Laser) untuk cek timbangan otomatis, dimensi koli, & sorting conveyor.',
    breadcrumb: ['Logistics', 'Barcode Scanner'],
    permission: 'trip.view',
    path: '/app/logistics/packages',
  },
  logistics_routes: {
    id: 'logistics_routes',
    title: 'Perencanaan Rute & Optimasi Muatan (VRP)',
    description: 'Algoritma Vehicle Routing Problem untuk multi-drop last-mile & efisiensi BBM linehaul antar-provinsi.',
    breadcrumb: ['Logistics', 'Perencanaan Rute'],
    permission: 'route.view',
    path: '/app/logistics/routes',
  },
  logistics_live_tracking: {
    id: 'logistics_live_tracking',
    title: 'Live GPS Tracking Kargo Linehaul',
    description: 'Telematika GPS real-time armada tronton antar-provinsi, kecepatan truk, geofence hub, & estimasi ETA.',
    breadcrumb: ['Logistics', 'Live GPS Tracking'],
    permission: 'tracking.view',
    path: '/app/logistics/tracking',
  },
  logistics_hubs: {
    id: 'logistics_hubs',
    title: 'Jaringan Hub, Gudang & Transit Depo',
    description: 'Pemantauan kapasitas storage CBM, staging bay, gate loading/unloading, dan armada standby.',
    breadcrumb: ['Logistics', 'Hub & Transit Depo'],
    permission: 'vehicle.view',
    path: '/app/logistics/hubs',
  },
  logistics_sortation: {
    id: 'logistics_sortation',
    title: 'Sortation Center & Staging Line Automation',
    description: 'Manajemen jalur conveyor pemilahan paket per zonasi kota tujuan, bin sorting, dan status ready-to-load.',
    breadcrumb: ['Logistics', 'Sortation Center'],
    permission: 'trip.view',
    path: '/app/logistics/sortation',
  },
  logistics_returns: {
    id: 'logistics_returns',
    title: 'Reverse Logistics & Retur Pengirim (RTS)',
    description: 'Kelola barang gagal kirim (alamat tidak ditemukan/COD ditolak) dan alur pengembalian ke gudang asal merchant.',
    breadcrumb: ['Logistics', 'Retur Pengirim (RTS)'],
    permission: 'trip.view',
    path: '/app/logistics/returns',
  },
  logistics_exceptions: {
    id: 'logistics_exceptions',
    title: 'Pusat Penanganan Kendala & Tiket Insiden',
    description: 'Tiket insiden operasional: ban meletus, kecelakaan, paket basah/rusak, dan keterlambatan cuaca ekstrem.',
    breadcrumb: ['Logistics', 'Kendala & Tiket'],
    permission: 'alert.view',
    path: '/app/logistics/exceptions',
  },
  logistics_cod: {
    id: 'logistics_cod',
    title: 'Manajemen COD & Rekonsiliasi Kas Driver',
    description: 'Validasi setoran uang tunai COD kurir, rekonsiliasi kasir hub, dan pencairan dana ke merchant B2B.',
    breadcrumb: ['Logistics', 'COD & Rekonsiliasi'],
    permission: 'cost.view',
    path: '/app/logistics/cod',
  },
  logistics_customers: {
    id: 'logistics_customers',
    title: 'Portal Akun Merchant B2B & Shipper CRM',
    description: 'Kelola kontrak SLA korporat, Term of Payment (TOP piutang pengiriman), invoice bulanan, dan diskon volume.',
    breadcrumb: ['Logistics', 'Merchant B2B CRM'],
    permission: 'driver.view',
    path: '/app/logistics/customers',
  },
  logistics_sla: {
    id: 'logistics_sla',
    title: 'Radar SLA & On-Time Delivery Performance',
    description: 'Pemantauan kepatuhan Service Level Agreement pengiriman sameday, nextday, regular, dan cold chain.',
    breadcrumb: ['Logistics', 'Radar Kepatuhan SLA'],
    permission: 'analytics.view',
    path: '/app/logistics/sla',
  },
  logistics_analytics: {
    id: 'logistics_analytics',
    title: 'Analitik Biaya Tonase & Unit Economics',
    description: 'Evaluasi Cost per Kg-KM, marjin keuntungan per koridor rute, utilisasi armada tronton, dan konsumsi solar.',
    breadcrumb: ['Logistics', 'Analitik Biaya Tonase'],
    permission: 'cost.view',
    path: '/app/logistics/analytics',
  },
  logistics_ai: {
    id: 'logistics_ai',
    title: 'AI Logistics Dispatcher & Fleet Copilot',
    description: 'Asisten cerdas untuk dynamic auto-dispatching, prediksi ETA cuaca, rekomendasi penggabungan muatan kargo.',
    breadcrumb: ['Logistics', 'AI Logistics Copilot'],
    permission: 'ai.view',
    path: '/app/logistics/ai',
  },
  logistics_reports: {
    id: 'logistics_reports',
    title: 'Pusat Laporan & Ekspor Data Logistik',
    description: 'Unduh laporan performa pengiriman, audit kepatuhan segel, rekonsiliasi COD, dan histori armada.',
    breadcrumb: ['Logistics', 'Pusat Laporan'],
    permission: 'report.view',
    path: '/app/logistics/reports',
  },
  bus_management: {
    id: 'bus_management',
    title: 'Bus Management System (PO Bus)',
    description: 'Sistem operasional armada bus AKAP, AKDP, pariwisata, ticketing online, manifest Kemenhub, UJS, dan telematika GPS.',
    breadcrumb: ['PO Bus', 'Overview'],
    permission: 'trip.view',
    path: '/app/bus',
  },
  bus_control_tower: {
    id: 'bus_control_tower',
    title: 'Menara Kendali Operasional PO Bus (Control Tower)',
    description: 'Monitoring real-time ritase bus jalan, okupansi penumpang koridor Trans-Jawa & Sumatera, dan keselamatan armada.',
    breadcrumb: ['PO Bus', 'Menara Kendali'],
    permission: 'trip.view',
    path: '/app/bus/control-tower',
  },
  bus_trips_schedule: {
    id: 'bus_trips_schedule',
    title: 'Jadwal Keberangkatan & Ritase Trayek Bus',
    description: 'Manajemen jadwal trayek reguler, bus tambahan/bantuan (sapu jagat), penugasan kru supir, dan penetapan tarif kelas.',
    breadcrumb: ['PO Bus', 'Jadwal & Ritase'],
    permission: 'trip.view',
    path: '/app/bus/trips',
  },
  bus_ticketing_seat: {
    id: 'bus_ticketing_seat',
    title: 'Reservasi Tiket & Denah Kursi Interaktif (Seat Map)',
    description: 'Visualisasi layout denah kursi Sleeper Suites, Double Decker, Executive, reservasi online OTA & loket agen.',
    breadcrumb: ['PO Bus', 'Tiket & Kursi'],
    permission: 'trip.view',
    path: '/app/bus/ticketing',
  },
  bus_passenger_manifest: {
    id: 'bus_passenger_manifest',
    title: 'Manifest Penumpang Resmi & E-Boarding Pass',
    description: 'Manifest perjalanan standar Kemenhub & Jasa Raharja, validasi QR code boarding penumpang di terminal asal.',
    breadcrumb: ['PO Bus', 'Manifest Penumpang'],
    permission: 'trip.view',
    path: '/app/bus/manifest',
  },
  bus_routes_terminals: {
    id: 'bus_routes_terminals',
    title: 'Master Trayek, Terminal Lintasan & Rest Area Tol',
    description: 'Konfigurasi rute trayek antarkota, pool agen perhentian, estimasi durasi tempuh, dan rumah makan rekanan.',
    breadcrumb: ['PO Bus', 'Trayek & Terminal'],
    permission: 'route.view',
    path: '/app/bus/routes',
  },
  bus_cargo_express: {
    id: 'bus_cargo_express',
    title: 'Kargo Paket Bus Kilat (Ekspedisi Bagasi Bus)',
    description: 'Layanan pengiriman paket same-day/next-day via bagasi bawah bus antar-terminal dengan nomor resi kilat.',
    breadcrumb: ['PO Bus', 'Kargo Paket Bus'],
    permission: 'trip.view',
    path: '/app/bus/cargo',
  },
  bus_agents_counter: {
    id: 'bus_agents_counter',
    title: 'Manajemen Agen Loket Terminal & Komisi',
    description: 'Monitoring setoran kasir agen loket tiket terminal, plafon deposit penjualan, dan perhitungan komisi tiket.',
    breadcrumb: ['PO Bus', 'Agen & Loket'],
    permission: 'trip.view',
    path: '/app/bus/agents',
  },
  bus_crew_roster: {
    id: 'bus_crew_roster',
    title: 'Roster Kru Supir, Kernet & Pemantau Kelelahan (Fatigue)',
    description: 'Penjadwalan supir utama, supir cadangan, kernet, kepatuhan batas jam mengemudi maks 8 jam, dan sertifikasi SIM BI/BII Umum.',
    breadcrumb: ['PO Bus', 'Kru & Roster Supir'],
    permission: 'driver.view',
    path: '/app/bus/crews',
  },
  bus_ramp_check: {
    id: 'bus_ramp_check',
    title: 'Inspeksi Ramp Check Kemenhub & Keselamatan Bus',
    description: 'Standar pengujian kelaikan jalan armada bus sebelum diberangkatkan: uji rem angin, ban, APAR, palu darurat, dan izin trayek KPS.',
    breadcrumb: ['PO Bus', 'Ramp Check Kemenhub'],
    permission: 'inspection.view',
    path: '/app/bus/ramp-check',
  },
  bus_ujs_toll_fuel: {
    id: 'bus_ujs_toll_fuel',
    title: 'Uang Jalan Supir (UJS), Solar BBM & E-Toll Trans-Jawa',
    description: 'Kalkulasi biaya operasional ritase jalan, kuota liter solar bus, saldo kartu tol, dan jatah makan kru/penumpang.',
    breadcrumb: ['PO Bus', 'UJS, BBM & Tol'],
    permission: 'cost.view',
    path: '/app/bus/ujs-fuel',
  },
  bus_live_tracking: {
    id: 'bus_live_tracking',
    title: 'Live GPS Telematika Bus & Speed Radar Tol Trans-Jawa',
    description: 'Pelacakan satelit GPS waktu-nyata posisi bus di jalan tol, kecepatan laju, dan geofence terminal.',
    breadcrumb: ['PO Bus', 'Live GPS Tracking'],
    permission: 'tracking.view',
    path: '/app/bus/live-tracking',
  },
  bus_charter_tour: {
    id: 'bus_charter_tour',
    title: 'Sewa Bus Pariwisata & Charter Khusus Rombongan',
    description: 'Pemesanan sewa rombongan pariwisata, study tour sekolah, ziarah wali, dan penerbitan Surat Perintah Jalan (SPJ).',
    breadcrumb: ['PO Bus', 'Sewa Bus Pariwisata'],
    permission: 'trip.view',
    path: '/app/bus/charter',
  },
  bus_occupancy_analytics: {
    id: 'bus_occupancy_analytics',
    title: 'Analitik Okupansi Kursi, RASK & Profitabilitas Trayek',
    description: 'Evaluasi performa load factor per kelas bus, revenue per available seat-kilometer, dan utilisasi armada.',
    breadcrumb: ['PO Bus', 'Analitik Okupansi & RASK'],
    permission: 'analytics.view',
    path: '/app/bus/analytics',
  },
  bus_ai_dispatcher: {
    id: 'bus_ai_dispatcher',
    title: 'AI PO Bus Demand Forecasting & Smart Dispatcher',
    description: 'AI Copilot peramal lonjakan penumpang mudik/weekend, mitigasi keterlambatan rute macet, dan saran bus cadangan.',
    breadcrumb: ['PO Bus', 'AI PO Bus Copilot'],
    permission: 'ai.view',
    path: '/app/bus/ai',
  },
  bus_reports: {
    id: 'bus_reports',
    title: 'Pusat Laporan & Ekspor Dokumen PO Bus',
    description: 'Unduh rekapitulasi penjualan tiket, manifest Kemenhub, pembukuan uang jalan supir (UJS), dan kelaikan ramp check.',
    breadcrumb: ['PO Bus', 'Pusat Laporan'],
    permission: 'report.view',
    path: '/app/bus/reports',
  },
  heavy_equipment: {
    id: 'heavy_equipment',
    title: 'Sistem Manajemen Konstruksi & Alat Berat',
    description: 'Pusat operasional armada alat berat pertambangan dan konstruksi: Menara kendali proyek, monitoring Hour Meter (HM), telematika mesin, dan logistik fuel bowser.',
    breadcrumb: ['Alat Berat', 'Menara Kendali'],
    permission: 'trip.view',
    path: '/app/heavy-equipment',
  },
  heavy_equipment_control_tower: {
    id: 'heavy_equipment_control_tower',
    title: 'Menara Kendali Operasional Alat Berat & Job Site',
    description: 'Monitoring real-time utilisasi Hour Meter (HM), ketersediaan mekanis Physical Availability (PA/UA), ritase tambang, dan status job site aktif.',
    breadcrumb: ['Alat Berat', 'Menara Kendali'],
    permission: 'trip.view',
    path: '/app/heavy-equipment/control-tower',
  },
  heavy_equipment_assets: {
    id: 'heavy_equipment_assets',
    title: 'Master Data Alat Berat & Sertifikasi SILO',
    description: 'Inventarisasi excavator, bulldozer, dump truck HD, mobile crane, spesifikasi bucket, nomor seri mesin, dan perizinan kelayakan operasi SILO Kemenaker.',
    breadcrumb: ['Alat Berat', 'Master Alat & SILO'],
    permission: 'vehicle.view',
    path: '/app/heavy-equipment/assets',
  },
  heavy_equipment_projects: {
    id: 'heavy_equipment_projects',
    title: 'Manajemen Job Site & Volume BCM Proyek',
    description: 'Pemantauan alokasi armada per site proyek, progress galian/timbunan (Bank Cubic Meter), konsumsi solar, dan penanggung jawab PM/HSE.',
    breadcrumb: ['Alat Berat', 'Job Site & Proyek'],
    permission: 'trip.view',
    path: '/app/heavy-equipment/projects',
  },
  heavy_equipment_timesheets: {
    id: 'heavy_equipment_timesheets',
    title: 'Daily Timesheet & Rekapitulasi Hour Meter (HM)',
    description: 'Pencatatan jam kerja operator, HM awal/akhir shift, jam produksi efektif, standby hujan/antrian, jam breakdown mekanik, dan approval pengawas.',
    breadcrumb: ['Alat Berat', 'Daily Timesheet'],
    permission: 'trip.view',
    path: '/app/heavy-equipment/timesheets',
  },
  heavy_equipment_p2h: {
    id: 'heavy_equipment_p2h',
    title: 'P2H (Pemeriksaan Harian Alat Berat) & K3 Tambang',
    description: 'Form checklist digital pre-shift K3 Kemenaker/ESDM: Pemeriksaan oli, hidrolik, rem angin, APAR, alarm mundur, dan evaluasi Fit-to-Work.',
    breadcrumb: ['Alat Berat', 'Checklist P2H Harian'],
    permission: 'inspection.view',
    path: '/app/heavy-equipment/p2h',
  },
  heavy_equipment_fuel: {
    id: 'heavy_equipment_fuel',
    title: 'Manajemen BBM Solar & Distribusi Fuel Bowser Truck',
    description: 'Pencatatan pengisian solar pit stop keliling, nomor voucher BBM, audit burn rate (Liter/HM), dan mitigasi kecurangan bahan bakar.',
    breadcrumb: ['Alat Berat', 'BBM Solar & Fuel Bowser'],
    permission: 'fuel.view',
    path: '/app/heavy-equipment/fuel',
  },
  heavy_equipment_maintenance: {
    id: 'heavy_equipment_maintenance',
    title: 'Pemeliharaan Berkala (PS 250–2000 HM) & Work Order',
    description: 'Jadwal servis berkala ganti oli/filter, backlog undercarriage & hidrolik, penugasan mekanik site, dan riwayat perbaikan alat berat.',
    breadcrumb: ['Alat Berat', 'Servis Berkala PS'],
    permission: 'maintenance.view',
    path: '/app/heavy-equipment/maintenance',
  },
  heavy_equipment_safety: {
    id: 'heavy_equipment_safety',
    title: 'K3 Pertambangan, Lisensi SIO Operator & SILO Alat',
    description: 'Monitoring masa berlaku Surat Izin Operator (SIO Kelas 1/2/3), Surat Izin Layak Operasi (SILO) alat, dan safety score pengemudi alat berat.',
    breadcrumb: ['Alat Berat', 'K3 & SIO Operator'],
    permission: 'safety.view',
    path: '/app/heavy-equipment/safety',
  },
  heavy_equipment_billing: {
    id: 'heavy_equipment_billing',
    title: 'Sewa Rental Alat Berat, Minimum Charge & Invoicing',
    description: 'Faktur penagihan sewa alat lepas kunci / all-in operator BBM, jaminan minimum charge 100–250 HM, lembur overtime, dan biaya mob-demob.',
    breadcrumb: ['Alat Berat', 'Faktur Rental & Sewa'],
    permission: 'cost.view',
    path: '/app/heavy-equipment/billing',
  },
  heavy_equipment_ai: {
    id: 'heavy_equipment_ai',
    title: 'AI Heavy Equipment Fleet Copilot & Predictive Failure',
    description: 'Asisten cerdas analisis telematika mesin, optimasi fleet matching excavator-dump truck, dan deteksi anomali konsumsi solar/hidrolik.',
    breadcrumb: ['Alat Berat', 'AI Heavy Copilot'],
    permission: 'ai.view',
    path: '/app/heavy-equipment/ai',
  },
  heavy_equipment_reports: {
    id: 'heavy_equipment_reports',
    title: 'Pusat Laporan & Rekapitulasi Alat Berat',
    description: 'Pusat ekspor dokumen resmi timesheet, kepatuhan P2H, konsumsi solar, performa ketersediaan PA/UA, dan penagihan rental ke CSV/Excel.',
    breadcrumb: ['Alat Berat', 'Pusat Laporan'],
    permission: 'report.view',
    path: '/app/heavy-equipment/reports',
  },
  mining: {
    id: 'mining',
    title: 'Mining Fleet & Operations Management System',
    description: 'Sistem operasional penambangan terpadu: Pit tambang, geofence elevasi RL, siklus hauling & dispatch Shovel-Truck, jembatan timbang, BBM Solar B35, K3 SMKP ESDM, dan AI Copilot.',
    breadcrumb: ['Mining', 'Papan Operasional'],
    permission: 'trip.view',
    path: '/app/mining',
  },
  mining_control_tower: {
    id: 'mining_control_tower',
    title: 'Menara Kendali Tambang (Control Tower)',
    description: 'Pusat pemantauan real-time operasional pit, pencapaian target harian BCM/Ton, utilisasi armada, dan status geofence aktif.',
    breadcrumb: ['Mining', 'Control Tower'],
    permission: 'trip.view',
    path: '/app/mining/control-tower',
  },
  mining_sites: {
    id: 'mining_sites',
    title: 'Site Tambang & Konsesi IUP',
    description: 'Manajemen lokasi tambang, izin konsesi IUP/PKP2B, luas area tambang, dan Kepala Teknik Tambang (KTT).',
    breadcrumb: ['Mining', 'Site & Konsesi'],
    permission: 'vehicle.view',
    path: '/app/mining/sites',
  },
  mining_pits: {
    id: 'mining_pits',
    title: 'Pit Tambang & Geofence (Open Pit RL)',
    description: 'Pemantauan pit aktif, elevasi Reduced Level (RL), alokasi shovel excavator, geofence radius peledakan, & risiko lereng highwall.',
    breadcrumb: ['Mining', 'Pit & Geofence'],
    permission: 'trip.view',
    path: '/app/mining/pits',
  },
  mining_benches: {
    id: 'mining_benches',
    title: 'Jenjang Kerja (Bench & Loading Zones)',
    description: 'Pengelolaan jenjang kerja pit, dimensi tinggi & lebar bench, tinggi safety berm penahan, dan jalur rute hauling.',
    breadcrumb: ['Mining', 'Jenjang (Bench)'],
    permission: 'trip.view',
    path: '/app/mining/benches',
  },
  mining_materials: {
    id: 'mining_materials',
    title: 'Klasifikasi Material & Grade (%Ni/GAR)',
    description: 'Klasifikasi komoditas batubara GAR, nikel saprolite/limonite, tembaga/emas, overburden OB, densitas (Ton/m³), & lokasi stockpile.',
    breadcrumb: ['Mining', 'Material & Grade'],
    permission: 'vehicle.view',
    path: '/app/mining/materials',
  },
  mining_equipment: {
    id: 'mining_equipment',
    title: 'Armada Alat Berat Tambang & Telematika',
    description: 'Monitoring telematika mesin shovel & dump truck, kapasitas muatan Ton/m³, jam operasi HM, SILO Disnaker, dan level BBM solar.',
    breadcrumb: ['Mining', 'Armada Alat Berat'],
    permission: 'vehicle.view',
    path: '/app/mining/equipment',
  },
  mining_operators: {
    id: 'mining_operators',
    title: 'Operator Tambang, SIO ESDM & KIMPER',
    description: 'Manajemen perizinan mengemudi tambang KIMPER, lisensi SIO, skor fatigue DSS AI kabin, dan rekam jejak jam kerja aman.',
    breadcrumb: ['Mining', 'Operator & KIMPER'],
    permission: 'driver.view',
    path: '/app/mining/operators',
  },
  mining_shifts: {
    id: 'mining_shifts',
    title: 'Shift Operasi Tambang & P5M Meeting',
    description: 'Monitoring roster giliran kerja (Day/Night Shift), rekap ritase & tonase, catatan briefing K3 P5M, dan penundaan cuaca hujan (Rain Delay).',
    breadcrumb: ['Mining', 'Shift Roster & P5M'],
    permission: 'trip.view',
    path: '/app/mining/shifts',
  },
  mining_dispatch: {
    id: 'mining_dispatch',
    title: 'Papan Kontrol Dispatch & Siklus Hauling',
    description: 'Siklus otomatisasi hauling: Loading Shovel -> Hauling -> Jembatan Timbang -> Dumping -> Return -> Queue, optimasi Match Factor real-time.',
    breadcrumb: ['Mining', 'Dispatch & Siklus Hauling'],
    permission: 'trip.view',
    path: '/app/mining/dispatch',
  },
  mining_weighbridge: {
    id: 'mining_weighbridge',
    title: 'Jembatan Timbang & Tiket Payload Digital',
    description: 'Penimbangan muatan digital RFID: Berat Kotor (Gross), Berat Kosong (Tare), Netto, verifikasi over/underload, & pencetakan tiket timbang.',
    breadcrumb: ['Mining', 'Jembatan Timbang'],
    permission: 'trip.view',
    path: '/app/mining/weighbridge',
  },
  mining_fuel: {
    id: 'mining_fuel',
    title: 'Manajemen BBM Solar B35 & Mobile Fuel Bowser',
    description: 'Pengisian bahan bakar di front pit, monitoring burn rate armada (L/HM, L/Ton, L/BCM), dan level tangki induk depot.',
    breadcrumb: ['Mining', 'BBM Solar & Bowser'],
    permission: 'fuel.view',
    path: '/app/mining/fuel',
  },
  mining_safety: {
    id: 'mining_safety',
    title: 'K3 Pertambangan (SMKP ESDM) & Fatigue DSS Radar',
    description: 'Pencapaian Zero LTI, audit kepatuhan SMKP ESDM Permen 26/2018, form inspeksi P2H pre-shift, dan mitigasi kantuk kamera DSS.',
    breadcrumb: ['Mining', 'K3 SMKP & Fatigue'],
    permission: 'safety.view',
    path: '/app/mining/safety',
  },
  mining_maintenance: {
    id: 'mining_maintenance',
    title: 'Plant Maintenance & OTR Giant Tyre Management',
    description: 'Jadwal servis berkala PS 250 - 2000 HM, backlog mekanik, pemantauan keausan ban raksasa OTR (Tread Depth & TKPH Rating).',
    breadcrumb: ['Mining', 'Plant & Ban OTR'],
    permission: 'maintenance.view',
    path: '/app/mining/maintenance',
  },
  mining_productivity: {
    id: 'mining_productivity',
    title: 'Produktivitas, Biaya & P&L Unit Tambang',
    description: 'Analisis profit & loss per Code Number unit: Pendapatan ritase vs Biaya Solar, Ban OTR, Suku Cadang, Upah Operator, & Cost/Ton/BCM.',
    breadcrumb: ['Mining', 'Produktivitas & P&L'],
    permission: 'cost.view',
    path: '/app/mining/productivity',
  },
  mining_ai: {
    id: 'mining_ai',
    title: 'AI Mining Operations Copilot & Match Factor',
    description: 'Executive Daily Briefing cerdas untuk KTT/Superintendent, simulator optimasi Shovel-Truck Match Factor, dan asisten konsultasi K3.',
    breadcrumb: ['Mining', 'AI Mining Copilot'],
    permission: 'ai.view',
    path: '/app/mining/ai',
  },
  mining_reports: {
    id: 'mining_reports',
    title: 'Pusat Laporan Tambang (LHT & LBT RKAB ESDM)',
    description: 'Pembuatan dokumen resmi Laporan Harian Tambang (LHT), Laporan Bulanan (LBT), rekapitulasi ritase timbang, BBM, dan jam kerja selamat K3.',
    breadcrumb: ['Mining', 'Pusat Laporan LHT/LBT'],
    permission: 'report.view',
    path: '/app/mining/reports',
  },
  pud: {
    id: 'pud',
    title: 'Pickup & Delivery Management System (PUD)',
    description: 'Sistem komprehensif penjemputan first-mile, pengantaran last-mile, alokasi kurir instan/same-day, validasi ePOD digital, dan rekonsiliasi COD.',
    breadcrumb: ['Logistics', 'PUD Management'],
    permission: 'trip.view',
    path: '/app/pud',
  },
  pud_control_tower: {
    id: 'pud_control_tower',
    title: 'Menara Kendali PUD (PUD Control Tower)',
    description: 'Dashboard pengawasan ritase penjemputan dan pengantaran real-time, tingkat On-Time Delivery (OTD), dan first-attempt rate.',
    breadcrumb: ['PUD', 'Menara Kendali'],
    permission: 'trip.view',
    path: '/app/pud/control-tower',
  },
  pud_pickups: {
    id: 'pud_pickups',
    title: 'Permintaan Penjemputan Paket (First-Mile Pickups)',
    description: 'Pengelolaan order pickup dari merchant e-commerce & seller B2B, penjadwalan time window, dan penugasan armada pickup box/blind van.',
    breadcrumb: ['PUD', 'Permintaan Pickup'],
    permission: 'trip.view',
    path: '/app/pud/pickups',
  },
  pud_deliveries: {
    id: 'pud_deliveries',
    title: 'Pengantaran Drop-off & Last-Mile Delivery',
    description: 'Daftar paket keluar untuk pengantaran ke penerima akhir, status perjalanan on-delivery, dan waktu estimasi tiba (ETA).',
    breadcrumb: ['PUD', 'Pengantaran Last-Mile'],
    permission: 'trip.view',
    path: '/app/pud/deliveries',
  },
  pud_dispatch: {
    id: 'pud_dispatch',
    title: 'Smart Dispatching & Alokasi Kurir Cerdas',
    description: 'Mesin alokasi kurir otomatis berdasarkan radius GPS terdekat, kapasitas sisa kendaraan, dan jenis SLA paket.',
    breadcrumb: ['PUD', 'Smart Dispatching'],
    permission: 'trip.view',
    path: '/app/pud/dispatch',
  },
  pud_epod: {
    id: 'pud_epod',
    title: 'Bukti Serah Terima Digital (ePOD & ePOP)',
    description: 'Arsip bukti penerimaan paket digital lengkap dengan foto dokumentasi serah terima, koordinat GPS geotag, OTP verifikasi, dan tanda tangan digital.',
    breadcrumb: ['PUD', 'Bukti Pengiriman (ePOD)'],
    permission: 'trip.view',
    path: '/app/pud/epod',
  },
  pud_live_couriers: {
    id: 'pud_live_couriers',
    title: 'Live Tracking GPS Kurir & Radar Armada PUD',
    description: 'Pelacakan real-time lokasi kurir motor & blind van, sisa baterai smartphone, status ketersediaan, dan riwayat pergerakan.',
    breadcrumb: ['PUD', 'Live Tracking Kurir'],
    permission: 'tracking.view',
    path: '/app/pud/live-couriers',
  },
  pud_route_optimizer: {
    id: 'pud_route_optimizer',
    title: 'Optimasi Rute Multi-Stop (VRP & TSP Routing)',
    description: 'Algoritma pengurutan perhentian otomatis multi-stop guna menghemat jarak tempuh, biaya bahan bakar, dan waktu tempuh kurir.',
    breadcrumb: ['PUD', 'Optimasi Rute Multi-Stop'],
    permission: 'route.view',
    path: '/app/pud/route-optimizer',
  },
  pud_failed_undelivered: {
    id: 'pud_failed_undelivered',
    title: 'Kendala & Gagal Antar (NDR & RTO Hub)',
    description: 'Penanganan tiket gagal kirim (Non-Delivery Report), penjadwalan ulang antar (Reschedule), dan alur pengembalian paket ke pengirim (RTO).',
    breadcrumb: ['PUD', 'Kendala Gagal Antar'],
    permission: 'alert.view',
    path: '/app/pud/failed-undelivered',
  },
  pud_cod: {
    id: 'pud_cod',
    title: 'COD & Rekonsiliasi Kasir Kurir (Remittance)',
    description: 'Manajemen uang tunai tagihan Cash on Delivery, transaksi QRIS on delivery, dan rekonsiliasi setoran fisik ke kasir hub.',
    breadcrumb: ['PUD', 'COD & Rekonsiliasi'],
    permission: 'cost.view',
    path: '/app/pud/cod',
  },
  pud_tracking_link: {
    id: 'pud_tracking_link',
    title: 'Tautan Pelacakan Publik & Notifikasi Pelanggan',
    description: 'Generator link tracking publik interaktif untuk penerima paket dan pengiriman notifikasi status otomatis via WhatsApp/SMS.',
    breadcrumb: ['PUD', 'Tautan Pelacakan Publik'],
    permission: 'trip.view',
    path: '/app/pud/tracking-link',
  },
  pud_couriers: {
    id: 'pud_couriers',
    title: 'Roster Kurir & Kinerja Insentif Harian',
    description: 'Profil kurir motor & driver van, rating kepuasan CSAT, jumlah paket selesai antar hari ini, dan kalkulasi bonus insentif.',
    breadcrumb: ['PUD', 'Roster Kurir & Insentif'],
    permission: 'driver.view',
    path: '/app/pud/couriers',
  },
  pud_tariffs: {
    id: 'pud_tariffs',
    title: 'Tarif Zona & Kalkulator Ongkos Kirim PUD',
    description: 'Matriks penetapan ongkos kirim berbasis zona, jarak per kilometer, dan berat kilogram untuk Instant, Same-Day, dan Cargo Bulky.',
    breadcrumb: ['PUD', 'Tarif & Kalkulator Ongkir'],
    permission: 'cost.view',
    path: '/app/pud/tariffs',
  },
  pud_ai_copilot: {
    id: 'pud_ai_copilot',
    title: 'AI PUD Operations Copilot & Decision Radar',
    description: 'Asisten cerdas Gemini multi-modal untuk analisis kepadatan lalu lintas rute, mitigasi risiko SLA, dan otomatisasi dispatch.',
    breadcrumb: ['PUD', 'AI PUD Copilot'],
    permission: 'ai.view',
    path: '/app/pud/ai-copilot',
  },
  pud_reports: {
    id: 'pud_reports',
    title: 'Pusat Laporan & KPI Pickup & Delivery (PUD)',
    description: 'Export laporan ritase, performa OTD & FADR, audit buku kas COD, dan peringkat produktivitas kurir ke format Excel & PDF.',
    breadcrumb: ['PUD', 'Pusat Laporan & KPI'],
    permission: 'report.view',
    path: '/app/pud/reports',
  },
  dtms: {
    id: 'dtms',
    title: 'Dump Truck Management System (DTMS)',
    description: 'Sistem Terpadu Manajemen Siklus Hauling, Match Factor Shovel-Truck, Jembatan Timbang, Telemetri Hoist Hidrolik & Efisiensi Solar.',
    breadcrumb: ['DTMS', 'Control Tower'],
    permission: 'trip.view',
    path: '/app/dtms',
  },
  dtms_control_tower: {
    id: 'dtms_control_tower',
    title: 'Menara Kendali Dump Truck (Control Tower)',
    description: 'Monitoring armada DT live status (loading, hauling, queue, dumping, returning), ritase target vs aktual, tonase, dan ketersediaan PA/UA.',
    breadcrumb: ['DTMS', 'Control Tower'],
    permission: 'trip.view',
    path: '/app/dtms/control-tower',
  },
  dtms_fleets: {
    id: 'dtms_fleets',
    title: 'Master Armada & Spesifikasi Dump Truck',
    description: 'Database registrasi OHT rigid (HD785/777), Heavy Dump Truck 8x4/6x4, ADT, kapasitas vessel m3, rated payload, dan dokumen KIR/KIMPER.',
    breadcrumb: ['DTMS', 'Armada Dump Truck'],
    permission: 'vehicle.view',
    path: '/app/dtms/fleets',
  },
  dtms_cycles: {
    id: 'dtms_cycles',
    title: 'Siklus Hauling & Breakdown Cycle Time',
    description: 'Analisis komponen waktu spotting antre, pemuatan shovel, loaded haul, antre dumping hopper, tipping hoist hidrolik, dan retur kosong.',
    breadcrumb: ['DTMS', 'Siklus Hauling'],
    permission: 'trip.view',
    path: '/app/dtms/cycles',
  },
  dtms_payload: {
    id: 'dtms_payload',
    title: 'Jembatan Timbang & Pencegahan Overload (Weighbridge)',
    description: 'Pencatatan timbangan bruto, tara, netto, verifikasi batas kapasitas muatan rated tonase, dan perlindungan kerusakan sasis/suspensi.',
    breadcrumb: ['DTMS', 'Jembatan Timbang'],
    permission: 'trip.view',
    path: '/app/dtms/payload',
  },
  dtms_haul_roads: {
    id: 'dtms_haul_roads',
    title: 'Peta Haul Road & Batas Kecepatan Segmen',
    description: 'Monitoring jalur hauling tambang: grade kemiringan %, deteksi debu, batas kecepatan segmen jalan, dan jadwal penyiraman water truck.',
    breadcrumb: ['DTMS', 'Haul Road Segments'],
    permission: 'route.view',
    path: '/app/dtms/haul-roads',
  },
  dtms_dispatch: {
    id: 'dtms_dispatch',
    title: 'Smart Dispatching & Match Factor Shovel-Truck',
    description: 'Optimasi rasio keseimbangan armada antara kapasitas excavator/shovel dan dump truck untuk meminimalkan waktu antre dan excavator waiting.',
    breadcrumb: ['DTMS', 'Smart Dispatch & Match Factor'],
    permission: 'trip.view',
    path: '/app/dtms/dispatch',
  },
  dtms_fuel: {
    id: 'dtms_fuel',
    title: 'Konsumsi Biosolar B35 & Efisiensi Fuel Burn',
    description: 'Monitoring rasio liter/ton, liter/km jalan muat vs kosong, pencegahan fuel theft/drain, dan integrasi mobile fuel bowser dispenser.',
    breadcrumb: ['DTMS', 'BBM Solar & Bowser'],
    permission: 'fuel.view',
    path: '/app/dtms/fuel',
  },
  dtms_tires: {
    id: 'dtms_tires',
    title: 'Manajemen Ban OTR & TPMS Sensor Nirkabel',
    description: 'Monitoring tekanan ban PSI & temperatur panas ban nirkabel, kedalaman tapak tread mm, TKPH rating, dan rotasi posisi roda.',
    breadcrumb: ['DTMS', 'Ban OTR & TPMS'],
    permission: 'maintenance.view',
    path: '/app/dtms/tires',
  },
  dtms_telematics: {
    id: 'dtms_telematics',
    title: 'Telemetri Sensor Hoist Hidrolik & Status PTO',
    description: 'Sensor sudut angkat bak dump (0-60°), deteksi power take-off aktif, dan peringatan dumping ilegal di luar area disposal resmi.',
    breadcrumb: ['DTMS', 'Hoist & PTO Telematics'],
    permission: 'tracking.view',
    path: '/app/dtms/telematics',
  },
  dtms_drivers: {
    id: 'dtms_drivers',
    title: 'Roster Operator KIMPER & AI Fatigue Radar DSS',
    description: 'Database lisensi KIMPER tambang & SIM B2 Umum, kamera AI pendeteksi kantuk (yawning/microsleep), dan rekap insentif ritase driver.',
    breadcrumb: ['DTMS', 'Operator & Fatigue DSS'],
    permission: 'driver.view',
    path: '/app/dtms/drivers',
  },
  dtms_safety: {
    id: 'dtms_safety',
    title: 'K3 Tambang, Anti-Rollover & Proximity Collision',
    description: 'Sensor kestabilan lateral dumping, CAS blindspot proximity radar 360°, retarder downhill control, dan audit standar SMKP ESDM.',
    breadcrumb: ['DTMS', 'K3 & Safety Sensor'],
    permission: 'safety.view',
    path: '/app/dtms/safety',
  },
  dtms_maintenance: {
    id: 'dtms_maintenance',
    title: 'Perawatan Berkala PM & Checklist P2H Harian',
    description: 'Jadwal PM Service 250, 500, 1000, 2000 Jam, inspeksi pra-operasi P2H mobile digital, dan kesehatan suspensi strut hidrolik.',
    breadcrumb: ['DTMS', 'Perawatan PM & P2H'],
    permission: 'maintenance.view',
    path: '/app/dtms/maintenance',
  },
  dtms_billing: {
    id: 'dtms_billing',
    title: 'Tarif Hauling, Pendapatan Ritase & Kalkulator P&L',
    description: 'Kalkulator tarif hauling kontrak Rp/Ton/KM, tagihan kontraktor/subkontraktor, potongan solar, dan margin laba bersih unit DT.',
    breadcrumb: ['DTMS', 'Tarif & P&L Ritase'],
    permission: 'cost.view',
    path: '/app/dtms/billing',
  },
  dtms_ai: {
    id: 'dtms_ai',
    title: 'AI Dump Truck Operations Copilot (Gemini Radar)',
    description: 'Asisten cerdas AI Gemini untuk analisis ritase harian, rekomendasi rebalance armada shovel-truck, dan mitigasi bottleneck disposal.',
    breadcrumb: ['DTMS', 'AI Operations Copilot'],
    permission: 'ai.view',
    path: '/app/dtms/ai-copilot',
  },
  dtms_reports: {
    id: 'dtms_reports',
    title: 'Pusat Laporan & Ekspor Analitik Dump Truck (LHT/LBT)',
    description: 'Export Laporan Harian Tambang (LHT), Laporan Bulanan Tambang (LBT), audit payload weighbridge, dan rekap solar ke Excel & PDF.',
    breadcrumb: ['DTMS', 'Pusat Laporan LHT/LBT'],
    permission: 'report.view',
    path: '/app/dtms/reports',
  },
  taxi: {
    id: 'taxi',
    title: 'Taxi Management System (TMS)',
    description: 'Platform AI Telematika & Manajemen Armada Taksi: Monitoring utilisasi jarak Paid KM, argometer tera metrologi, auto-dispatching pangkalan & bandara, serta setoran kasir pool.',
    breadcrumb: ['Taxi', 'Control Tower'],
    permission: 'trip.view',
    path: '/app/taxi',
  },
  taxi_control_tower: {
    id: 'taxi_control_tower',
    title: 'Menara Kendali Taksi (Control Tower)',
    description: 'Monitoring armada taksi live status (hired, vacant, standby pool, charging), utilisasi jarak (Paid KM vs Deadhead), antrean bandara, dan pendapatan real-time.',
    breadcrumb: ['Taxi', 'Control Tower'],
    permission: 'trip.view',
    path: '/app/taxi/control-tower',
  },
  taxi_fleets: {
    id: 'taxi_fleets',
    title: 'Master Armada Taksi (Sedan, MPV, EV & Executive)',
    description: 'Database registrasi nomor lambung, pelat kuning, taksi listrik EV Green, eksekutif Silver Bird, masa berlaku KIR Dishub, dan tera segel argometer.',
    breadcrumb: ['Taxi', 'Armada Taksi'],
    permission: 'vehicle.view',
    path: '/app/taxi/fleets',
  },
  taxi_taximeter: {
    id: 'taxi_taximeter',
    title: 'Sistem Argometer Digital & Manajemen Tarif SK Dishub',
    description: 'Konfigurasi tarif buka pintu (flag fall), tarif per KM, tarif tunggu per jam, surcharge bandara & malam hari, serta sertifikasi Tera Metrologi Legalitas.',
    breadcrumb: ['Taxi', 'Argometer & Tarif'],
    permission: 'cost.view',
    path: '/app/taxi/taximeter',
  },
  taxi_orders: {
    id: 'taxi_orders',
    title: 'Smart Dispatching, On-Demand Booking & Order Ritase',
    description: 'Pusat penugasan pesanan taksi instan via Call Center, Aplikasi Mobile, Concierge Hotel, Pangkalan Bandara, dan Street Hail.',
    breadcrumb: ['Taxi', 'Smart Dispatching'],
    permission: 'trip.view',
    path: '/app/taxi/orders',
  },
  taxi_revenue: {
    id: 'taxi_revenue',
    title: 'Manajemen Setoran Driver & Skema Bagi Hasil (Revenue Sharing)',
    description: 'Pencatatan setoran harian kasir pool, komisi ritase, skema bagi hasil 60:40, bonus loyalitas bulanan, dan jaminan operasional.',
    breadcrumb: ['Taxi', 'Setoran & Bagi Hasil'],
    permission: 'cost.view',
    path: '/app/taxi/revenue',
  },
  taxi_pools: {
    id: 'taxi_pools',
    title: 'Pool Induk & Manajemen Antrean Pangkalan Taksi (Staging Queues)',
    description: 'Pengaturan antrean First-In-First-Out (FIFO) di Bandara Soetta T1/T2/T3, Stasiun Gambir/Senen, Mall, Hotel Bintang 5, dan kapasitas pool.',
    breadcrumb: ['Taxi', 'Pool & Pangkalan FIFO'],
    permission: 'trip.view',
    path: '/app/taxi/pools',
  },
  taxi_energy: {
    id: 'taxi_energy',
    title: 'Manajemen Energi, BBM Bensin, SPBG Gas & SPKLU EV Charging',
    description: 'Monitoring konsumsi energi per KM, status baterai SOC taksi listrik (BYD e6 & Ioniq 5), SPBG converter kit, dan rasio penghematan operasional.',
    breadcrumb: ['Taxi', 'BBM, SPBG & SPKLU EV'],
    permission: 'fuel.view',
    path: '/app/taxi/energy',
  },
  taxi_drivers: {
    id: 'taxi_drivers',
    title: 'Manajemen Pengemudi Taksi, KTA & Roster Shift Operasional',
    description: 'Database lisensi KTA Dishub, SIM A Umum, roster shift 12 Jam / 24 Jam, rating kepuasan penumpang bintang 1-5, dan evaluasi kelelahan pengemudi.',
    breadcrumb: ['Taxi', 'Pengemudi & Roster'],
    permission: 'driver.view',
    path: '/app/taxi/drivers',
  },
  taxi_safety: {
    id: 'taxi_safety',
    title: 'Kamera MDVR Kabin, Tombol Panic SOS & Keamanan Penumpang',
    description: 'Monitoring video kabin 2-arah (jalan & kabin), tombol darurat panic SOS terhubung ke Command Center, dan deteksi argo bypass (penumpang tanpa argo).',
    breadcrumb: ['Taxi', 'Kamera MDVR & Panic SOS'],
    permission: 'safety.view',
    path: '/app/taxi/safety',
  },
  taxi_maintenance: {
    id: 'taxi_maintenance',
    title: 'Perawatan Armada Taksi, Bengkel Pool & Sertifikasi Uji KIR/Tera',
    description: 'Jadwal servis berkala 10.000 KM, ganti oli mesin, rem, tune-up, perbaikan bengkel pool, serta jadwal Uji Berkala KIR Dishub & Kalibrasi Tera Argo.',
    breadcrumb: ['Taxi', 'Perawatan & Uji KIR/Tera'],
    permission: 'maintenance.view',
    path: '/app/taxi/maintenance',
  },
  taxi_lost_found: {
    id: 'taxi_lost_found',
    title: 'Pusat Pengelolaan Barang Tertinggal Penumpang (Lost & Found)',
    description: 'Pencarian nomor lambung taksi, pelaporan barang berharga (smartphone, dompet, koper, dokumen), verifikasi identitas, dan berita acara serah terima.',
    breadcrumb: ['Taxi', 'Lost & Found Penumpang'],
    permission: 'trip.view',
    path: '/app/taxi/lost-found',
  },
  taxi_cashless: {
    id: 'taxi_cashless',
    title: 'Pembayaran Digital Cashless (QRIS & EDC) & Rekonsiliasi Kasir',
    description: 'Penyelesaian transaksi non-tunai QRIS dinamis argo, mesin EDC debit/kredit, auto-settlement bank, dan rekonsiliasi kasir pool.',
    breadcrumb: ['Taxi', 'Pembayaran QRIS & EDC'],
    permission: 'cost.view',
    path: '/app/taxi/cashless',
  },
  taxi_ai_copilot: {
    id: 'taxi_ai_copilot',
    title: 'AI Taxi Operations Copilot & Demand Hotspot Prediction',
    description: 'Prediksi lonjakan permintaan berbasis cuaca hujan, data kedatangan penerbangan bandara, asisten tanya jawab AI, dan rekomendasi relokasi armada.',
    breadcrumb: ['Taxi', 'AI Taxi Demand Copilot'],
    permission: 'ai.view',
    path: '/app/taxi/ai-copilot',
  },
  taxi_reports: {
    id: 'taxi_reports',
    title: 'Pusat Laporan Operasional Harian Taksi (LOH) & Audit Utilisasi',
    description: 'Rekapitulasi ritase harian, rasio Paid KM vs Empty Deadhead KM, setoran kasir pool, produktivitas armada, dan ekspor ke Excel & PDF.',
    breadcrumb: ['Taxi', 'Pusat Laporan LOH & Audit'],
    permission: 'report.view',
    path: '/app/taxi/reports',
  },
  tanker: {
    id: 'tanker',
    title: 'Tanker Truck Management System (TTMS)',
    description: 'Sistem komprehensif manajemen truk tangki cairan: BBM, CPO, bahan kimia berbahaya B3, gas LPG, sensor kompartemen, smart e-lock, dan kepatuhan tera legal.',
    breadcrumb: ['TTMS', 'Tanker Operations'],
    permission: 'trip.view',
    path: '/app/tanker',
  },
  tanker_control_tower: {
    id: 'tanker_control_tower',
    title: 'Menara Kendali Truk Tangki (Live Control Tower)',
    description: 'Peta pemantauan telemetri armada tangki live: status muatan, suhu & densitas kompartemen, status segel e-lock, dan kepatuhan koridor rute.',
    breadcrumb: ['TTMS', 'Menara Kendali Tangki'],
    permission: 'trip.view',
    path: '/app/tanker/control-tower',
  },
  tanker_fleets: {
    id: 'tanker_fleets',
    title: 'Master Armada Tangki & Bejana Cairan Curah',
    description: 'Database registrasi truk tangki: material bejana (Stainless Steel 316L, Aluminium 5083, Carbon Steel), kapasitas total liter, jumlah sekat kompartemen, dan masa berlaku izin.',
    breadcrumb: ['TTMS', 'Master Armada Tangki'],
    permission: 'vehicle.view',
    path: '/app/tanker/fleets',
  },
  tanker_compartments: {
    id: 'tanker_compartments',
    title: 'Sensor Kompartemen & Analisis Susut Cairan (Losses)',
    description: 'Telemetri sensor level cairan ultrasonik per sekat kompartemen, kompensasi temperatur standar 15°C, densitas API, deteksi volume ullage, dan air dasar (bottom water).',
    breadcrumb: ['TTMS', 'Sensor Kompartemen & Susut'],
    permission: 'vehicle.view',
    path: '/app/tanker/compartments',
  },
  tanker_elocks: {
    id: 'tanker_elocks',
    title: 'Smart E-Lock, Segel Elektronik & Katup Bottom Loading',
    description: 'Sistem penguncian terenkripsi multi-titik (Manhole, Foot Valve, API Coupler) dengan otorisasi berbasis Geofence + OTP Dispatcher.',
    breadcrumb: ['TTMS', 'Smart E-Lock & Segel'],
    permission: 'safety.view',
    path: '/app/tanker/elocks',
  },
  tanker_loading_orders: {
    id: 'tanker_loading_orders',
    title: 'Manajemen Order Pengiriman (DO / SPPB) & Gantry Loading',
    description: 'Pencatatan Surat Perintah Pengeluaran Barang, meteran gantry loading terminal, dan verifikasi volume Gross vs Net @15°C.',
    breadcrumb: ['TTMS', 'Order DO & Gantry Loading'],
    permission: 'trip.view',
    path: '/app/tanker/loading-orders',
  },
  tanker_unloading: {
    id: 'tanker_unloading',
    title: 'Bongkar Muatan (Discharge / Unloading) & Flowmeter SPBU/Pabrik',
    description: 'Prosedur pembongkaran aman cairan BBM/CPO/Kimia: verifikasi sounding tangki timbun, flow rate, dan Berita Acara Penerimaan (BAP).',
    breadcrumb: ['TTMS', 'Bongkar Muatan & Flowmeter'],
    permission: 'trip.view',
    path: '/app/tanker/unloading',
  },
  tanker_geofences: {
    id: 'tanker_geofences',
    title: 'Geofencing Koridor Khusus & Zona Larangan Berhenti (Red Zones)',
    description: 'Pengawasan rute resmi angkutan cairan berbahaya, batas kecepatan kurva sloshing, dan proteksi anti-pencurian (kencing cairan).',
    breadcrumb: ['TTMS', 'Koridor Rute & Red Zones'],
    permission: 'safety.view',
    path: '/app/tanker/geofences',
  },
  tanker_safety_hazmat: {
    id: 'tanker_safety_hazmat',
    title: 'Keselamatan B3 (Hazmat ADR), MSDS & Pencegahan Rollover',
    description: 'Kepatuhan regulasi Kementerian Lingkungan Hidup & Kehutanan (KLHK), rambu plakat UN Number, dan sistem proteksi anti-guling (Rollover Stability).',
    breadcrumb: ['TTMS', 'Keselamatan B3 & Rollover'],
    permission: 'safety.view',
    path: '/app/tanker/safety-hazmat',
  },
  tanker_cleaning: {
    id: 'tanker_cleaning',
    title: 'Pencucian Tangki (Tank Cleaning, Degassing & Vapor Recovery)',
    description: 'Fasilitas pencucian uap panas (Steam Wash), Caustic Wash, degassing gas berbahaya, dan penerbitan Clean Tank Certificate (Mencegah Kontaminasi Silang).',
    breadcrumb: ['TTMS', 'Pencucian Tangki & CIP'],
    permission: 'maintenance.view',
    path: '/app/tanker/cleaning',
  },
  tanker_drivers: {
    id: 'tanker_drivers',
    title: 'Pengemudi Tangki B3, Roster Shift & DSS Kelelahan',
    description: 'Database sertifikasi kompetensi pengemudi B3 BNSP, tes alkohol harian (Breathalyzer 0.00‰), skor kelelahan DMS, dan rasio zero-loss.',
    breadcrumb: ['TTMS', 'Pengemudi Tangki B3'],
    permission: 'driver.view',
    path: '/app/tanker/drivers',
  },
  tanker_maintenance: {
    id: 'tanker_maintenance',
    title: 'Perawatan Tangki, Uji Hidrostatis & Tera Metrologi Legal',
    description: 'Jadwal kalibrasi bejana ukur metrologi legalitas (Tanda Tera T2/T3), uji ketebalan pelat tabung (NDT), dan servis katup darurat pneumatik.',
    breadcrumb: ['TTMS', 'Perawatan & Tera Legal'],
    permission: 'maintenance.view',
    path: '/app/tanker/maintenance',
  },
  tanker_billing: {
    id: 'tanker_billing',
    title: 'Tarif Angkutan Cairan (Freight Tariff) & Klaim Susut Losses',
    description: 'Perhitungan ongkos angkut (Rp/Liter/KM atau Kontrak Ritase) dan rekonsiliasi klaim penyusutan cairan (Losses tolerance threshold <0.15%).',
    breadcrumb: ['TTMS', 'Tarif Angkutan & Klaim'],
    permission: 'cost.view',
    path: '/app/tanker/billing',
  },
  tanker_ai_copilot: {
    id: 'tanker_ai_copilot',
    title: 'AI Tanker Operations Copilot & Anomaly Detector',
    description: 'Asisten cerdas pendeteksi anomali densitas/suhu volume cairan, rekomendasi rute koridor bebas zona rawan, dan audit kepatuhan B3 otomatis.',
    breadcrumb: ['TTMS', 'AI Tanker Copilot'],
    permission: 'ai.view',
    path: '/app/tanker/ai-copilot',
  },
  tanker_reports: {
    id: 'tanker_reports',
    title: 'Pusat Laporan Tangki, Audit Kepatuhan & Rekapitulasi Losses',
    description: 'Laporan rekap ritase pengiriman cairan, analisis variansi susut muatan, log pembukaan segel elektronik, dan audit sertifikat uji KIR/Tera.',
    breadcrumb: ['TTMS', 'Laporan Audit & Losses'],
    permission: 'report.view',
    path: '/app/tanker/reports',
  },
  waste: {
    id: 'waste',
    title: 'Waste Transport Fleet Management System',
    description: 'Sistem komprehensif pengelolaan armada truk sampah compactor, arm roll, limbah B3, medis, dan vacuum sludge.',
    breadcrumb: ['Waste Transport', 'Dashboard'],
    permission: 'trip.view',
    path: '/app/waste',
  },
  waste_control_tower: {
    id: 'waste_control_tower',
    title: 'Menara Kendali Angkutan Sampah (Live Control Tower)',
    description: 'Monitoring real-time pergerakan armada truk compactor, arm roll, sensor hidrolik, tonase muatan, dan rute TPA/TPST.',
    breadcrumb: ['Waste Transport', 'Menara Kendali'],
    permission: 'trip.view',
    path: '/app/waste/control-tower',
  },
  waste_fleets: {
    id: 'waste_fleets',
    title: 'Master Armada Pengangkut Sampah & Limbah',
    description: 'Database truk compactor, arm roll, hook lift, vacuum sludge, dan cold box limbah medis dengan izin operasional KLHK.',
    breadcrumb: ['Waste Transport', 'Master Armada'],
    permission: 'vehicle.view',
    path: '/app/waste/fleets',
  },
  waste_routes: {
    id: 'waste_routes',
    title: 'Jadwal & Rute Pengumpulan TPS / Depo Sampah',
    description: 'Perencanaan dan optimasi rute pengumpulan sampah dari TPS 3R, pusat perbelanjaan komersial, pasar, dan kawasan industri.',
    breadcrumb: ['Waste Transport', 'Jadwal & Rute TPS'],
    permission: 'route.view',
    path: '/app/waste/routes',
  },
  waste_manifest_festronik: {
    id: 'waste_manifest_festronik',
    title: 'Manifest Elektronik Limbah B3 (Festronik KLHK)',
    description: 'Integrasi Festronik Kementerian Lingkungan Hidup & Kehutanan untuk validasi tiga pihak: Penghasil, Pengangkut, dan Pengolah.',
    breadcrumb: ['Waste Transport', 'Festronik KLHK'],
    permission: 'trip.view',
    path: '/app/waste/festronik',
  },
  waste_weighbridge: {
    id: 'waste_weighbridge',
    title: 'Jembatan Timbang & Tipping Floor TPA / TPST',
    description: 'Pencatatan bobot kotor (Gross), bobot kosong truk (Tare), tonase bersih (Net Payload), dan zona pembongkaran sampah TPA.',
    breadcrumb: ['Waste Transport', 'Jembatan Timbang'],
    permission: 'trip.view',
    path: '/app/waste/weighbridge',
  },
  waste_containers: {
    id: 'waste_containers',
    title: 'Sensor Kontainer Cerdas & Pelacakan RFID Bin',
    description: 'Sensor level kepenuhan ultrasonik IoT, detektor gas metana/bau (H2S), dan pelacakan siklus swap kontainer.',
    breadcrumb: ['Waste Transport', 'Smart Bin & RFID'],
    permission: 'vehicle.view',
    path: '/app/waste/containers',
  },
  waste_medical_biohazard: {
    id: 'waste_medical_biohazard',
    title: 'Limbah Medis, Biohazard & Cold Chain Transport',
    description: 'Standar pengangkutan limbah infeksius rumah sakit: pendingin cold box <4°C, segel biohazard, dan disinfeksi armada.',
    breadcrumb: ['Waste Transport', 'Limbah Medis Cold Box'],
    permission: 'safety.view',
    path: '/app/waste/medical-biohazard',
  },
  waste_sludge_vacuum: {
    id: 'waste_sludge_vacuum',
    title: 'Armada Vacuum, Sedot Tinja & Lumpur IPAL',
    description: 'Pengelolaan order sedot lumpur tinja (LLTT), kapasitas tangki vacuum, dan pengawasan pembuangan resmi ke IPLT.',
    breadcrumb: ['Waste Transport', 'Sedot Tinja & IPAL'],
    permission: 'trip.view',
    path: '/app/waste/sludge-vacuum',
  },
  waste_safety_compliance: {
    id: 'waste_safety_compliance',
    title: 'Kepatuhan K3 Lingkungan, APD Kru & Spill Kit',
    description: 'Pencegahan ceceran air lindi (leachate spill prevention), kepatuhan APD loader, dan tanggap darurat tumpahan limbah.',
    breadcrumb: ['Waste Transport', 'K3, APD & Spill Kit'],
    permission: 'safety.view',
    path: '/app/waste/safety-compliance',
  },
  waste_crews: {
    id: 'waste_crews',
    title: 'Kinerja Petugas / Kru & Insentif Ritase',
    description: 'Database supir, operator hidrolik compactor, kru loader, absensi shift subuh/malam, dan insentif tonase terangkut.',
    breadcrumb: ['Waste Transport', 'Kinerja Kru & Insentif'],
    permission: 'driver.view',
    path: '/app/waste/crews',
  },
  waste_maintenance: {
    id: 'waste_maintenance',
    title: 'Perawatan Hidrolik, Pompa Vacuum & Disinfeksi',
    description: 'Pemeliharaan silinder hidrolik compactor PTO, pompa vacuum sedot tinja, dan pencucian disinfeksi armada di Washing Bay.',
    breadcrumb: ['Waste Transport', 'Perawatan & Disinfeksi'],
    permission: 'maintenance.view',
    path: '/app/waste/maintenance',
  },
  waste_billing: {
    id: 'waste_billing',
    title: 'Tarif Retribusi, Kontrak B2B & Faktur Billing',
    description: 'Perhitungan tarif tipping fee jembatan timbang, biaya penarikan kontainer arm roll, dan kontrak pengangkutan limbah B3.',
    breadcrumb: ['Waste Transport', 'Tarif Retribusi & Billing'],
    permission: 'cost.view',
    path: '/app/waste/billing',
  },
  waste_ai_copilot: {
    id: 'waste_ai_copilot',
    title: 'AI Waste Operations & Route Optimizer Copilot',
    description: 'Asisten AI untuk prediksi timbulan volume sampah, efisiensi rute penjemputan TPS, dan validasi kepatuhan Festronik B3.',
    breadcrumb: ['Waste Transport', 'AI Waste Copilot'],
    permission: 'ai.view',
    path: '/app/waste/ai-copilot',
  },
  waste_reports: {
    id: 'waste_reports',
    title: 'Pusat Laporan, Neraca Limbah B3 & Audit KLHK',
    description: 'Rekapitulasi tonase harian TPA, neraca limbah B3 Festronik, kepatuhan emisi armada, dan ekspor laporan resmi AMDAL/KLHK.',
    breadcrumb: ['Waste Transport', 'Pusat Laporan KLHK'],
    permission: 'report.view',
    path: '/app/waste/reports',
  },
  securicor: {
    id: 'securicor',
    title: 'Securicor & Cash-In-Transit (CIT) Fleet System',
    description: 'Sistem komprehensif pengangkutan uang tunai, mobil lapis baja balistik, smart vault, dan pengawalan bersenjata POLRI.',
    breadcrumb: ['Securicor', 'Dashboard'],
    permission: 'trip.view',
    path: '/app/securicor',
  },
  securicor_control_tower: {
    id: 'securicor_control_tower',
    title: 'Menara Kendali Lapis Baja (CIT Live Control Tower)',
    description: 'Monitoring real-time pergerakan armada lapis baja, nilai uang tunai angkut, status solenoid pintu airlock, dan sensor getaran/serangan.',
    breadcrumb: ['Securicor', 'Menara Kendali'],
    permission: 'trip.view',
    path: '/app/securicor/control-tower',
  },
  securicor_armored_fleets: {
    id: 'securicor_armored_fleets',
    title: 'Master Armada Lapis Baja (B6/B7 Ballistic Armor)',
    description: 'Spesifikasi fisik van CIT lapis baja, ban run-flat anti-kempes, drop chute uang tunai, dan sertifikasi balistik STANAG.',
    breadcrumb: ['Securicor', 'Master Armada'],
    permission: 'vehicle.view',
    path: '/app/securicor/fleets',
  },
  securicor_cit_missions: {
    id: 'securicor_cit_missions',
    title: 'Manifest Misi Cash-in-Transit (CIT Manifest)',
    description: 'Penerbitan manifest pengawalan uang, otorisasi dua kunci (Dual-Custody Key A & B), dan kode verifikasi serah terima kas.',
    breadcrumb: ['Securicor', 'Manifest CIT'],
    permission: 'trip.view',
    path: '/app/securicor/missions',
  },
  securicor_smart_vault: {
    id: 'securicor_smart_vault',
    title: 'Khazanah Brankas & Kaset Smart Dye/Smoke',
    description: 'Pusat brankas elektronik, kaset ATM anti-pembobolan dengan pewarna tinta (Indelible Dye Staining), dan sensor seismik thermal.',
    breadcrumb: ['Securicor', 'Khazanah & Smart Vault'],
    permission: 'trip.view',
    path: '/app/securicor/vault',
  },
  securicor_atm_replenishment: {
    id: 'securicor_atm_replenishment',
    title: 'Pengisian Kas ATM & First Line Maintenance (FLM)',
    description: 'Jadwal pengisian kaset ATM CRM perbankan, audit sisa uang (purge/reject tray), dan pemeliharaan teknis modul hardware ATM.',
    breadcrumb: ['Securicor', 'Pengisian ATM & FLM'],
    permission: 'trip.view',
    path: '/app/securicor/atm-flm',
  },
  securicor_patrol_guards: {
    id: 'securicor_patrol_guards',
    title: 'Patroli Pengamanan & Live Bodycam Stream',
    description: 'Pemantauan rute ronda satpam khazanah via NFC checkpoint, streaming kamera tubuh (bodycam), dan status kesiapsiagaan shift.',
    breadcrumb: ['Securicor', 'Patroli & Bodycam'],
    permission: 'safety.view',
    path: '/app/securicor/patrol-guards',
  },
  securicor_duress_emergency: {
    id: 'securicor_duress_emergency',
    title: 'Pusat Alarm Duress, Tombol Panik & Anti-Hijack SOS',
    description: 'Penanganan sinyal darurat silent panic button, remote engine kill interlock, dan koordinasi taktis langsung ke SPKT Polda Metro Jaya.',
    breadcrumb: ['Securicor', 'Alarm Duress & SOS'],
    permission: 'safety.view',
    path: '/app/securicor/duress-emergency',
  },
  securicor_armed_officers: {
    id: 'securicor_armed_officers',
    title: 'Pengawal Bersenjata & Izin Senpi Khusus (IKH)',
    description: 'Database personil pengawal bersenjata, nomor KTA POLRI, masa berlaku izin khusus senjata api dinas, dan sertifikasi menembak.',
    breadcrumb: ['Securicor', 'Pengawal Bersenjata'],
    permission: 'driver.view',
    path: '/app/securicor/armed-officers',
  },
  securicor_geofence_corridors: {
    id: 'securicor_geofence_corridors',
    title: 'Koridor Hijau Rute Pengawalan & No-Stop Zone',
    description: 'Penetapan koridor jalur aman VVIP, peringatan deviasi konvoi >50 meter, dan zona larangan berhenti darurat (No-Stop Area).',
    breadcrumb: ['Securicor', 'Koridor Rute Geofence'],
    permission: 'route.view',
    path: '/app/securicor/geofence-corridors',
  },
  securicor_armor_maintenance: {
    id: 'securicor_armor_maintenance',
    title: 'Perawatan Balistik, Kaca Anti-Peluru & Solenoid',
    description: 'Pemeliharaan pelat baja balistik, inspeksi delaminasi kaca antipeluru, servis ban run-flat, dan kalibrasi solenoid kunci brankas.',
    breadcrumb: ['Securicor', 'Perawatan Balistik'],
    permission: 'maintenance.view',
    path: '/app/securicor/armor-maintenance',
  },
  securicor_insurance_billing: {
    id: 'securicor_insurance_billing',
    title: 'Asuransi Kas CIT & Tarif Penagihan Bank (Billing)',
    description: 'Pengelolaan polis asuransi pengangkutan uang (Cash In Transit Policy Lloyd’s), deductible risiko, dan kalkulasi tagihan ritase bank.',
    breadcrumb: ['Securicor', 'Asuransi & Billing'],
    permission: 'cost.view',
    path: '/app/securicor/insurance-billing',
  },
  securicor_ai_copilot: {
    id: 'securicor_ai_copilot',
    title: 'AI Securicor Tactical Threat & Route Copilot',
    description: 'Asisten kecerdasan buatan Gemini untuk kalkulasi skor risiko ancaman penyergapan (ambush risk score) dan rute taktis.',
    breadcrumb: ['Securicor', 'AI Tactical Copilot'],
    permission: 'ai.view',
    path: '/app/securicor/ai-copilot',
  },
  securicor_reports: {
    id: 'securicor_reports',
    title: 'Pusat Laporan Audit Bank Indonesia (PUPR)',
    description: 'Rekapitulasi transaksi kas CIT, kepatuhan regulasi PBI Jasa Pengolahan Uang Rupiah (PUPR), dan log audit chain-of-custody.',
    breadcrumb: ['Securicor', 'Pusat Laporan Audit'],
    permission: 'report.view',
    path: '/app/securicor/reports',
  },
  corporate: {
    id: 'corporate',
    title: 'Corporate Company Vehicle Management System',
    description: 'Sistem Terpadu Pengelolaan Mobil Dinas, Sharing Pool Karyawan, Mobil Jabatan Direksi, Smart Key Locker, dan Kontrak Sewa Leasing Korporat.',
    breadcrumb: ['Corporate', 'Dashboard'],
    permission: 'trip.view',
    path: '/app/corporate',
  },
  corp_control_tower: {
    id: 'corp_control_tower',
    title: 'Menara Kendali Pool Mobil Dinas (GA Control Tower)',
    description: 'Live radar pemantauan posisi mobil pool di jalan, ketersediaan unit di basement parkir HO, status loker kunci smart keybox, dan antrean reservasi.',
    breadcrumb: ['Corporate Fleet', 'Menara Kendali Pool'],
    permission: 'trip.view',
    path: '/app/corporate/control-tower',
  },
  corp_vehicles: {
    id: 'corp_vehicles',
    title: 'Master Database Kendaraan, Pool & Mobil Jabatan',
    description: 'Master inventaris kendaraan dinas, model kepemilikan (Operating Lease / Owned / COP), divisi pengampu, dan telematika OBD-II.',
    breadcrumb: ['Corporate Fleet', 'Master Kendaraan'],
    permission: 'vehicle.view',
    path: '/app/corporate/vehicles',
  },
  corp_bookings: {
    id: 'corp_bookings',
    title: 'Pemesanan & Reservasi E-Booking Mobil Dinas',
    description: 'Alur permohonan reservasi kendaraan sharing pool, verifikasi tujuan meeting bisnis, approval bertingkat GA, dan surat izin keluar (SIMK).',
    breadcrumb: ['Corporate Fleet', 'E-Booking Dinas'],
    permission: 'trip.view',
    path: '/app/corporate/bookings',
  },
  corp_keybox: {
    id: 'corp_keybox',
    title: 'Smart Keybox Locker B1 & Virtual Keyless Smartphone',
    description: 'Loker kunci pintar berbasis RFID ID Card / OTP Booking, integrasi BLE virtual key smartphone, dan pencatatan odometer check-in/out.',
    breadcrumb: ['Corporate Fleet', 'Smart Keybox'],
    permission: 'trip.view',
    path: '/app/corporate/keybox',
  },
  corp_inspections: {
    id: 'corp_inspections',
    title: 'Inspeksi Digital Pra/Pasca Pakai & Checklist Baret Body',
    description: 'Formulir digital serah terima kondisi fisik 360°, verifikasi tekanan ban, level bahan bakar, sisa saldo e-Toll, dan kebersihan kabin.',
    breadcrumb: ['Corporate Fleet', 'Inspeksi & Serah Terima'],
    permission: 'safety.view',
    path: '/app/corporate/inspections',
  },
  corp_drivers: {
    id: 'corp_drivers',
    title: 'Manajemen Supir Pool Kantor & Chauffeur VIP Direksi',
    description: 'Penugasan pengemudi operasional kantor, monitoring jam lembur dinas (GA Overtime), masa berlaku SIM, dan rating kepuasan karyawan.',
    breadcrumb: ['Corporate Fleet', 'Supir Pool & VIP'],
    permission: 'driver.view',
    path: '/app/corporate/drivers',
  },
  corp_fuel_toll: {
    id: 'corp_fuel_toll',
    title: 'Kartu BBM Korporat, Saldo E-Toll & Reimbursement Kasbon',
    description: 'Pengelolaan kartu Pertamina/Shell Corporate Fleet, top-up saldo kartu e-Toll Mandiri/BCA, audit rasio KM/Liter, dan validasi struk kasbon.',
    breadcrumb: ['Corporate Fleet', 'BBM & E-Toll'],
    permission: 'cost.view',
    path: '/app/corporate/fuel-toll',
  },
  corp_policy_compliance: {
    id: 'corp_policy_compliance',
    title: 'Penegakan Car Policy, Jam Malam & Geofence Wilayah',
    description: 'Pemantauan otomatis pelanggaran mobil dinas di luar jam kerja (After-Hours Usage), perjalanan luar kota tanpa SPPD, dan batas kecepatan.',
    breadcrumb: ['Corporate Fleet', 'Car Policy & Kepatuhan'],
    permission: 'safety.view',
    path: '/app/corporate/policy-compliance',
  },
  corp_compliance_lease: {
    id: 'corp_compliance_lease',
    title: 'Manajemen Kontrak Sewa Vendor (TRAC/MPM/ASSA) & STNK',
    description: 'Pemantauan masa berlaku kontrak sewa operasional, jadwal perpanjangan pajak STNK tahunan/5-tahunan, dan klaim asuransi All-Risk.',
    breadcrumb: ['Corporate Fleet', 'Kontrak Sewa & Pajak'],
    permission: 'cost.view',
    path: '/app/corporate/compliance-lease',
  },
  corp_maintenance: {
    id: 'corp_maintenance',
    title: 'Jadwal Servis Berkala & Bengkel Resmi Dealer',
    description: 'Booking servis berkala 10.000 KM di Auto2000/Hyundai, penggantian suku cadang/ban, dan klaim free maintenance operating lease.',
    breadcrumb: ['Corporate Fleet', 'Servis & Bengkel'],
    permission: 'maintenance.view',
    path: '/app/corporate/maintenance',
  },
  corp_cost_centers: {
    id: 'corp_cost_centers',
    title: 'Alokasi Beban Operasional per Cost Center Divisi',
    description: 'Pembebanan proporsional biaya sewa lease, konsumsi BBM, tol, dan lembur supir ke masing-masing anggaran departemen (Sales/IT/HR/BOD).',
    breadcrumb: ['Corporate Fleet', 'Cost Center Divisi'],
    permission: 'cost.view',
    path: '/app/corporate/cost-centers',
  },
  corp_ai_copilot: {
    id: 'corp_ai_copilot',
    title: 'AI Corporate Fleet Optimizer & TCO Copilot',
    description: 'Asisten cerdas Gemini untuk analisis utilisasi pool, studi kelayakan Sewa (Lease) vs Beli (CapEx), serta kalkulasi transisi armada EV.',
    breadcrumb: ['Corporate Fleet', 'AI Fleet Copilot'],
    permission: 'ai.view',
    path: '/app/corporate/ai-copilot',
  },
  corp_reports: {
    id: 'corp_reports',
    title: 'Pusat Laporan Eksekutif, Beban TCO & ESG Green Fleet',
    description: 'Rekapitulasi performa pool sharing, laporan TCO untuk Direksi & Finance SAP/Oracle, serta reduksi emisi karbon ESG Scope 1.',
    breadcrumb: ['Corporate Fleet', 'Pusat Laporan Eksekutif'],
    permission: 'report.view',
    path: '/app/corporate/reports',
  },
  security: {
    id: 'security',
    title: 'Enterprise Security & Zero Trust Center',
    description: 'Pusat keamanan enterprise: Enkripsi AES-256-GCM, manajemen sesi aktif, rate limiting, isolasi tenant & cabang, AI DLP, GPS firewall, dan disaster recovery.',
    breadcrumb: ['Sistem', 'Enterprise Security'],
    permission: 'security.view',
    path: '/app/security',
  },
};
