/**
 * Fleet Intelligence Smart AI - Report Templates Management Service
 * PROMPT 39 - Reusable Report Configurations, Standard Templates & Favorites
 */

import { ReportTemplate } from '../types';

export const INITIAL_REPORT_TEMPLATES: ReportTemplate[] = [
  {
    id: 'TPL-EXECUTIVE-MONTHLY',
    tenantId: 'tenant-default',
    name: 'Executive Board of Directors Monthly Briefing',
    type: 'EXECUTIVE',
    subType: 'EXECUTIVE_MONTHLY',
    description: 'Laporan komprehensif bulanan direksi merangkum utilisasi armada, total operating cost, efisiensi solar, safety score, dan rekomendasi AI.',
    tags: ['Executive', 'Management', 'Finance', 'Board'],
    columns: ['metricCategory', 'currentMonthValue', 'targetBenchmark', 'variancePct', 'trendStatus', 'financialImpactIdr', 'aiObservation'],
    filters: {
      periodPreset: 'THIS_MONTH',
      startDate: '2026-08-01',
      endDate: '2026-08-17',
      branchId: 'ALL',
    },
    grouping: 'NONE',
    sortBy: 'metricCategory',
    sortDirection: 'ASC',
    visualization: 'TABLE',
    aiSummaryEnabled: true,
    isDefault: true,
    isFavorite: true,
    usageCount: 142,
    createdBy: 'Director of Operations',
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-08-15T14:30:00Z',
  },
  {
    id: 'TPL-COST-TOC-STATEMENT',
    tenantId: 'tenant-default',
    name: 'Total Operating Cost (TOC) & Cost/KM Statement',
    type: 'COST',
    subType: 'COST_OPERATING',
    description: 'Rincian seluruh pos pengeluaran operasional per unit (Solar, Bengkel, Driver, Tol, Asuransi) dengan analisis biaya per kilometer.',
    tags: ['Finance', 'Cost', 'Operations', 'Audit'],
    columns: ['vehiclePlate', 'branchName', 'fuelCostIdr', 'maintenanceCostIdr', 'driverCostIdr', 'tollParkingCostIdr', 'totalCostIdr', 'totalDistanceKm', 'costPerKmIdr'],
    filters: {
      periodPreset: 'THIS_MONTH',
      startDate: '2026-08-01',
      endDate: '2026-08-17',
      branchId: 'ALL',
    },
    grouping: 'BRANCH',
    sortBy: 'totalCostIdr',
    sortDirection: 'DESC',
    visualization: 'BAR_CHART',
    aiSummaryEnabled: true,
    isDefault: true,
    isFavorite: true,
    usageCount: 238,
    createdBy: 'Head of Finance & Fleet',
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-08-16T11:00:00Z',
  },
  {
    id: 'TPL-FUEL-ANOMALY-AUDIT',
    tenantId: 'tenant-default',
    name: 'Audit Konsumsi BBM & Deteksi Anomali Solar',
    type: 'FUEL',
    subType: 'FUEL_ANOMALY',
    description: 'Pendeteksian unit kendaraan dengan penyimpangan rasio KM/L ekstrem, pemborosan idling mesin, dan indikasi pencurian solar.',
    tags: ['Fuel', 'Operations', 'Audit', 'AI'],
    columns: ['date', 'vehiclePlate', 'driverName', 'expectedKmL', 'actualKmL', 'variancePct', 'possibleCause', 'threatLevel', 'estimatedLossIdr'],
    filters: {
      periodPreset: 'THIS_MONTH',
      startDate: '2026-08-01',
      endDate: '2026-08-17',
      branchId: 'ALL',
    },
    grouping: 'NONE',
    sortBy: 'variancePct',
    sortDirection: 'ASC',
    visualization: 'TABLE',
    aiSummaryEnabled: true,
    isDefault: true,
    isFavorite: true,
    usageCount: 185,
    createdBy: 'Fleet Fuel Specialist',
    createdAt: '2026-03-05T10:00:00Z',
    updatedAt: '2026-08-17T09:15:00Z',
  },
  {
    id: 'TPL-DRIVER-SAFETY-SCORECARD',
    tenantId: 'tenant-default',
    name: 'Driver Behavior & Safety Scorecard Terpadu',
    type: 'DRIVER',
    subType: 'DRIVER_PERFORMANCE',
    description: 'Evaluasi perilaku mengemudi bulanan mencakup overspeed, harsh braking, jam idle, tingkat kelelahan, dan skor risiko safety.',
    tags: ['Safety', 'Driver', 'HR', 'Coaching'],
    columns: ['driverName', 'branchName', 'totalTrips', 'totalDistanceKm', 'overspeedCount', 'harshBrakingCount', 'idleHours', 'safetyScore', 'riskRank'],
    filters: {
      periodPreset: 'THIS_MONTH',
      startDate: '2026-08-01',
      endDate: '2026-08-17',
      branchId: 'ALL',
    },
    grouping: 'BRANCH',
    sortBy: 'safetyScore',
    sortDirection: 'ASC',
    visualization: 'LINE_CHART',
    aiSummaryEnabled: true,
    isDefault: true,
    isFavorite: false,
    usageCount: 164,
    createdBy: 'HSE Safety Manager',
    createdAt: '2026-02-15T14:00:00Z',
    updatedAt: '2026-08-12T16:20:00Z',
  },
  {
    id: 'TPL-MAINTENANCE-WO-COST',
    tenantId: 'tenant-default',
    name: 'Rekapitulasi Pemeliharaan & Biaya Servis Berkala',
    type: 'MAINTENANCE',
    subType: 'MAINTENANCE_COST',
    description: 'Laporan Work Order bengkel, penggantian suku cadang, biaya jasa mekanik, dan jadwal servis berkala yang akan jatuh tempo.',
    tags: ['Maintenance', 'Workshop', 'Cost'],
    columns: ['orderNumber', 'vehiclePlate', 'serviceType', 'serviceDate', 'workshopName', 'partsReplaced', 'partsCostIdr', 'laborCostIdr', 'totalCostIdr', 'status'],
    filters: {
      periodPreset: 'THIS_MONTH',
      startDate: '2026-08-01',
      endDate: '2026-08-17',
      branchId: 'ALL',
    },
    grouping: 'NONE',
    sortBy: 'serviceDate',
    sortDirection: 'DESC',
    visualization: 'TABLE',
    aiSummaryEnabled: true,
    isDefault: true,
    isFavorite: false,
    usageCount: 119,
    createdBy: 'Workshop Supervisor',
    createdAt: '2026-04-01T08:30:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'TPL-GPS-MILEAGE-ACTIVITY',
    tenantId: 'tenant-default',
    name: 'Log Jarak Tempuh & Jam Kerja GPS Telematika',
    type: 'GPS',
    subType: 'GPS_MILEAGE',
    description: 'Rekapitulasi odometer awal/akhir, total kilometer, jam bergerak, dan jam idling telemetri sensor IoT GPS armada.',
    tags: ['GPS', 'Telematics', 'Operations'],
    columns: ['vehiclePlate', 'driverName', 'startMileage', 'endMileage', 'distance', 'drivingHours', 'idleHours', 'stopHours'],
    filters: {
      periodPreset: 'THIS_WEEK',
      startDate: '2026-08-11',
      endDate: '2026-08-17',
      branchId: 'ALL',
    },
    grouping: 'NONE',
    sortBy: 'distance',
    sortDirection: 'DESC',
    visualization: 'BAR_CHART',
    aiSummaryEnabled: false,
    isDefault: true,
    isFavorite: false,
    usageCount: 95,
    createdBy: 'GPS Dispatch Lead',
    createdAt: '2026-03-20T11:00:00Z',
    updatedAt: '2026-08-17T07:45:00Z',
  },
];
