/**
 * Fleet Intelligence Smart AI - Scheduled Reports Engine
 * PROMPT 39 - Automated Multi-Channel Report Delivery & Cron Management
 */

import { ReportSchedule } from '../types';

export const INITIAL_SCHEDULED_REPORTS: ReportSchedule[] = [
  {
    id: 'SCH-01',
    tenantId: 'tenant-default',
    name: 'Briefing Eksekutif Mingguan Direksi (Setiap Senin 08:00 WIB)',
    templateId: 'TPL-EXECUTIVE-MONTHLY',
    reportType: 'EXECUTIVE',
    subType: 'EXECUTIVE_WEEKLY',
    frequency: 'WEEKLY',
    timeOfDay: '08:00',
    dayOfWeek: 1, // Monday
    timezone: 'Asia/Jakarta',
    recipients: ['director@fleet-smart.ai', 'general.manager@fleet-smart.ai', 'operations.vp@fleet-smart.ai'],
    formats: ['PDF', 'EXCEL'],
    channels: ['EMAIL', 'IN_APP', 'PUSH'],
    filters: {
      periodPreset: 'LAST_WEEK',
      startDate: '2026-08-10',
      endDate: '2026-08-16',
      branchId: 'ALL',
    },
    aiSummaryEnabled: true,
    enabled: true,
    lastRunAt: '2026-08-17T08:00:00Z',
    lastStatus: 'SUCCESS',
    nextRunAt: '2026-08-24T08:00:00Z',
    createdBy: 'Director of Operations',
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'SCH-02',
    tenantId: 'tenant-default',
    name: 'Rekonsiliasi Biaya Operasional & TOC Bulanan (Tanggal 1)',
    templateId: 'TPL-COST-TOC-STATEMENT',
    reportType: 'COST',
    subType: 'COST_OPERATING',
    frequency: 'MONTHLY',
    timeOfDay: '09:00',
    dayOfMonth: 1,
    timezone: 'Asia/Jakarta',
    recipients: ['finance.lead@fleet-smart.ai', 'accounting@fleet-smart.ai', 'cfo@fleet-smart.ai'],
    formats: ['EXCEL', 'PDF'],
    channels: ['EMAIL', 'IN_APP'],
    filters: {
      periodPreset: 'LAST_MONTH',
      startDate: '2026-07-01',
      endDate: '2026-07-31',
      branchId: 'ALL',
    },
    aiSummaryEnabled: true,
    enabled: true,
    lastRunAt: '2026-08-01T09:00:00Z',
    lastStatus: 'SUCCESS',
    nextRunAt: '2026-09-01T09:00:00Z',
    createdBy: 'Head of Finance',
    createdAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'SCH-03',
    tenantId: 'tenant-default',
    name: 'Laporan Audit Anomali BBM & Deteksi Siphon Harian (07:00 WIB)',
    templateId: 'TPL-FUEL-ANOMALY-AUDIT',
    reportType: 'FUEL',
    subType: 'FUEL_ANOMALY',
    frequency: 'DAILY',
    timeOfDay: '07:00',
    timezone: 'Asia/Jakarta',
    recipients: ['fuel.supervisor@fleet-smart.ai', 'fleet.manager@fleet-smart.ai'],
    formats: ['PDF', 'CSV'],
    channels: ['EMAIL', 'IN_APP', 'WHATSAPP'],
    filters: {
      periodPreset: 'YESTERDAY',
      startDate: '2026-08-16',
      endDate: '2026-08-16',
      branchId: 'ALL',
    },
    aiSummaryEnabled: true,
    enabled: true,
    lastRunAt: '2026-08-17T07:00:00Z',
    lastStatus: 'SUCCESS',
    nextRunAt: '2026-08-18T07:00:00Z',
    createdBy: 'Fleet Fuel Lead',
    createdAt: '2026-03-01T07:00:00Z',
  },
  {
    id: 'SCH-04',
    tenantId: 'tenant-default',
    name: 'Audit Kepatuhan Safety & Overspeed Mingguan (Setiap Jumat)',
    templateId: 'TPL-DRIVER-SAFETY-SCORECARD',
    reportType: 'SAFETY',
    subType: 'SAFETY_SUMMARY',
    frequency: 'WEEKLY',
    timeOfDay: '17:00',
    dayOfWeek: 5, // Friday
    timezone: 'Asia/Jakarta',
    recipients: ['safety.officer@fleet-smart.ai', 'hr.coaching@fleet-smart.ai'],
    formats: ['PDF'],
    channels: ['EMAIL', 'PUSH'],
    filters: {
      periodPreset: 'THIS_WEEK',
      startDate: '2026-08-11',
      endDate: '2026-08-17',
      branchId: 'ALL',
    },
    aiSummaryEnabled: true,
    enabled: true,
    lastRunAt: '2026-08-15T17:00:00Z',
    lastStatus: 'SUCCESS',
    nextRunAt: '2026-08-22T17:00:00Z',
    createdBy: 'HSE Safety Manager',
    createdAt: '2026-03-10T14:00:00Z',
  },
];
